In [2]:
import pandas as pd
import numpy as np
import os

In [4]:
E379 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Performance_ExpFarm/Validación probioticos 18_11_2024.xlsx", "Data to stat")
E379.head()

,Battery,Line,Block 1,Cage,Operator,Trts,Trt,Block 2,Formulated EM Pst (Kcal/Kg),Formulated EM St (kcal/kg),...,Mort + Cull 0 - 42d (%),EM intake 29-35d (kcal).1,kacl intake/Kg 29-35d.1,g dLys intake 29-35d.1,g dLys intake/kg BWG 29-35d.1,g Ca intake 29-35d.1,g Ca intake/ kg BWG 29-35d.1,g P intake 29-35d.1,g P intake/ kg BWG 29-35d.1,$/kg BWG 29-35d.1
0,2,B,B,14,NaN,3,UORA,1,NaN,3020,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,A,A,15,NaN,1,CONTROL,1,NaN,3020,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,B,B,18,NaN,2,GALLIPRO FIT,1,NaN,3020,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,B,B,24,NaN,1,CONTROL,2,NaN,3020,...,3.125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,A,A,25,NaN,3,UORA,2,NaN,3020,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
print(list(E379.columns))
E379["ProjectID"] = 'E379'
E379.head()

['Battery', 'Line', 'Block 1', 'Cage', 'Operator', 'Trts', 'Trt', 'Block 2', 'Formulated EM Pst (Kcal/Kg)', 'Formulated EM St (kcal/kg)', 'Formulated EM Gw (kcal/kg)', 'Formulated EM Fs (kcal/kg)', 'Formulated dLys Pst (%)', 'Formulated dLys St (%)', 'Formulated dLys Gw (%)', 'Formulated dLys Fs (%)', 'Analyzed Ca Pst (%)', 'Analyzed Ca St (%)', 'Analyzed Ca Gw (%)', 'Analyzed Ca Fs (%)', 'analyzed P Pst (%)', 'analyzed P St (%)', 'analyzed P Gw (%)', 'analyzed P Fs (%)', 'Pst diet cost ($/Kg)', 'St diet cost ($/Kg)', 'Gw diet cost ($/Kg)', 'Fs diet cost ($/Kg)', 'BW1 (g)', 'BW7  (g)', 'FI 0-7d  (g)', 'BWG 0-7d (g)', 'BWG 0-7d (g) correct', 'FCR 0-7d  (g:g)', 'FCR 0-7d corrected (g:g)', 'Mortality 0-7d (%)', 'Culling 0-7d (%)', 'Mort + Cull 0-7d (%)', 'kg/m2 0-7d', 'EM intake 0-7d (kcal)', 'kacl intake/Kg 0-7d', 'g dLys intake 0-7', 'g dLys intake/kg BWG 0-7d', 'g Ca intake 0-7d', 'g Ca intake/ kg BWG 0-7d', 'g P intake 0-7d', 'g P intake/ kg BWG 0-7d', '$/kg BWG 0-7d', 'BW14 (g)', 'FI 8-14d (g)', 'BWG 8-14d  (g) ', 'BWG 8-14d  (g) correct', 'FCR 8-14d  (g:g) ', 'FCR 8-14d corrected (g:g) ', 'Mortality 8-14d (%)', 'Culling 8-14d (%)', 'Mort + Cull 8-14d (%)', 'kg/m2 8-14d', 'EM intake 8-14d (kcal)', 'kacl intake/Kg 8-14d', 'g dLys intake 8-14d', 'g dLys intake/kg BWG 8-14dd', 'g Ca intake 8-14d', 'g Ca intake/ kg BWG 8-14d', 'g P intake 8-14d', 'g P intake/ kg BWG 8-14d', '$/kg BWG 8-14d', 'BW21  (g)', 'FI 15-21d  (g)', 'BWG 15-21d (g) ', 'BWG 15-21d (g) correct', 'FCR 15-21d (g:g) ', 'FCR 15-21d corrected (g:g) ', 'Mortality 15-21d (%)', 'Culling 15-21dd (%)', 'Mort + Cull 15-21d (%)', 'kg/m2 15-21d', 'EM intake 15-21d (kcal)', 'kacl intake/Kg 15-21d', 'g dLys intake 15-21d', 'g dLys intake/kg BWG 15-21d', 'g Ca intake 15-21d', 'g Ca intake/ kg BWG 15-21d', 'g P intake 15-21d', 'g P intake/ kg BWG 15-21d', '$/kg BWG 15-21d', 'FI 0-21d (g)', 'BWG 0-21d (g) ', 'BWG 0-21d (g) correct', 'FCR 0-21d (g:g) ', 'FCR 0-21d corrected (g:g) ', 'Mortality 0 - 21d (%)', 'Culling 0 - 21d (%)', 'Mort + Cull 0 - 21d (%)', 'EM intake 0-21d (kcal)', 'kacl intake/Kg 0-21d', 'g dLys intake 0-21d', 'g dLys intake/kg BWG 0-21d', 'g Ca intake 0-21d', 'g Ca intake/ kg BWG 0-21d', 'g P intake 0-21d', 'g P intake/ kg BWG 0-21d', '$/kg BWG 0-21d', 'BW28  (g)', 'FI 22-28d  (g)', 'BWG 22-28d  (g)', 'BWG 22-28d  (g) correct', 'FCR 22-28d (g:g) ', 'FCR 22-28d corrected (g:g) ', 'Mortality 22 - 28d (%)', 'Culling 22 - 28d (%)', 'Mort + Cull 22 - 28d (%)', 'kg/m2 22-28d', 'EM intake 22-28d (kcal)', 'kacl intake/Kg 22-28d', 'g dLys intake 22-28d', 'g dLys intake/kg BWG 22-28d', 'g Ca intake 22-28d', 'g Ca intake/ kg BWG 22-28d', 'g P intake 22-28d', 'g P intake/ kg BWG 22-28d', '$/kg BWG 22-28d', 'BW35  (g)', 'FI 29-35d  (g)', 'BWG 29-35d  (g)', 'BWG 29-35d  (g) correct', 'FCR 29-35d (g:g) ', 'FCR 29-35d corrected (g:g) ', 'Mortality 29 - 35d (%)', 'Culling 29 - 35d (%)', 'Mort + Cull 29 - 35d (%)', 'kg/m2 29-35d', 'EM intake 29-35d (kcal)', 'kacl intake/Kg 29-35d', 'g dLys intake 29-35d', 'g dLys intake/kg BWG 29-35d', 'g Ca intake 29-35d', 'g Ca intake/ kg BWG 29-35d', 'g P intake 29-35d', 'g P intake/ kg BWG 29-35d', '$/kg BWG 29-35d', 'BW42  (g)', 'FI 36-42d  (g)', 'BWG 36-42d  (g)', 'BWG 36-42d  (g) correct', 'FCR 36-42d (g:g) ', 'FCR 36-42d corrected (g:g) ', 'Mortality 36 - 42d (%)', 'Culling 36 - 42d (%)', 'Mort + Cull 36 - 42d (%)', 'kg/m2 36-42d', 'EM intake 36-42d (kcal)', 'kacl intake/Kg 36-42d', 'g dLys intake 36-42d', 'g dLys intake/kg BWG 36-42d', 'g Ca intake 36-42d', 'g Ca intake/ kg BWG 36-42d', 'g P intake 36-42d', 'g P intake/ kg BWG 36-42d', '$/kg BWG 36-42d', 'FI 22-42 (g)', 'BWG 22-42d  (g) ', 'BWG 22-42d  (g) correct', 'FCR 22-42d (g:g) ', 'FCR 22-42d corrected (g:g) ', 'Mortality 22 - 42d (%)', 'Culling 22 - 42d (%)', 'Mort + Cull 22 - 42d (%)', 'EM intake 22-42d (kcal)', 'kacl intake/Kg 22-42d', 'g dLys intake 22-42d', 'g dLys intake/kg BWG 22-42d', 'g Ca intake 22-42d', 'g Ca intake/ kg BWG 22-42d', 'g P intake 22-42d', 'g P intake/ kg BWG 22-42d', '$/kg BWG 22-42d', 'FI 0-42d  (g)', 'BWG 0-42d  (g) ', 'BWG 0-42d  (g) correct', 'FCR 0-42d (g:g) ', 'FCR 0-42d corrected (g:g) ', 'Mortality 0 - 42d (%)', 'Culling 0 - 42d (%)', 'Mort + Cull 0 - 42d (%)', 'EM intake 29-35d (kcal).1', 'kacl intake/Kg 29-35d.1', 'g dLys intake 29-35d.1', 'g dLys intake/kg BWG 29-35d.1', 'g Ca intake 29-35d.1', 'g Ca intake/ kg BWG 29-35d.1', 'g P intake 29-35d.1', 'g P intake/ kg BWG 29-35d.1', '$/kg BWG 29-35d.1']

,Battery,Line,Block 1,Cage,Operator,Trts,Trt,Block 2,Formulated EM Pst (Kcal/Kg),Formulated EM St (kcal/kg),...,EM intake 29-35d (kcal).1,kacl intake/Kg 29-35d.1,g dLys intake 29-35d.1,g dLys intake/kg BWG 29-35d.1,g Ca intake 29-35d.1,g Ca intake/ kg BWG 29-35d.1,g P intake 29-35d.1,g P intake/ kg BWG 29-35d.1,$/kg BWG 29-35d.1,ProjectID
0,2,B,B,14,NaN,3,UORA,1,NaN,3020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E379
1,2,A,A,15,NaN,1,CONTROL,1,NaN,3020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E379
2,2,B,B,18,NaN,2,GALLIPRO FIT,1,NaN,3020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E379
3,3,B,B,24,NaN,1,CONTROL,2,NaN,3020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E379
4,3,A,A,25,NaN,3,UORA,2,NaN,3020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E379

In [5]:
E379[[i for i in E379.columns if "21" in i]].columns

Index(['BW21  (g)', 'FI 15-21d  (g)', 'BWG 15-21d (g) ',
       'BWG 15-21d (g) correct', 'FCR 15-21d (g:g) ',
       'FCR 15-21d corrected (g:g) ', 'Mortality 15-21d (%)',
       'Culling 15-21dd (%)', 'Mort + Cull 15-21d (%)', 'kg/m2 15-21d',
       'EM intake 15-21d (kcal)', 'kacl intake/Kg 15-21d',
       'g dLys intake 15-21d', 'g dLys intake/kg BWG 15-21d',
       'g Ca intake 15-21d', 'g Ca intake/ kg BWG 15-21d', 'g P intake 15-21d',
       'g P intake/ kg BWG 15-21d', '$/kg BWG 15-21d', 'FI 0-21d (g)',
       'BWG 0-21d (g) ', 'BWG 0-21d (g) correct', 'FCR 0-21d (g:g) ',
       'FCR 0-21d corrected (g:g) ', 'Mortality 0 - 21d (%)',
       'Culling 0 - 21d (%)', 'Mort + Cull 0 - 21d (%)',
       'EM intake 0-21d (kcal)', 'kacl intake/Kg 0-21d', 'g dLys intake 0-21d',
       'g dLys intake/kg BWG 0-21d', 'g Ca intake 0-21d',
       'g Ca intake/ kg BWG 0-21d', 'g P intake 0-21d',
       'g P intake/ kg BWG 0-21d', '$/kg BWG 0-21d'],
      dtype='object')

In [10]:
dfE379 = E379[['ProjectID','Cage', 'Trts', 'Trt', 
               'BW21  (g)', 
               'BWG 15-21d (g) correct', 'BWG 0-21d (g) correct', 
               'FCR 15-21d corrected (g:g) ', 'FCR 0-21d corrected (g:g) '
             ]]
dfE379

,ProjectID,Cage,Trts,Trt,BW21 (g),BWG 15-21d (g) correct,BWG 0-21d (g) correct,FCR 15-21d corrected (g:g),FCR 0-21d corrected (g:g)
0,E379,14,3,UORA,910.833333,498.333333,860.081845,1.265719,1.227999
1,E379,15,1,CONTROL,864.583333,460.416667,809.983631,1.366697,1.301628
2,E379,18,2,GALLIPRO FIT,867.500000,472.916667,824.691558,1.327401,1.269341
3,E379,24,1,CONTROL,868.750000,456.666667,819.454685,1.346715,1.273756
4,E379,25,3,UORA,882.500000,468.333333,824.345238,1.355516,1.282259
5,E379,28,2,GALLIPRO FIT,870.833333,470.416667,804.486607,1.356776,1.303044
6,E379,34,3,UORA,909.090909,484.090909,839.090909,1.319437,1.272635
7,E379,35,2,GALLIPRO FIT,859.166667,465.416667,817.403274,1.333751,1.270270
8,E379,38,1,CONTROL,852.083333,458.333333,810.544643,1.362909,1.288902
9,E379,44,2,GALLIPRO FIT,899.166667,481.250000,840.980655,1.292468,1.237051
10,E379,45,3,UORA,868.333333,471.250000,819.934524,1.345889,1.294685
11,E379,48,1,CONTROL,858.750000,460.000000,806.375000,1.379529,1.300799

In [11]:
dfE379.columns

Index(['ProjectID', 'Cage', 'Trts', 'Trt', 'BW21  (g)',
       'BWG 15-21d (g) correct', 'BWG 0-21d (g) correct',
       'FCR 15-21d corrected (g:g) ', 'FCR 0-21d corrected (g:g) '],
      dtype='object')

In [12]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Cage': 'Cage',
    'Trts': 'TreatmentNumber',
    'Trt': 'Treatment',
    
    'BW21  (g)': 'BW',
    'BWG 15-21d (g) correct': 'BWGbefore',
    'BWG 0-21d (g) correct': 'BWG',
    'FCR 0-21d corrected (g:g) ': 'FCR',
    'FCR 15-21d corrected (g:g) ': 'FCRbefore'
}

dfE379.rename(columns=column_rename_map, inplace=True)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_62310/2354701425.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfE379.rename(columns=column_rename_map, inplace=True)

In [25]:
dfE379['Age'] = 21
dfE379

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_62310/3397361402.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfE379['Age'] = 21

,ProjectID,Cage,TreatmentNumber,Treatment,BW,BWGbefore,BWG,FCRbefore,FCR,Age,Cage_grouped
0,E379,14,3,UORA,910.833333,498.333333,860.081845,1.265719,1.227999,21,NaN
1,E379,15,1,CONTROL,864.583333,460.416667,809.983631,1.366697,1.301628,21,NaN
2,E379,18,2,GALLIPRO FIT,867.500000,472.916667,824.691558,1.327401,1.269341,21,NaN
3,E379,24,1,CONTROL,868.750000,456.666667,819.454685,1.346715,1.273756,21,NaN
4,E379,25,3,UORA,882.500000,468.333333,824.345238,1.355516,1.282259,21,NaN
5,E379,28,2,GALLIPRO FIT,870.833333,470.416667,804.486607,1.356776,1.303044,21,NaN
6,E379,34,3,UORA,909.090909,484.090909,839.090909,1.319437,1.272635,21,NaN
7,E379,35,2,GALLIPRO FIT,859.166667,465.416667,817.403274,1.333751,1.270270,21,NaN
8,E379,38,1,CONTROL,852.083333,458.333333,810.544643,1.362909,1.288902,21,NaN
9,E379,44,2,GALLIPRO FIT,899.166667,481.250000,840.980655,1.292468,1.237051,21,NaN
10,E379,45,3,UORA,868.333333,471.250000,819.934524,1.345889,1.294685,21,NaN
11,E379,48,1,CONTROL,858.750000,460.000000,806.375000,1.379529,1.300799,21,NaN

In [32]:
dfE379['Cage'] = dfE379['Cage'].astype(str).str.strip()

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_62310/524696408.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfE379['Cage'] = dfE379['Cage'].astype(str).str.strip()

In [33]:
cage_mapping = {
    '15': '1524',
    '24': '1524',
    '18': '1828',
    '28': '1828',
    '35': '3544',
    '44': '3544',
    '14': '1425',
    '25': '1425',
    '38': '3848',
    '48': '3848',
    '34': '3445',
    '45': '3445'
}

# Creamos la columna agrupada
dfE379['Cage_grouped'] = dfE379['Cage'].map(cage_mapping)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_62310/3013591645.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfE379['Cage_grouped'] = dfE379['Cage'].map(cage_mapping)

In [34]:
dfE379

,ProjectID,Cage,TreatmentNumber,Treatment,BW,BWGbefore,BWG,FCRbefore,FCR,Age,Cage_grouped
0,E379,14,3,UORA,910.833333,498.333333,860.081845,1.265719,1.227999,21,1425
1,E379,15,1,CONTROL,864.583333,460.416667,809.983631,1.366697,1.301628,21,1524
2,E379,18,2,GALLIPRO FIT,867.500000,472.916667,824.691558,1.327401,1.269341,21,1828
3,E379,24,1,CONTROL,868.750000,456.666667,819.454685,1.346715,1.273756,21,1524
4,E379,25,3,UORA,882.500000,468.333333,824.345238,1.355516,1.282259,21,1425
5,E379,28,2,GALLIPRO FIT,870.833333,470.416667,804.486607,1.356776,1.303044,21,1828
6,E379,34,3,UORA,909.090909,484.090909,839.090909,1.319437,1.272635,21,3445
7,E379,35,2,GALLIPRO FIT,859.166667,465.416667,817.403274,1.333751,1.270270,21,3544
8,E379,38,1,CONTROL,852.083333,458.333333,810.544643,1.362909,1.288902,21,3848
9,E379,44,2,GALLIPRO FIT,899.166667,481.250000,840.980655,1.292468,1.237051,21,3544
10,E379,45,3,UORA,868.333333,471.250000,819.934524,1.345889,1.294685,21,3445
11,E379,48,1,CONTROL,858.750000,460.000000,806.375000,1.379529,1.300799,21,3848

In [35]:
# Columnas numéricas para mean
numeric_columns = ['BW', 'BWGbefore', 'BWG', 'FCRbefore', 'FCR']

# Columnas categóricas
categorical_columns = ['ProjectID', 'TreatmentNumber', 'Treatment', 'Age']

In [36]:
def get_mode(series):
    return series.mode()[0] if not series.mode().empty else series.iloc[0]

# Agrupamos y calculamos
result = dfE379.groupby('Cage_grouped').agg({
    **{col: 'mean' for col in numeric_columns},  # Mean para numéricas
    **{col: get_mode for col in categorical_columns}  # Moda para categóricas
}).reset_index()

In [39]:
result

,Pen,BW,BWGbefore,BWG,FCRbefore,FCR,ProjectID,TreatmentNumber,Treatment,Age
0,1425,896.666667,483.333333,842.213542,1.310618,1.255129,E379,3,UORA,21
1,1524,866.666667,458.541667,814.719158,1.356706,1.287692,E379,1,CONTROL,21
2,1828,869.166667,471.666667,814.589083,1.342088,1.286192,E379,2,GALLIPRO FIT,21
3,3445,888.712121,477.670455,829.512716,1.332663,1.283660,E379,3,UORA,21
4,3544,879.166667,473.333333,829.191964,1.313109,1.253661,E379,2,GALLIPRO FIT,21
5,3848,855.416667,459.166667,808.459821,1.371219,1.294850,E379,1,CONTROL,21

In [38]:
column_rename_map = {
    'Cage_grouped': 'Pen'
}

result.rename(columns=column_rename_map, inplace=True)

In [40]:
result.to_csv('/Users/sbedoya/Library/CloudStorage/GoogleDrive-sebastian.bedoya@premexcorp.com/.shortcut-targets-by-id/14y2xKGwNoxbZw62IuQ4kAOneGUwlRbqR/SIWA_shared/ETL/Broiler/performance_longformat/LongFormatE379.csv', index=False)

# 378

In [3]:
E378 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Performance_ExpFarm/E-378 Energia Carbohidrasas 24_01-2025.xlsx", "Data to stat")
E378

,House,Line,Block 1,Pen,Operator,Trts,Trts.,Carb,Block 2,"Formulated EM Pst, Kcal/kg",...,"BWG 0-42d correct, g","FCR 0-42d, g:g","FCR 0-42d corrected, g:g","Mortality 0 - 42d, %","Culling 0 - 42d, %","Mort + Cull 0 - 42d, %","EM intake 0-42d, kcal",kcal intake/Kg 0-42d,g dLys intake 0-42d,g dLys intake/kg BWG 0-42d
0,1,A,1A,1,D,1,A,A,1,3020.0,...,3110.155000,1.412459,1.412459,4.000000,0.000000,4.000000,13640.303000,4385.730936,54.362255,17.478954
1,1,A,1A,2,D,5,Danisc X,Xilanasa,1,2900.0,...,3106.960000,1.462652,1.462652,0.000000,0.000000,0.000000,13566.240000,4366.403172,56.230920,18.098373
2,1,A,1A,3,D,4,Natugrain,Xilanasa,1,2900.0,...,2987.840000,1.458177,1.458177,0.000000,0.000000,0.000000,13005.432000,4352.787298,53.913480,18.044300
3,1,A,1A,4,D,2,B,B,1,2900.0,...,3136.523168,1.501025,1.455861,8.166667,0.000000,8.166667,13633.171739,4481.429312,56.495239,18.570838
4,1,A,1A,5,D,6,Axta XAP,Blend,1,2900.0,...,3099.200000,1.446696,1.446696,0.000000,0.000000,0.000000,13383.024000,4318.218895,55.487160,17.903704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2,B,2B,36,D,3,Robavio,Blend,13,2900.0,...,3153.834928,1.464824,1.452981,4.000000,4.166667,8.166667,13679.645783,4372.820078,56.702973,18.125608
76,2,B,2B,37,D,4,Natugrain,Xilanasa,7,2900.0,...,3096.720000,1.458963,1.458963,0.000000,0.000000,0.000000,13488.096000,4355.607223,55.900920,18.051655
77,2,B,2B,38,D,6,Axta XAP,Blend,7,2900.0,...,3093.680000,1.459104,1.459104,0.000000,0.000000,0.000000,13474.104000,4355.364485,55.861680,18.056709
78,2,B,2B,39,D,5,Danisc X,Xilanasa,7,2900.0,...,3078.179455,1.508018,1.462462,8.166667,0.000000,8.166667,13438.013043,4501.560384,55.706918,18.661096
79,2,B,2B,40,D,0,NaN,NaN,0,NaN,...,-659.600000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN

In [4]:
print(list(E378.columns))
E378["ProjectID"] = 'E378'
E378.head()

['House', 'Line', 'Block 1', 'Pen', 'Operator', 'Trts', 'Trts.', 'Carb', 'Block 2', 'Formulated EM Pst, Kcal/kg', 'Formulated EM St, kcal/kg', 'Formulated EM Gr, kcal/kg', 'Formulated EM Fn, kcal/kg', 'Formulated dLys Pst, %', 'Formulated dLys St, %', 'Formulated dLys Gr, %', 'Formulated dLys Fn, %', 'Analyzed Ca Pst, %', 'Analyzed Ca St, %', 'Analyzed Ca Gr, %', 'Analyzed Ca Fn, %', 'analyzed P Pst, %', 'analyzed P St, %', 'analyzed P Gr, %', 'analyzed P Fn, %', 'Pst diet cost, $/Kg', 'St diet cost, $/Kg', 'Gr diet cost, $/Kg', 'Fn diet cost, $/Kg', 'BW1, g', 'BW 7d, g', 'FI 0-7d, g', 'cFI 0-7d, g', 'WC 0-7d, g', 'BWG 0-7d, g', 'BWG 0-7d, g correct', 'FCR 0-7d, g:g', 'FCR 0-7d corrected, g:g', 'Mortality 0-7d, %', 'Culling 0-7d, %', 'Mort + Cull 0-7d, %', 'kg/m2 0-7d', 'EM intake 0-7d, kcal', 'kcal intake/Kg 0-7d', 'g dLys intake 0-7d', 'g dLys intake/kg BWG 0-7d', 'g Ca intake 0-7d', 'g Ca intake/ kg BWG 0-7d', 'g P intake 0-7d', 'g P intake/ kg BWG 0-7d', '$/kg BWG 0-7d', 'BW 14d, g', 'FI 8-14d, g', 'cFI 8-14d, g ', 'WC 8-14d, g', 'BWG 8-14d, g', 'BWG 8-14d correct, g', 'FCR 8-14d, g:g', 'FCR 8-14d corrected, g:g', 'Mortality 8-14d, %', 'Culling 8-14d, %', 'Mort + Cull 8-14d, %', 'kg/m2 8-14d', 'EM intake 8-14d, kcal', 'kcal intake/Kg 8-14d', 'g dLys intake 8-14d', 'g dLys intake/kg BWG 8-14d', 'g Ca intake 8-14d', 'g Ca intake/ kg BWG 8-14d', 'g P intake 8-14d', 'g P intake/ kg BWG 8-14d', '$/kg BWG 8-14d', 'FI 0-14d, g', 'cFI 0-14d, g', 'WC 0-14d, g', 'BWG 0-14d, g', 'BWG 0-14d correct, g', 'FCR 0-14d, g:g', 'FCR 0-14d corrected, g:g', 'Mortality 0-14d, %', 'Culling 0-14d, %', 'Mort + Cull 0-14d, %', 'BW 21d, g', 'FI 15-21d, g', 'cFI 15-21d, g ', 'WC 15-21d, g', 'BWG 15-21d, g', 'BWG 15-21d correct, g', 'FCR 15-21d, g:g', 'FCR 15-21d corrected, g:g', 'Mortality 15-21d, %', 'Culling 15-21d, %', 'Mort + Cull 15-21d, %', 'kg/m2 15-21d', 'EM intake 15-21dl kcal', 'kcal intake/Kg 15-21d', 'g dLys intake 15-21d', 'g dLys intake/kg BWG 15-21d', 'g Ca intake 15-21d', 'g Ca intake/ kg BWG 15-21d', 'g P intake 15-21d', 'g P intake/ kg BWG 15-21d', '$/kg BWG 15-21d', 'FI 8-21d, g', 'cFI 8-21d, g', 'WC 8-21d, g', 'BWG 8-21d, g', 'BWG 8-21d correct, g', 'FCR 8-21d, g:g', 'FCR 8-21d corrected, g:g', 'Mortality 8 - 21d, %', 'Culling 8 - 21d, %', 'Mort + Cull 8 - 21d, %', 'EM intake 8-21d, kcal', 'kcal intake/Kg 8-21d', 'g dLys intake 8-21d', 'g dLys intake/kg BWG 8-21d', 'FI 0-21d, g', 'cFI 0-21d, g', 'WC 0-21d, g', 'BWG 0-21d, g', 'BWG 0-21d correct, g', 'FCR 0-21d, g:g', 'FCR 0-21d corrected, g:g', 'Mortality 0 - 21d, %', 'Culling 0 - 21d, %', 'Mort + Cull 0 - 21d, %', 'EM intake 0-21d, kcal', 'kcal intake/Kg 0-21d', 'g dLys intake 0-21d', 'g dLys intake/kg BWG 0-21d', 'g Ca intake 0-21d', 'g Ca intake/ kg BWG 0-21d', 'g P intake 0-21d', 'g P intake/ kg BWG 0-21d', '$/kg BWG 0-21d', 'BW 28d, g', 'FI 22-28d, g', 'cFI 22-28d, g', 'WC 22-28d, g', 'BWG 22-28d, g', 'BWG 22-28d correct, g', 'FCR 22-28d, g:g', 'FCR 22-28d corrected, g:g', 'Mortality 22 - 28d, %', 'Culling 22 - 28d, %', 'Mort + Cull 22 - 28d, %', 'kg/m2 22-28d', 'EM intake 22-28d, kcal', 'kcal intake/Kg 22-28d', 'g dLys intake 22-28d', 'g dLys intake/kg BWG 22-28d', 'g Ca intake 22-28d', 'g Ca intake/ kg BWG 22-28d', 'g P intake 22-28d', 'g P intake/ kg BWG 22-28d', '$/kg BWG 22-28d', 'FI 0-28d, g', 'cFI 0-28d, g', 'WC 0-28d, g', 'BWG 0-28d, g', 'BWG 0-28d correct, g', 'FCR 0-28d, g:g', 'FCR 0-28d corrected, g:g', 'Mortality 0-28d, %', 'Culling 0-28d, %', 'Mort + Cull 0 - 28d, %', 'BW 35d, g', 'FI 29-35d, g', 'cFI 29-35d, g', 'WC 29-35d, g', 'BWG 29-35d, g', 'BWG 29-35d correct, g', 'FCR 29-35d, g:g', 'FCR 29-35d corrected, g:g', 'Mortality 29 - 35d, %', 'Culling 29 - 35d, %', 'Mort + Cull 29 - 35d, %', 'kg/m2 29-35d', 'EM intake 29-35d (kcal)', 'kcal intake/Kg 29-35d', 'g dLys intake 29-35d', 'g dLys intake/kg BWG 29-35d', 'g Ca intake 29-35d', 'g Ca intake/ kg BWG 29-35d', 'g P intake 29-35d', 'g P intake/ kg BWG 29-35d', '$/kg BWG 29-35d', 'FI 0-35d, g', 'cFI 0-35d, g', 'WC 0-35d, g', 'BWG 0-35d, g', 'BWG 0-35d correct, g', 'FCR 0-35d, g:g', 'FCR 0-35d corrected, g:g', 'Mortality 0-35d, %', 'Culling 0-35d, %', 'Mort + Cull 0 - 35d, %', 'BW 42d, g', 'FI 36-42d, g', 'cFI 36-42d, g', 'WC 36-42d, g', 'BWG 36-42d, g', 'BWG 36-42d, g correct', 'FCR 36-42d, g:g', 'FCR 36-42d corrected, g:g', 'Mortality 36 - 42d, %', 'Culling 36 - 42d, %', 'Mort + Cull 36 - 42d, %', 'kg/m2 36-42d', 'EM intake 36-42d, kcal', 'kcal intake/Kg 36-42d', 'g dLys intake 36-42d', 'g dLys intake/kg BWG 36-42d', 'g Ca intake 36-42d', 'g Ca intake/ kg BWG 36-42d', 'g P intake 36-42d', 'g P intake/ kg BWG 36-42d', '$/kg BWG 36-42d', 'FI 22-42, g', 'cFI 22-42, g', 'WC 22-42, g', 'BWG 22-42d, g', 'BWG 22-42d corrected, g', 'FCR 22-42d, g:g', 'FCR 22-42d corrected, g:g', 'Mortality 22 - 42d, %', 'Culling 22 - 42d, %', 'Mort + Cull 22 - 42d, %', 'EM intake 22-42d, kcal', 'kcal intake/Kg 22-42d', 'g dLys intake 22-42d', 'g dLys intake/kg BWG 22-42d', 'g Ca intake 22-42d', 'g Ca intake/ kg BWG 22-42d', 'g P intake 22-42d', 'g P intake/ kg BWG 22-42d', '$/kg BWG 22-42d', 'FI 0-42d, g', 'cFI 0-42d, g', 'WC 0-42d, g', 'BWG 0-42d, g', 'BWG 0-42d correct, g', 'FCR 0-42d, g:g', 'FCR 0-42d corrected, g:g', 'Mortality 0 - 42d, %', 'Culling 0 - 42d, %', 'Mort + Cull 0 - 42d, %', 'EM intake 0-42d, kcal', 'kcal intake/Kg 0-42d', 'g dLys intake 0-42d', 'g dLys intake/kg BWG 0-42d']

,House,Line,Block 1,Pen,Operator,Trts,Trts.,Carb,Block 2,"Formulated EM Pst, Kcal/kg",...,"FCR 0-42d, g:g","FCR 0-42d corrected, g:g","Mortality 0 - 42d, %","Culling 0 - 42d, %","Mort + Cull 0 - 42d, %","EM intake 0-42d, kcal",kcal intake/Kg 0-42d,g dLys intake 0-42d,g dLys intake/kg BWG 0-42d,ProjectID
0,1,A,1A,1,D,1,A,A,1,3020.0,...,1.412459,1.412459,4.000000,0.0,4.000000,13640.303000,4385.730936,54.362255,17.478954,E378
1,1,A,1A,2,D,5,Danisc X,Xilanasa,1,2900.0,...,1.462652,1.462652,0.000000,0.0,0.000000,13566.240000,4366.403172,56.230920,18.098373,E378
2,1,A,1A,3,D,4,Natugrain,Xilanasa,1,2900.0,...,1.458177,1.458177,0.000000,0.0,0.000000,13005.432000,4352.787298,53.913480,18.044300,E378
3,1,A,1A,4,D,2,B,B,1,2900.0,...,1.501025,1.455861,8.166667,0.0,8.166667,13633.171739,4481.429312,56.495239,18.570838,E378
4,1,A,1A,5,D,6,Axta XAP,Blend,1,2900.0,...,1.446696,1.446696,0.000000,0.0,0.000000,13383.024000,4318.218895,55.487160,17.903704,E378

In [5]:
E378[[i for i in E378.columns if "7" in i]].columns

Index(['BW 7d, g', 'FI 0-7d, g', 'cFI 0-7d, g', 'WC 0-7d, g', 'BWG 0-7d, g',
       'BWG 0-7d, g correct', 'FCR 0-7d, g:g', 'FCR 0-7d corrected, g:g',
       'Mortality 0-7d, %', 'Culling 0-7d, %', 'Mort + Cull 0-7d, %',
       'kg/m2 0-7d', 'EM intake 0-7d, kcal', 'kcal intake/Kg 0-7d',
       'g dLys intake 0-7d', 'g dLys intake/kg BWG 0-7d', 'g Ca intake 0-7d',
       'g Ca intake/ kg BWG 0-7d', 'g P intake 0-7d',
       'g P intake/ kg BWG 0-7d', '$/kg BWG 0-7d'],
      dtype='object')

In [16]:
dfE378 = E378[['ProjectID','House', 'Pen', 'Trts', 'Trts.', 'Carb', 
               'BW 42d, g', 
               'BWG 36-42d, g correct', 'BWG 0-42d correct, g', 
               'FCR 0-42d corrected, g:g', 'FCR 36-42d corrected, g:g'
             ]]
dfE378.head()

,ProjectID,House,Pen,Trts,Trts.,Carb,"BW 42d, g","BWG 36-42d, g correct","BWG 0-42d correct, g","FCR 0-42d corrected, g:g","FCR 36-42d corrected, g:g"
0,E378,1,1,1,A,A,3156.250000,732.083333,3110.155000,1.412459,1.626636
1,E378,1,2,5,Danisc X,Xilanasa,3154.000000,732.800000,3106.960000,1.462652,1.695415
2,E378,1,3,4,Natugrain,Xilanasa,3034.400000,669.200000,2987.840000,1.458177,1.683204
3,E378,1,4,2,B,B,3200.434783,730.314050,3136.523168,1.455861,1.711027
4,E378,1,5,6,Axta XAP,Blend,3146.800000,712.400000,3099.200000,1.446696,1.685570

In [17]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Trts': 'TreatmentNumber',
    'Trts.': 'Treatment',
    
    'BW 42d, g': 'BW',
    'BWG 36-42d, g correct': 'BWGbefore',
    'BWG 0-42d correct, g': 'BWG',
    'FCR 0-42d corrected, g:g': 'FCR',
    'FCR 36-42d corrected, g:g': 'FCRbefore'
}

dfE378.rename(columns=column_rename_map, inplace=True)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_20960/2833963056.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfE378.rename(columns=column_rename_map, inplace=True)

In [18]:
dfE378['Age'] = 42

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_20960/2185693237.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfE378['Age'] = 42

In [19]:
dfE378.head(2)

,ProjectID,House,Pen,TreatmentNumber,Treatment,Carb,BW,BWGbefore,BWG,FCR,FCRbefore,Age
0,E378,1,1,1,A,A,3156.25,732.083333,3110.155,1.412459,1.626636,42
1,E378,1,2,5,Danisc X,Xilanasa,3154.00,732.800000,3106.960,1.462652,1.695415,42

In [20]:
dfE378.to_csv('/Users/sbedoya/Library/CloudStorage/GoogleDrive-sebastian.bedoya@premexcorp.com/.shortcut-targets-by-id/14y2xKGwNoxbZw62IuQ4kAOneGUwlRbqR/SIWA_shared/ETL/Broiler/performance_longformat/LongFormatE378.csv', index=False)

In [15]:
E378[[i for i in E378.columns if "42" in i]].columns

Index(['BW 42d, g', 'FI 36-42d, g', 'cFI 36-42d, g', 'WC 36-42d, g',
       'BWG 36-42d, g', 'BWG 36-42d, g correct', 'FCR 36-42d, g:g',
       'FCR 36-42d corrected, g:g', 'Mortality 36 - 42d, %',
       'Culling 36 - 42d, %', 'Mort + Cull 36 - 42d, %', 'kg/m2 36-42d',
       'EM intake 36-42d, kcal', 'kcal intake/Kg 36-42d',
       'g dLys intake 36-42d', 'g dLys intake/kg BWG 36-42d',
       'g Ca intake 36-42d', 'g Ca intake/ kg BWG 36-42d', 'g P intake 36-42d',
       'g P intake/ kg BWG 36-42d', '$/kg BWG 36-42d', 'FI 22-42, g',
       'cFI 22-42, g', 'WC 22-42, g', 'BWG 22-42d, g',
       'BWG 22-42d corrected, g', 'FCR 22-42d, g:g',
       'FCR 22-42d corrected, g:g', 'Mortality 22 - 42d, %',
       'Culling 22 - 42d, %', 'Mort + Cull 22 - 42d, %',
       'EM intake 22-42d, kcal', 'kcal intake/Kg 22-42d',
       'g dLys intake 22-42d', 'g dLys intake/kg BWG 22-42d',
       'g Ca intake 22-42d', 'g Ca intake/ kg BWG 22-42d', 'g P intake 22-42d',
       'g P intake/ kg BWG 22-42d', '$/kg BWG 22-42d', 'FI 0-42d, g',
       'cFI 0-42d, g', 'WC 0-42d, g', 'BWG 0-42d, g', 'BWG 0-42d correct, g',
       'FCR 0-42d, g:g', 'FCR 0-42d corrected, g:g', 'Mortality 0 - 42d, %',
       'Culling 0 - 42d, %', 'Mort + Cull 0 - 42d, %', 'EM intake 0-42d, kcal',
       'kcal intake/Kg 0-42d', 'g dLys intake 0-42d',
       'g dLys intake/kg BWG 0-42d'],
      dtype='object')

In [18]:
dfE378 = E378[['Trts.',
               'BW 7d, g', 'BWG 0-7d, g correct', 'cFI 0-7d, g', 'FCR 0-7d corrected, g:g', 'Mort + Cull 0-7d, %',

               'BW 14d, g', 'BWG 0-14d correct, g', 'cFI 0-14d, g', 'FCR 0-14d corrected, g:g', 'Mort + Cull 0-14d, %',

               'BW 21d, g', 'BWG 0-21d correct, g','cFI 0-21d, g', 'FCR 0-21d corrected, g:g', 'Mort + Cull 0 - 21d, %',

               'BW 28d, g', 'BWG 0-28d correct, g', 'cFI 0-28d, g', 'FCR 0-28d corrected, g:g', 'Mort + Cull 0 - 28d, %',

               'BW 35d, g', 'BWG 0-35d correct, g', 'cFI 0-35d, g', 'FCR 0-35d corrected, g:g', 'Mort + Cull 0 - 35d, %', 

               
               'BW 42d, g', 'BWG 0-42d correct, g', 'cFI 0-42d, g', 'FCR 0-42d corrected, g:g', 'Mort + Cull 0 - 42d, %'
             ]]
dfE378.head()

,Trts.,"BW 7d, g","BWG 0-7d, g correct","cFI 0-7d, g","FCR 0-7d corrected, g:g","Mort + Cull 0-7d, %","BW 14d, g","BWG 0-14d correct, g","cFI 0-14d, g","FCR 0-14d corrected, g:g",...,"BW 35d, g","BWG 0-35d correct, g","cFI 0-35d, g","FCR 0-35d corrected, g:g","Mort + Cull 0 - 35d, %","BW 42d, g","BWG 0-42d correct, g","cFI 0-42d, g","FCR 0-42d corrected, g:g","Mort + Cull 0 - 42d, %"
0,A,154.0,108.28,118.8,1.097156,4.0,415.000000,368.905000,443.383333,1.201890,...,2424.166667,2378.071667,3202.133333,1.346525,4.0,3156.250000,3110.155000,4392.966667,1.412459,4.000000
1,Danisc X,154.4,107.36,126.8,1.181073,0.0,424.400000,377.360000,463.200000,1.227475,...,2421.200000,2374.160000,3302.000000,1.390808,0.0,3154.000000,3106.960000,4544.400000,1.462652,0.000000
2,Natugrain,154.4,107.84,114.8,1.064540,0.0,416.400000,369.840000,443.600000,1.199438,...,2365.200000,2318.640000,3230.400000,1.393231,0.0,3034.400000,2987.840000,4356.800000,1.458177,0.000000
3,B,156.0,110.88,120.0,1.082251,0.0,435.416667,388.292451,457.470817,1.195405,...,2453.333333,2406.209118,3307.470817,1.377339,4.0,3200.434783,3136.523168,4557.057594,1.455861,8.166667
4,Axta XAP,164.6,117.00,127.2,1.087179,0.0,446.000000,398.400000,472.800000,1.186747,...,2434.400000,2386.800000,3282.800000,1.375398,0.0,3146.800000,3099.200000,4483.600000,1.446696,0.000000

In [19]:
dfE378['Trts.'].unique()

array(['A', 'Danisc X', 'Natugrain', 'B', 'Axta XAP', 'Robavio', nan],
      dtype=object)

In [28]:
dfE378_filter = dfE378[dfE378['Trts.'].isin(['Danisc X', 'Natugrain', 'B', 'Axta XAP', 'Robavio'])]

In [42]:
dfE378_filter.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/E378/performance_allages.csv', index=False)

In [22]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import numpy as np

In [29]:
numeric_cols = [col for col in dfE378_filter.columns if col != 'Trts.' and np.issubdtype(dfE378_filter[col].dtype, np.number)]
numeric_cols

['BW 7d, g',
 'BWG 0-7d, g correct',
 'cFI 0-7d, g',
 'FCR 0-7d corrected, g:g',
 'Mort + Cull 0-7d, %',
 'BW 14d, g',
 'BWG 0-14d correct, g',
 'cFI 0-14d, g',
 'FCR 0-14d corrected, g:g',
 'Mort + Cull 0-14d, %',
 'BW 21d, g',
 'BWG 0-21d correct, g',
 'cFI 0-21d, g',
 'FCR 0-21d corrected, g:g',
 'Mort + Cull 0 - 21d, %',
 'BW 28d, g',
 'BWG 0-28d correct, g',
 'cFI 0-28d, g',
 'FCR 0-28d corrected, g:g',
 'Mort + Cull 0 - 28d, %',
 'BW 35d, g',
 'BWG 0-35d correct, g',
 'cFI 0-35d, g',
 'FCR 0-35d corrected, g:g',
 'Mort + Cull 0 - 35d, %',
 'BW 42d, g',
 'BWG 0-42d correct, g',
 'cFI 0-42d, g',
 'FCR 0-42d corrected, g:g',
 'Mort + Cull 0 - 42d, %']

# 361

In [2]:
E361 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Fractal_26_10_2023 CC.xlsx", "Performance Data")
E361.head()

,House,Line,Pen,Blind Trts,Trts.,# Ini birds 1d,"Group BWh, g","BW placement, g",Mortality 0-6d,"Mortality weight 0-6d, g",...,"WC 36 - 42d, g","Group BWG 36-42d, g","BWG 36-42d, g","Group BWG 36-42d corrected, g","BWG 36-42d corrected, g","FCR 36-42d, g:g","FCR 36-42d corrected, g:g","Mortality 36-42d, %","Culling 36-42d, %","Mort + Cull 36-42d, %"
0,1,A,1,4.0,ALURA_FRACTAL_454,32,1415,44.21875,0,0,...,0.0,22465,748.833333,22465,748.833333,1.825951,1.825951,0.0,0.0,0.0
1,1,A,2,10.0,BIOLUTION5_AF227_EO2,32,1410,44.06250,0,0,...,0.0,20220,631.875000,20220,631.875000,2.041048,2.041048,0.0,0.0,0.0
2,1,A,3,8.0,BIOLUTION3_AF454_EO3,32,1420,44.37500,0,0,...,0.0,23835,794.500000,23835,794.500000,1.749948,1.749948,0.0,0.0,0.0
3,1,A,4,11.0,BIOLUTION6_AF227_EO3,32,1400,43.75000,0,0,...,0.0,21680,774.285714,21680,774.285714,1.785055,1.785055,0.0,0.0,0.0
4,1,A,5,5.0,ALURA_FRACTAL_227,32,1395,43.59375,0,0,...,0.0,22860,737.419355,22860,737.419355,1.867454,1.867454,0.0,0.0,0.0

In [3]:
print(list(E361.columns))
E361["ProjectID"] = 'E361'
E361.head()

['House', 'Line', 'Pen', 'Blind Trts ', 'Trts.', '# Ini birds 1d', 'Group BWh, g', 'BW placement, g', 'Mortality 0-6d', 'Mortality weight 0-6d, g', 'Culling 0-6d', 'Culling weight 0-6d, g', 'Total Mort. + cull 0-6d, g', 'Mortality 7d', 'Mortality weight 7d, g', 'Culling 7d', 'Culling weight 7d, g', 'Total Weight Mort. + cull 7d, g', 'Sampling 7d', 'Sampling weight 7d, g', 'Offered feed 1d, g', 'Offered water 1d, g', 'Leftover feed 7d, g', 'Leftover water 7d, g', 'Container weight, g', 'Container + birds weight, g', '# Fnl birds 7d', 'Group BW7, g', 'BW7, g', 'Group FI 0-7d, g', 'FI 0-7d, g', 'Group WC 0-7d, g', 'WC 0-7d, g', 'Group BWG 0-7d, g', 'BWG 0-7d, g', 'Group BWG 0-7d corrected, g', 'BWG 0-7d corrected, g', 'FCR 0-7d, g:g', 'FCR 0-7d corrected, g:g', 'Mortality 0-7d, %', 'Culling 0-7d, %', 'Mort + Cull 0-7d, %', 'Wk2   (8-14d)', '# Ini birds 8d', 'Ini GBW8, g', 'Offered feed 8d, g', 'Feed adicion 8-14, g', 'Leftover feed 14d, g', 'Offered Water 8d, g', 'Leftover water 14d, g', 'Mortality 8-13d', 'Mortality weight 8-13d, g', 'Culling 8-13d', 'Culling weight 8-13d, g', 'Total Mort. + cull 8-13d, g', 'Mortality 14d', 'Mortality weight 14d, g', 'Culling 14d', 'Culling weight 14d, g', 'Mort + Cull 14d (g)', 'Sampling 14d', 'Sampling weight 14d, g', 'Container weight, g.1', 'Container + birds weight, g.1', 'Fnl birds 14d', 'Group BW14, g', 'BW14, g', 'Group FI 8-14d, g', 'FI 8-14d, g', 'Group WC 8-14d, g', 'WC 8-14d, g', 'Group BWG 8-14d, g', 'BWG 8-14d, g', 'Group BWG 8-14d corrected, g', 'BWG 8-14d  corrected, g', 'FCR 8-14d, g:g', 'FCR 8-14d corrected, g:g', 'Mortality 8-14d, %', 'Culling 8-14d, %', 'Mort + Cull 8-14d, %', 'Wk3  (15-21d)', '# Ini birds 15d', 'Ini GBW 15d, g', 'Offered feed 15-21, g', 'Offered water 15-21, g', 'Feed Adition 15-21d, g', 'Leftover feed 15-21d, g', 'Leftover water 15-21, g', 'Mortality 15-20d', 'Mortality weight 15-20d, g', 'Culling 15-20d', 'Culling weight 15-20d, g', 'Total Mort. + cull 15-20d, g', 'Mortality 21d', 'Mortality weight 21d, g', 'Culling 21d', 'Culling weight 21d, g', 'Total Mort + Cull 21d, g', 'Sampling 21d', 'Sampling weight 21d, g', 'Container weight, g.2', 'Container + birds weight, g.2', '# Fnl birds 21d', 'Group BW 21d, g', 'BW 21d, g', 'Group FI 15-21d, g', 'FI 15-21d, g', 'Group WC 15-21d, g', 'WC 15-21d, g', 'Group BWG 15-21d, g', 'BWG 15-21d, g', 'Group BWG 15-21d  corrected, g', 'BWG 15-21d  corrected, g', 'FCR 15-21d, g:g', 'FCR 15-21d corrected, g:g', 'Mortality 15-21d, %', 'Culling 15-21d, %', 'Mort + Cull 15-21d, %', 'Wk4  (22-28d)', '#Ini birds 22d', 'Ini GBW 22d, g', 'Offered feed 22-28d, g', 'Feed adition 22-28d, g', 'Leftover feed 22-28d, g', 'Offered water 22 -28d, g', 'Leftover water 22-28d, g', 'Mortality 22-27d', 'Mortality weight 22-27d, g', 'Culling 22-27d', 'Culling weight 22-27d, g', 'Total Mort. + Cull 22-27d, g', 'Mortality 28d', 'Mortality weight 28d, g', 'Culling 28d', 'Culling weight 28d, g', 'Total Mort + Cull 28d, g', 'Sampling 22d', 'Sampling weight 22d, g', 'Container weight, g.3', 'Container + birds weight, g.3', '# Fnl birds 28d', 'Group BW28d, g', 'BW28d, g', 'Group FI 22-28d, g', 'FI 22-28d, g', 'Group WC 22-28d, g', 'WC 22-28d, g', 'Group BWG 22-28d, g', 'BWG 22-28d, g', 'Group BWG 22-28d corrected, g', 'BWG 22-28d corrected, g', 'FCR 22-28d, g:g', 'FCR22-28 corrected, g:g', 'Mortality 22-28d, %', 'Culling 22-28d, %', 'Mort + Cull 22-28d, %', 'Wk5   (29-35d)', '#Ini birds 29d', 'Ini GBW 29d, g', 'Offered feed 29-35d, g', 'Adition 1 feed 29-35d, g', 'Adition 2 feed 29-35d, g', 'Adition 3 feed 29-35d, g', 'Leftover feed 29-35d, g', 'Offered water 29-35d, g', 'Leftover water 29-35d, g', 'Mortality 29-34d', 'Mortality weight 29-34d, g', 'Culling 29-34d', 'Culling weight 29-34d, g', 'Total Mort. + cull 29-34d, g', 'Mortality 35d', 'Mortality weight 35d, g', 'Culling 35d', 'Culling weight 35d', 'Total Mort + Cull 35d, g', 'Sampling 29d', 'Sampling weight 29d, g', 'Container weight (g)', 'Container + birds weight (g)', '# Fnl birds 35d', 'Group BW 35d, g', 'BW35d, g', 'Group FI 29-35d, g', 'FI 29-35d, g', 'Group WC 29-35d, g', 'WC 29 - 35d, g', 'Group BWG 29-35d, g', 'BWG 29-35d, g', 'Group BWG 29-35d corrected, g', 'BWG 29-35d corrected, g', 'FCR 29-35d, g:g', 'FCR 29-35d corrected, g:g', 'Mortality 29-35d, %', 'Culling 29-35d, %', 'Mort + Cull 29-35d, %', 'Wk5   (36-42d)', '# Ini Birds 36d', 'Ini GBW 36d, g', 'Offered feed 36-42d, g', 'Adition feed 36-42d, g', 'Leftover feed 36-42d, g', 'Offered water 26-42d, g', 'Leftover water 36 - 42d, g', 'Mortality 36-41d', 'Mortality weight 36-41d, g', 'Culling 36-41d', 'Culling weight 36-41d, g', 'Total Mort. + cull 36-41d, g', 'Mortality 42d', 'Mortality weight 42d, g', 'Culling 42d', 'Culling weight 42d, g', 'Total Mort + Cull 42d, g', 'Sampling 42d', 'Sampling weight 42d, g', 'Container weight, g.4', 'Container + birds weight, g.4', '# Fnl birds 42d', 'Unnamed: 219', 'Group BW 42d, g', 'BW 42d, g', 'Group FI 36-42d, g', 'FI 36-42d, g', 'Group WC 36-42d, g', 'WC 36 - 42d, g', 'Group BWG 36-42d, g', 'BWG 36-42d, g', 'Group BWG 36-42d corrected, g', 'BWG 36-42d corrected, g', 'FCR 36-42d, g:g', 'FCR 36-42d corrected, g:g', 'Mortality 36-42d, %', 'Culling 36-42d, %', 'Mort + Cull 36-42d, %']

,House,Line,Pen,Blind Trts,Trts.,# Ini birds 1d,"Group BWh, g","BW placement, g",Mortality 0-6d,"Mortality weight 0-6d, g",...,"Group BWG 36-42d, g","BWG 36-42d, g","Group BWG 36-42d corrected, g","BWG 36-42d corrected, g","FCR 36-42d, g:g","FCR 36-42d corrected, g:g","Mortality 36-42d, %","Culling 36-42d, %","Mort + Cull 36-42d, %",ProjectID
0,1,A,1,4.0,ALURA_FRACTAL_454,32,1415,44.21875,0,0,...,22465,748.833333,22465,748.833333,1.825951,1.825951,0.0,0.0,0.0,E361
1,1,A,2,10.0,BIOLUTION5_AF227_EO2,32,1410,44.06250,0,0,...,20220,631.875000,20220,631.875000,2.041048,2.041048,0.0,0.0,0.0,E361
2,1,A,3,8.0,BIOLUTION3_AF454_EO3,32,1420,44.37500,0,0,...,23835,794.500000,23835,794.500000,1.749948,1.749948,0.0,0.0,0.0,E361
3,1,A,4,11.0,BIOLUTION6_AF227_EO3,32,1400,43.75000,0,0,...,21680,774.285714,21680,774.285714,1.785055,1.785055,0.0,0.0,0.0,E361
4,1,A,5,5.0,ALURA_FRACTAL_227,32,1395,43.59375,0,0,...,22860,737.419355,22860,737.419355,1.867454,1.867454,0.0,0.0,0.0,E361

In [4]:
E361[[i for i in E361.columns if "Sampling" in i]].columns

Index(['Sampling 7d', 'Sampling weight 7d, g', 'Sampling 14d',
       'Sampling weight 14d, g', 'Sampling 21d', 'Sampling weight 21d, g',
       'Sampling 22d', 'Sampling weight 22d, g', 'Sampling 29d',
       'Sampling weight 29d, g', 'Sampling 42d', 'Sampling weight 42d, g'],
      dtype='object')

In [5]:
dfE361 = E361[['ProjectID','House', 'Pen', 'Blind Trts ', 'Trts.', 
               
               'Group BWh, g', 'Group BW7, g', 'Group BW14, g', 'Group BW 21d, g', 'Group BW28d, g', 'Group BW 35d, g', 'Group BW 42d, g',

               '# Ini birds 1d', '# Fnl birds 7d', 'Fnl birds 14d','# Fnl birds 21d','# Fnl birds 28d','# Fnl birds 35d','# Fnl birds 42d',

               'Mortality weight 7d, g', 'Mortality weight 14d, g', 'Mortality weight 21d, g', 'Mortality weight 28d, g', 'Mortality weight 35d, g', 'Mortality weight 42d, g',

               'Culling 7d', 'Culling 14d', 'Culling 21d', 'Culling 28d', 'Culling 35d', 'Culling 42d', 


                'Culling weight 7d, g', 'Culling weight 14d, g', 'Culling weight 21d, g', 'Culling weight 28d, g', 'Culling weight 35d', 'Culling weight 42d, g',

               
               'Sampling 7d', 'Sampling 14d', 'Sampling 21d', 'Sampling 22d', 'Sampling 29d', 'Sampling 42d',
               
               
               'Sampling weight 7d, g',  'Sampling weight 14d, g',  'Sampling weight 21d, g', 'Sampling weight 22d, g', 'Sampling weight 29d, g',  'Sampling weight 42d, g', 

               
               
               'Group FI 0-7d, g', 'Group FI 8-14d, g', 'Group FI 15-21d, g','Group FI 22-28d, g', 'Group FI 29-35d, g', 'Group FI 36-42d, g',

               

               
             ]]
dfE361.head()

,ProjectID,House,Pen,Blind Trts,Trts.,"Group BWh, g","Group BW7, g","Group BW14, g","Group BW 21d, g","Group BW28d, g",...,"Sampling weight 21d, g","Sampling weight 22d, g","Sampling weight 29d, g","Sampling weight 42d, g","Group FI 0-7d, g","Group FI 8-14d, g","Group FI 15-21d, g","Group FI 22-28d, g","Group FI 29-35d, g","Group FI 36-42d, g"
0,E361,1,1,4.0,ALURA_FRACTAL_454,1415,5200,12315,26870,45670,...,0,975,1455,0,4820,10000,20060,27980,35600,41020
1,E361,1,2,10.0,BIOLUTION5_AF227_EO2,1410,4830,11265,25130,44380,...,0,0,0,0,4510,8920,19040,27550,37220,41270
2,E361,1,3,8.0,BIOLUTION3_AF454_EO3,1420,5105,11925,26800,45530,...,0,945,1365,0,4690,9370,19880,27820,36290,41710
3,E361,1,4,11.0,BIOLUTION6_AF227_EO3,1400,4520,10405,22350,39200,...,0,0,0,0,4450,9410,17750,24700,34550,38700
4,E361,1,5,5.0,ALURA_FRACTAL_227,1395,5115,10995,24400,43970,...,0,0,0,0,4840,9420,19180,27210,37440,42690

In [6]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Blind Trts ': 'TreatmentNumber',
    'Trts.': 'Treatment',
    
    'Group BWh, g': 'GBW_initial',
    'Group BW7, g': 'GBW_7',
    'Group BW14, g': 'GBW_14',
    'Group BW 21d, g': 'GBW_21',
    'Group BW28d, g': 'GBW_28',
    'Group BW 35d, g': 'GBW_35',
    'Group BW 42d, g': 'GBW_42',
    
    '# Ini birds 1d': 'Init_Birds_D1',
    '# Fnl birds 7d': 'Fnl_Birds_D7',
    'Fnl birds 14d': 'Fnl_Birds_D14',
    '# Fnl birds 21d': 'Fnl_Birds_D21',
    '# Fnl birds 28d': 'Fnl_Birds_D28',
    '# Fnl birds 35d': 'Fnl_Birds_D35',
    '# Fnl birds 42d': 'Fnl_Birds_D42',
    
    'Mortality weight 7d, g': 'Mort_Wt_D7',
    'Mortality weight 14d, g': 'Mort_Wt_D14',
    'Mortality weight 21d, g': 'Mort_Wt_D21',
    'Mortality weight 28d, g': 'Mort_Wt_D28',
    'Mortality weight 35d, g': 'Mort_Wt_D35',
    'Mortality weight 42d, g': 'Mort_Wt_D42',
    
    'Culling 7d': 'Cull_D7',
    'Culling 14d': 'Cull_D14',
    'Culling 21d': 'Cull_D21',
    'Culling 28d': 'Cull_D28',
    'Culling 35d': 'Cull_D35',
    'Culling 42d': 'Cull_D42',
    
    'Culling weight 7d, g': 'Cull_Wt_D7',
    'Culling weight 14d, g': 'Cull_Wt_D14',
    'Culling weight 21d, g': 'Cull_Wt_D21',
    'Culling weight 28d, g': 'Cull_Wt_D28',
    'Culling weight 35d': 'Cull_Wt_D35',
    'Culling weight 42d, g': 'Cull_Wt_D42',
    
    'Sampling 7d': 'Samp_D7',
    'Sampling 14d': 'Samp_D14',
    'Sampling 21d': 'Samp_D21',
    'Sampling 22d': 'Samp_D22',
    'Sampling 29d': 'Samp_D29',
    'Sampling 42d': 'Samp_D42',
    
    'Sampling weight 7d, g': 'Samp_Wt_D7',
    'Sampling weight 14d, g': 'Samp_Wt_D14',
    'Sampling weight 21d, g': 'Samp_Wt_D21',
    'Sampling weight 22d, g': 'Samp_Wt_D22',
    'Sampling weight 29d, g': 'Samp_Wt_D29',
    'Sampling weight 42d, g': 'Samp_Wt_D42',
    
    'Group FI 0-7d, g': 'GFI_0_7D',
    'Group FI 8-14d, g': 'GFI_8_14D',
    'Group FI 15-21d, g': 'GFI_15_21D',
    'Group FI 22-28d, g': 'GFI_22_28D',
    'Group FI 29-35d, g': 'GFI_29_35D',
    'Group FI 36-42d, g': 'GFI_36_42D'
}

dfE361.rename(columns=column_rename_map, inplace=True)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_1301/3842922909.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfE361.rename(columns=column_rename_map, inplace=True)

In [7]:
dfE361.head()

,ProjectID,House,Pen,TreatmentNumber,Treatment,GBW_initial,GBW_7,GBW_14,GBW_21,GBW_28,...,Samp_Wt_D21,Samp_Wt_D22,Samp_Wt_D29,Samp_Wt_D42,GFI_0_7D,GFI_8_14D,GFI_15_21D,GFI_22_28D,GFI_29_35D,GFI_36_42D
0,E361,1,1,4.0,ALURA_FRACTAL_454,1415,5200,12315,26870,45670,...,0,975,1455,0,4820,10000,20060,27980,35600,41020
1,E361,1,2,10.0,BIOLUTION5_AF227_EO2,1410,4830,11265,25130,44380,...,0,0,0,0,4510,8920,19040,27550,37220,41270
2,E361,1,3,8.0,BIOLUTION3_AF454_EO3,1420,5105,11925,26800,45530,...,0,945,1365,0,4690,9370,19880,27820,36290,41710
3,E361,1,4,11.0,BIOLUTION6_AF227_EO3,1400,4520,10405,22350,39200,...,0,0,0,0,4450,9410,17750,24700,34550,38700
4,E361,1,5,5.0,ALURA_FRACTAL_227,1395,5115,10995,24400,43970,...,0,0,0,0,4840,9420,19180,27210,37440,42690

In [7]:
dfE361.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE361.csv', index=False)

In [60]:
dfE361.columns

Index(['ProjectID', 'House', 'Pen', 'Blind_Treatments', 'Treatments',
       'GBW_initial', 'GBW_7', 'GBW_14', 'GBW_21', 'GBW_28', 'GBW_35',
       'GBW_42', 'Init_Birds_Day1', 'Fnl_Birds_Day7', 'Fnl_Birds_Day14',
       'Fnl_Birds_Day21', 'Fnl_Birds_Day28', 'Fnl_Birds_Day35',
       'Fnl_Birds_Day42', 'Mort_Wt_D7', 'Mort_Wt_D14', 'Mort_Wt_D21',
       'Mort_Wt_D28', 'Mort_Wt_D35', 'Mort_Wt_D42', 'Cull_D7', 'Cull_D14',
       'Cull_D21', 'Cull_D28', 'Cull_D35', 'Cull_D42', 'Cull_Wt_D7',
       'Cull_Wt_D14', 'Cull_Wt_D21', 'Cull_Wt_D28', 'Cull_Wt_D35',
       'Cull_Wt_D42', 'Samp_D7', 'Samp_D14', 'Samp_D21', 'Samp_D22',
       'Samp_D29', 'Samp_D42', 'Samp_Wt_D7', 'Samp_Wt_D14', 'Samp_Wt_D21',
       'Samp_Wt_D22', 'Samp_Wt_D29', 'Samp_Wt_D42', 'GFI_0_7d', 'GFI_8_14d',
       'GFI_15_21d', 'GFI_22_28d', 'GFI_29_35d', 'GFI_36_42d'],
      dtype='object')

# new columns

In [152]:
def calculate_columns(df):
    # Definir las columnas necesarias para cada cálculo con los nombres definitivos
    bw_columns = [('BW7', 'GBW_7', 'Fnl_Birds_Day7'),
                  ('BW14', 'GBW_14', 'Fnl_Birds_Day14'),
                  ('BW21', 'GBW_21', 'Fnl_Birds_Day21'),
                  ('BW28', 'GBW_28', 'Fnl_Birds_Day28'),
                  ('BW35', 'GBW_35', 'Fnl_Birds_Day35'),
                  ('BW42', 'GBW_42', 'Fnl_Birds_Day42')]
    
    fcr_columns = [('FCR0_7', 'GFI_0_7d', 'GBW_7', 'GBW_initial', 'Fnl_Birds_Day7'),
                   ('FCR8_14', 'GFI_8_14d', 'GBW_14', 'GBW_initial', 'Fnl_Birds_Day14'),
                   ('FCR15_21', 'GFI_15_21d', 'GBW_21', 'GBW_14', 'Fnl_Birds_Day21'),
                   ('FCR22_28', 'GFI_22_28d', 'GBW_28', 'GBW_21', 'Fnl_Birds_Day28'),
                   ('FCR29_35', 'GFI_29_35d', 'GBW_35', 'GBW_28', 'Fnl_Birds_Day35'),
                   ('FCR36_42', 'GFI_36_42d', 'GBW_42', 'GBW_35', 'Fnl_Birds_Day42')]
    
    cfcr_columns = [('cFCR0_7', 'GFI_0_7d', 'GBW_7', 'GBW_initial', 'Mort_Wt_D7', 'Cull_Wt_D7', 'Fnl_Birds_Day7'),
                    ('cFCR8_14', 'GFI_8_14d', 'GBW_14', 'GBW_7', 'Mort_Wt_D14', 'Cull_Wt_D14', 'Fnl_Birds_Day14'),
                    ('cFCR15_21', 'GFI_15_21d', 'GBW_21', 'GBW_14', 'Mort_Wt_D21', 'Cull_Wt_D21', 'Fnl_Birds_Day21'),
                    ('cFCR22_28', 'GFI_22_28d', 'GBW_28', 'GBW_21', 'Mort_Wt_D28', 'Cull_Wt_D28', 'Fnl_Birds_Day28'),
                    ('cFCR29_35', 'GFI_29_35d', 'GBW_35', 'GBW_28', 'Mort_Wt_D35', 'Cull_Wt_D35', 'Fnl_Birds_Day35'),
                    ('cFCR36_42', 'GFI_36_42d', 'GBW_42', 'GBW_35', 'Mort_Wt_D42', 'Cull_Wt_D42', 'Fnl_Birds_Day42')]
    
    mort_columns = [('Mort7', 'Init_Birds_Day1', 'Fnl_Birds_Day7'),
                    ('Mort14', 'Init_Birds_Day1', 'Fnl_Birds_Day14'),
                    ('Mort21', 'Init_Birds_Day1', 'Fnl_Birds_Day21'),
                    ('Mort28', 'Init_Birds_Day1', 'Fnl_Birds_Day28'),
                    ('Mort35', 'Init_Birds_Day1', 'Fnl_Birds_Day35'),
                    ('Mort42', 'Init_Birds_Day1', 'Fnl_Birds_Day42')]

    # Función auxiliar para verificar columnas y calcular
    def verify_and_calculate(df, column_set, formula):
        for col_set in column_set:
            new_col = col_set[0]
            required_cols = col_set[1:]
            # Verificar si todas las columnas requeridas están en el DataFrame
            if all(col in df.columns for col in required_cols):
                df[new_col] = formula(df, *required_cols)
            else:
                missing_cols = [col for col in required_cols if col not in df.columns]
                print(f"Cannot calculate '{new_col}': missing columns {missing_cols}")

    # Definir fórmulas para cada cálculo
    verify_and_calculate(df, bw_columns, lambda df, gbw, birds: df[gbw] / df[birds])
    verify_and_calculate(df, fcr_columns, lambda df, fi, gbw, gbw_init, birds: (df[fi] / (df[gbw] - df[gbw_init])))
    verify_and_calculate(df, cfcr_columns, lambda df, fi, gbw, gbw_init, mort_wt, cull_wt, birds: (df[fi] / (df[gbw] - df[gbw_init] + df[mort_wt] + df[cull_wt])))
    verify_and_calculate(df, mort_columns, lambda df, ini_birds, fnl_birds: ((df[ini_birds] - df[fnl_birds]) / df[ini_birds]) * 100)
    return df

In [77]:
dfE361 = calculate_columns(dfE361)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_11521/1495824541.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = formula(df, *required_cols)

In [78]:
dfE361.head()

,ProjectID,House,Pen,Blind_Treatments,Treatments,GBW_initial,GBW_7,GBW_14,GBW_21,GBW_28,...,cFCR15_21,cFCR22_28,cFCR29_35,cFCR36_42,Mort7,Mort14,Mort21,Mort28,Mort35,Mort42
0,E361,1,1,4.0,ALURA_FRACTAL_454,1415,5200,12315,26870,45670,...,1.378221,1.488298,1.630783,1.952404,0.0,0.000,0.000,3.125,6.250,6.250
1,E361,1,2,10.0,BIOLUTION5_AF227_EO2,1410,4830,11265,25130,44380,...,1.373242,1.431169,1.542478,2.041048,0.0,0.000,0.000,0.000,0.000,0.000
2,E361,1,3,8.0,BIOLUTION3_AF454_EO3,1420,5105,11925,26800,45530,...,1.336471,1.485318,1.691053,1.856253,0.0,0.000,0.000,3.125,6.250,6.250
3,E361,1,4,11.0,BIOLUTION6_AF227_EO3,1400,4520,10405,22350,39200,...,1.485977,1.465875,1.623590,1.785055,0.0,0.000,6.250,9.375,12.500,12.500
4,E361,1,5,5.0,ALURA_FRACTAL_227,1395,5115,10995,24400,43970,...,1.430809,1.390393,1.538841,1.867454,0.0,3.125,3.125,3.125,3.125,3.125

In [80]:
dfE361.filter(like='FCR')

,FCR0_7,FCR8_14,FCR15_21,FCR22_28,FCR29_35,FCR36_42,cFCR0_7,cFCR8_14,cFCR15_21,cFCR22_28,cFCR29_35,cFCR36_42
0,1.273448,0.917431,1.378221,1.488298,1.630783,1.952404,1.273448,1.405481,1.378221,1.488298,1.630783,1.952404
1,1.318713,0.905124,1.373242,1.431169,1.542478,2.041048,1.318713,1.386169,1.373242,1.431169,1.542478,2.041048
2,1.272727,0.891956,1.336471,1.485318,1.691053,1.856253,1.272727,1.373900,1.336471,1.485318,1.691053,1.856253
3,1.426282,1.044975,1.485977,1.465875,1.623590,1.785055,1.426282,1.514079,1.485977,1.465875,1.623590,1.785055
4,1.301075,0.981250,1.430809,1.390393,1.538841,1.867454,1.301075,1.602041,1.430809,1.390393,1.538841,1.867454
...,...,...,...,...,...,...,...,...,...,...,...,...
155,1.315615,0.923077,1.338636,1.411765,1.596570,2.247761,1.285714,1.410526,1.338636,1.411765,1.596570,2.247761
156,1.400000,0.960958,1.441400,1.522686,1.610628,2.920777,1.400000,1.414559,1.441400,1.522686,1.610628,2.920777
157,1.396880,1.048349,1.433962,1.466147,1.680064,2.090079,1.396880,1.588919,1.433962,1.466147,1.680064,2.090079
158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# si queremos en long format

se necesitan variables como peso inicial total, numero de animales totales, siempre al inicio para ponder hacer los calculos de las variables adicionales, lo mejor es hacer los calculos en wide format y luego convertir


Que pasa si se pasa un dia o dos el muestreo, como cambian las ecuaciones, ajustamos a cada caso o solo tenemos en cuenta rangos especificos y ya?

cuando se calculan variables acumuladas se complica un longformat, mejor dejar wide, y luego de calcular poner en long format

In [81]:
dfE361.columns

Index(['ProjectID', 'House', 'Pen', 'Blind_Treatments', 'Treatments',
       'GBW_initial', 'GBW_7', 'GBW_14', 'GBW_21', 'GBW_28', 'GBW_35',
       'GBW_42', 'Init_Birds_Day1', 'Fnl_Birds_Day7', 'Fnl_Birds_Day14',
       'Fnl_Birds_Day21', 'Fnl_Birds_Day28', 'Fnl_Birds_Day35',
       'Fnl_Birds_Day42', 'Mort_Wt_D7', 'Mort_Wt_D14', 'Mort_Wt_D21',
       'Mort_Wt_D28', 'Mort_Wt_D35', 'Mort_Wt_D42', 'Cull_D7', 'Cull_D14',
       'Cull_D21', 'Cull_D28', 'Cull_D35', 'Cull_D42', 'Cull_Wt_D7',
       'Cull_Wt_D14', 'Cull_Wt_D21', 'Cull_Wt_D28', 'Cull_Wt_D35',
       'Cull_Wt_D42', 'Samp_D7', 'Samp_D14', 'Samp_D21', 'Samp_D22',
       'Samp_D29', 'Samp_D42', 'Samp_Wt_D7', 'Samp_Wt_D14', 'Samp_Wt_D21',
       'Samp_Wt_D22', 'Samp_Wt_D29', 'Samp_Wt_D42', 'GFI_0_7d', 'GFI_8_14d',
       'GFI_15_21d', 'GFI_22_28d', 'GFI_29_35d', 'GFI_36_42d', 'BW7', 'BW14',
       'BW21', 'BW28', 'BW35', 'BW42', 'FCR0_7', 'FCR8_14', 'FCR15_21',
       'FCR22_28', 'FCR29_35', 'FCR36_42', 'cFCR0_7', 'cFCR8_14', 'cFCR15_21',
       'cFCR22_28', 'cFCR29_35', 'cFCR36_42', 'Mort7', 'Mort14', 'Mort21',
       'Mort28', 'Mort35', 'Mort42'],
      dtype='object')

In [88]:
dfE361[[i for i in dfE361.columns if "GFI" in i]].columns

Index(['GFI_0_7d', 'GFI_8_14d', 'GFI_15_21d', 'GFI_22_28d', 'GFI_29_35d',
       'GFI_36_42d'],
      dtype='object')

In [89]:
df1 = dfE361[['ProjectID', 'House', 'Pen', 'Blind_Treatments', 'Treatments', 'GBW_initial', 'Init_Birds_Day1', 'GBW_7', 'GBW_14', 'GBW_21', 'GBW_28', 'GBW_35', 'GBW_42']]
df2 = dfE361[['ProjectID', 'House', 'Pen', 'Blind_Treatments', 'Treatments', 'GBW_initial', 'Init_Birds_Day1', 'Fnl_Birds_Day7', 'Fnl_Birds_Day14', 'Fnl_Birds_Day21', 'Fnl_Birds_Day28', 'Fnl_Birds_Day35', 'Fnl_Birds_Day42']]
df3 = dfE361[['ProjectID', 'House', 'Pen', 'Blind_Treatments', 'Treatments', 'GBW_initial', 'Init_Birds_Day1', 'Mort_Wt_D7', 'Mort_Wt_D14', 'Mort_Wt_D21', 'Mort_Wt_D28', 'Mort_Wt_D35', 'Mort_Wt_D42']]
df4 = dfE361[['ProjectID', 'House', 'Pen', 'Blind_Treatments', 'Treatments', 'GBW_initial', 'Init_Birds_Day1', 'Cull_D7', 'Cull_D14', 'Cull_D21', 'Cull_D28', 'Cull_D35', 'Cull_D42']]
df5 = dfE361[['ProjectID', 'House', 'Pen', 'Blind_Treatments', 'Treatments', 'GBW_initial', 'Init_Birds_Day1', 'Cull_Wt_D7', 'Cull_Wt_D14', 'Cull_Wt_D21', 'Cull_Wt_D28', 'Cull_Wt_D35', 'Cull_Wt_D42']]
df6 = dfE361[['ProjectID', 'House', 'Pen', 'Blind_Treatments', 'Treatments', 'GBW_initial', 'Init_Birds_Day1', 'Samp_D7', 'Samp_D14', 'Samp_D21', 'Samp_D29', 'Samp_D42']]
df7 = dfE361[['ProjectID', 'House', 'Pen', 'Blind_Treatments', 'Treatments', 'GBW_initial', 'Init_Birds_Day1', 'Samp_Wt_D7', 'Samp_Wt_D14', 'Samp_Wt_D21', 'Samp_Wt_D29', 'Samp_Wt_D42']]
df8 = dfE361[['ProjectID', 'House', 'Pen', 'Blind_Treatments', 'Treatments', 'GBW_initial', 'Init_Birds_Day1', 'GFI_0_7d', 'GFI_8_14d', 'GFI_15_21d', 'GFI_22_28d', 'GFI_29_35d', 'GFI_36_42d']]

# E271

Este proyecto a diferencia de todos los otros los datos crudos estan en long format, pero no tienen columna de age, solo se diferencia por colores cuando inicia y termina una age


en galpon 1, corral 1 tratamiento 1 de la semana 1 a la 2 hay 4 animales que no se para donde se van, la semana 1 termina con 34 animales y la semana 2 inicia con 30
deberia iniciar con 34 tambien

In [70]:
E271 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Libro de datos E-271 Probióticos NF revisión 18-07-2022.xlsx", "Datos ")
E271.head()

,Semana,Galpón,Corral,TTO,Repetición,Initial birds,Final birds,Alimento Ofrecido (g),Alimento Sobrante (g),Peso de la canasta (g),...,Conversión Acumulada (C),Muertos,Descartes,Peso Muertos + Descartes (g),% Mortalidad Semana,% Descartes Semana,% Mortalidad + Descartes,% Mortalidad + Descartes Acumulado,"GBW Placement, g","BW placement, g"
0,1,1,1,1.0,NaN,35.0,34,49220.0,44320.0,2318.0,...,0.729377,0,1,41.45,0,2.857143,2.857143,2.857143,1486.0,42.457143
1,1,1,2,2.0,NaN,35.0,32,49280.0,44340.0,1913.0,...,0.692404,0,3,185.40,0,8.571429,8.571429,8.571429,1490.0,42.571429
2,1,1,3,1.0,NaN,35.0,34,49220.0,43720.0,2318.0,...,0.796442,0,1,42.20,0,2.857143,2.857143,2.857143,1474.0,42.114286
3,1,1,4,2.0,NaN,35.0,34,49240.0,44180.0,1913.0,...,0.697032,0,1,42.19,0,2.857143,2.857143,2.857143,1522.0,43.485714
4,1,1,5,1.0,NaN,35.0,34,49200.0,44020.0,2318.0,...,0.738174,0,1,42.51,0,2.857143,2.857143,2.857143,1480.0,42.285714

In [74]:
print(list(E271.columns))
E271["ProjectID"] = 'E271'
E271.head()

['Semana', 'Galpón', 'Corral', 'TTO', 'Repetición', 'Initial birds', 'Final birds', 'Alimento Ofrecido (g)', 'Alimento Sobrante (g)', 'Peso de la canasta (g)', 'Peso Canasta + Aves (g)', 'GBW, g', 'BW, g', 'Group FI, g', 'FI, g', 'DFI, g', 'Consumo Acumulado (g)', 'Group BWG, g', 'Ganancia Promedio (g)', 'BWG, g', 'cGroup BWG, g', 'cBWG, g', 'Ganancia Promedio/ día (g)', 'Conversión (g/g)', 'Conversión Acumulada', 'Consumo semana (C) (g)', 'Consumo Promedio (C) (g)', 'Consumo Acumulado (C) (g)', 'FCR', 'cFCR', 'Conversión (C) (g/g) ', 'Conversión Acumulada  (C) ', 'Muertos', 'Descartes', 'Peso Muertos + Descartes (g)', '% Mortalidad Semana', '% Descartes Semana', '% Mortalidad + Descartes', '% Mortalidad + Descartes Acumulado', 'GBW Placement, g', 'BW placement, g', 'ProjectID', 'Day']

,Semana,Galpón,Corral,TTO,Repetición,Initial birds,Final birds,Alimento Ofrecido (g),Alimento Sobrante (g),Peso de la canasta (g),...,Descartes,Peso Muertos + Descartes (g),% Mortalidad Semana,% Descartes Semana,% Mortalidad + Descartes,% Mortalidad + Descartes Acumulado,"GBW Placement, g","BW placement, g",ProjectID,Day
0,1,1,1,1.0,NaN,35.0,34,49220.0,44320.0,2318.0,...,1,41.45,0,2.857143,2.857143,2.857143,1486.0,42.457143,E271,7
1,1,1,2,2.0,NaN,35.0,32,49280.0,44340.0,1913.0,...,3,185.40,0,8.571429,8.571429,8.571429,1490.0,42.571429,E271,7
2,1,1,3,1.0,NaN,35.0,34,49220.0,43720.0,2318.0,...,1,42.20,0,2.857143,2.857143,2.857143,1474.0,42.114286,E271,7
3,1,1,4,2.0,NaN,35.0,34,49240.0,44180.0,1913.0,...,1,42.19,0,2.857143,2.857143,2.857143,1522.0,43.485714,E271,7
4,1,1,5,1.0,NaN,35.0,34,49200.0,44020.0,2318.0,...,1,42.51,0,2.857143,2.857143,2.857143,1480.0,42.285714,E271,7

In [73]:
E271[[i for i in E271.columns if "Sampling" in i]].columns

Index([], dtype='object')

In [51]:
print(E271.columns)

Index(['Semana', 'Galpón', 'Corral', 'TTO', 'Repetición', 'Initial birds',
       'Final birds', 'Alimento Ofrecido (g)', 'Alimento Sobrante (g)',
       'Peso de la canasta (g)', 'Peso Canasta + Aves (g)', 'GBW, g', 'BW, g',
       'Group FI, g', 'FI, g', 'DFI, g', 'Consumo Acumulado (g)',
       'Group BWG, g', 'Ganancia Promedio (g)', 'BWG, g', 'cGroup BWG, g',
       'cBWG, g', 'Ganancia Promedio/ día (g)', 'Conversión (g/g)',
       'Conversión Acumulada', 'Consumo semana (C) (g)',
       'Consumo Promedio (C) (g)', 'Consumo Acumulado (C) (g)', 'FCR', 'cFCR',
       'Conversión (C) (g/g) ', 'Conversión Acumulada  (C) ', 'Muertos',
       'Descartes', 'Peso Muertos + Descartes (g)', '% Mortalidad Semana',
       '% Descartes Semana', '% Mortalidad + Descartes',
       '% Mortalidad + Descartes Acumulado', 'GBW Placement, g',
       'BW placement, g', 'ProjectID', 'Day'],
      dtype='object')

In [84]:
dfE271 = E271[['Galpón', 'Semana', 'Corral', 'TTO', 'Initial birds', 'ProjectID',
               
               'GBW Placement, g', 
               
               'Final birds',

               'GBW, g',

               'Group FI, g', 
               
               
                'Descartes', 'Peso Muertos + Descartes (g)', 
               
               
             ]]
dfE271.head()

,Galpón,Semana,Corral,TTO,Initial birds,ProjectID,"GBW Placement, g",Final birds,"GBW, g","Group FI, g",Descartes,Peso Muertos + Descartes (g)
0,1,1,1,1.0,35.0,E271,1486.0,34,4790,4900,1,41.45
1,1,1,2,2.0,35.0,E271,1490.0,32,4853,4940,3,185.40
2,1,1,3,1.0,35.0,E271,1474.0,34,5140,5500,1,42.20
3,1,1,4,2.0,35.0,E271,1522.0,34,5241,5060,1,42.19
4,1,1,5,1.0,35.0,E271,1480.0,34,5113,5180,1,42.51

In [121]:
df1 = dfE271[dfE271['Semana'] == 1]
df2 = dfE271[dfE271['Semana'] == 2]
df3 = dfE271[dfE271['Semana'] == 3]
df4 = dfE271[dfE271['Semana'] == 4]
df5 = dfE271[dfE271['Semana'] == 5]
df6 = dfE271[dfE271['Semana'] == 6]
df6.columns

Index(['Galpón', 'Semana', 'Corral', 'TTO', 'Initial birds', 'ProjectID',
       'GBW Placement, g', 'Final birds', 'GBW, g', 'Group FI, g', 'Descartes',
       'Peso Muertos + Descartes (g)'],
      dtype='object')

In [123]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'TTO': 'TreatmentNumber',
    'GBW Placement, g': 'GBW_initial',
    'GBW, g': 'GBW_7',
    'Initial birds': 'Init_Birds_D1',
    'Final birds': 'Fnl_Birds_D7',
    'Descartes': 'Cull_D7',
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D7',
    'Group FI, g': 'GFI_0_7D',
}

df1.rename(columns=column_rename_map, inplace=True)
df1.drop(columns=['Semana'], inplace=True)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/620557069.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns=column_rename_map, inplace=True)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/620557069.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(columns=['Semana'], inplace=True)

In [115]:
df1.head()

,House,Pen,TreatmentNumber,Init_Birds_D1,ProjectID,GBW_initial,Fnl_Birds_D7,GBW_7,GFI_0_7D,Cull_D7,Mort_Cull_Wt_D7
0,1,1,1.0,35.0,E271,1486.0,34,4790,4900,1,41.45
1,1,2,2.0,35.0,E271,1490.0,32,4853,4940,3,185.40
2,1,3,1.0,35.0,E271,1474.0,34,5140,5500,1,42.20
3,1,4,2.0,35.0,E271,1522.0,34,5241,5060,1,42.19
4,1,5,1.0,35.0,E271,1480.0,34,5113,5180,1,42.51

In [122]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'TTO': 'TreatmentNumber',
    'GBW, g': 'GBW_14',
    'Final birds': 'Fnl_Birds_Day14',
    'Descartes': 'Cull_D14',
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D14',
    'Group FI, g': 'GFI_8_14d',
}

df2.rename(columns=column_rename_map, inplace=True)
df2.drop(columns=['Semana', 'GBW Placement, g', 'Initial birds'], inplace=True)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/4123473298.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns=column_rename_map, inplace=True)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/4123473298.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(columns=['Semana', 'GBW Placement, g', 'Initial birds'], inplace=True)

In [117]:
df2.head()

,House,Pen,TreatmentNumber,ProjectID,Fnl_Birds_Day14,GBW_14,GFI_8_14d,Cull_D14,Mort_Cull_Wt_D14
160,1,1,1.0,E271,30,10460,8540,0,0.0
161,1,2,2.0,E271,30,10560,8140,0,0.0
162,1,3,1.0,E271,29,10700,8280,0,0.0
163,1,4,2.0,E271,29,10770,8100,0,173.0
164,1,5,1.0,E271,30,11540,8880,0,0.0

In [124]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'TTO': 'TreatmentNumber',
    'GBW, g': 'GBW_21',
    'Final birds': 'Fnl_Birds_Day21',
    'Descartes': 'Cull_D21',
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D21',
    'Group FI, g': 'GFI_15_21d',
}

df3.rename(columns=column_rename_map, inplace=True)
df3.drop(columns=['Semana', 'GBW Placement, g', 'Initial birds'], inplace=True)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/3884261507.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.rename(columns=column_rename_map, inplace=True)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/3884261507.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop(columns=['Semana', 'GBW Placement, g', 'Initial birds'], inplace=True)

In [105]:
df3.head()

,House,Semana,Pen,TreatmentNumber,ProjectID,Fnl_Birds_Day21,GBW_21,GFI_15_21d,Cull_D21,Mort_Cull_Wt_D21
320,1,3,1,1.0,E271,29,21550,19506,1,350.0
321,1,3,2,2.0,E271,29,22620,17305,1,376.0
322,1,3,3,1.0,E271,27,21540,16999,1,1052.0
323,1,3,4,2.0,E271,28,22290,17572,1,395.0
324,1,3,5,1.0,E271,29,24160,18638,1,362.0

In [125]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'TTO': 'TreatmentNumber',
    'GBW, g': 'GBW_28',
    'Final birds': 'Fnl_Birds_Day28',
    'Descartes': 'Cull_D28',
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D28',
    'Group FI, g': 'GFI_22_28d',
}

df4.rename(columns=column_rename_map, inplace=True)
df4.drop(columns=['Semana', 'GBW Placement, g', 'Initial birds'], inplace=True)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/2370678588.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.rename(columns=column_rename_map, inplace=True)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/2370678588.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.drop(columns=['Semana', 'GBW Placement, g', 'Initial birds'], inplace=True)

In [108]:
df4.head()

,House,Semana,Pen,TreatmentNumber,ProjectID,Fnl_Birds_Day28,GBW_28,GFI_22_28d,Cull_D28,Mort_Cull_Wt_D28
480,1,4,1,1.0,E271,29,36720,23780,0,0.0
481,1,4,2,2.0,E271,29,38520,24760,0,0.0
482,1,4,3,1.0,E271,27,36600,22300,0,0.0
483,1,4,4,2.0,E271,27,36810,24980,1,910.0
484,1,4,5,1.0,E271,29,40020,24900,0,0.0

In [126]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'TTO': 'TreatmentNumber',
    'GBW, g': 'GBW_35',
    'Final birds': 'Fnl_Birds_Day35',
    'Descartes': 'Cull_D35',
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D35',
    'Group FI, g': 'GFI_29_35d',
}

df5.rename(columns=column_rename_map, inplace=True)
df5.drop(columns=['Semana', 'GBW Placement, g', 'Initial birds'], inplace=True)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/3282652079.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5.rename(columns=column_rename_map, inplace=True)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/3282652079.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5.drop(columns=['Semana', 'GBW Placement, g', 'Initial birds'], inplace=True)

In [110]:
df5.head()

,House,Semana,Pen,TreatmentNumber,ProjectID,Fnl_Birds_Day35,GBW_35,GFI_29_35d,Cull_D35,Mort_Cull_Wt_D35
640,1,5,1,1.0,E271,28,56330,32600,1,0.0
641,1,5,2,2.0,E271,28,58390,32950,1,0.0
642,1,5,3,1.0,E271,26,54250,30070,1,0.0
643,1,5,4,2.0,E271,26,55480,31840,1,0.0
644,1,5,5,1.0,E271,28,59210,33470,1,0.0

In [127]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'TTO': 'TreatmentNumber',
    'GBW, g': 'GBW_42',
    'Final birds': 'Fnl_Birds_Day42',
    'Descartes': 'Cull_D42',
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D42',
    'Group FI, g': 'GFI_36_42d',
}

df6.rename(columns=column_rename_map, inplace=True)
df6.drop(columns=['Semana', 'GBW Placement, g', 'Initial birds'], inplace=True)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/3475589670.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6.rename(columns=column_rename_map, inplace=True)
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/3475589670.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6.drop(columns=['Semana', 'GBW Placement, g', 'Initial birds'], inplace=True)

In [128]:
df6.head()

,House,Pen,TreatmentNumber,ProjectID,Fnl_Birds_Day42,GBW_42,GFI_36_42d,Cull_D42,Mort_Cull_Wt_D42
800,1,1,1.0,E271,28,79990,37750,0,0.0
801,1,2,2.0,E271,27,78870,37040,1,1380.0
802,1,3,1.0,E271,26,74810,35110,0,0.0
803,1,4,2.0,E271,26,76400,35310,0,0.0
804,1,5,1.0,E271,27,77960,36450,1,1560.0

In [96]:
df6.columns

Index(['House', 'Semana', 'Pen', 'Treatments', 'ProjectID', 'Fnl_Birds_Day42',
       'GBW_42', 'GFI_36_42d', 'Cull_D42', 'Mort_Cull_Wt_D42'],
      dtype='object')

In [129]:
E271_wide = df1.merge(df2, on=['House', 'Pen', 'TreatmentNumber', 'ProjectID'], how='left')\
               .merge(df3, on=['House', 'Pen', 'TreatmentNumber', 'ProjectID'], how='left')\
               .merge(df4, on=['House', 'Pen', 'TreatmentNumber', 'ProjectID'], how='left')\
               .merge(df5, on=['House', 'Pen', 'TreatmentNumber', 'ProjectID'], how='left')\
                .merge(df6, on=['House', 'Pen', 'TreatmentNumber', 'ProjectID'], how='left')

In [130]:
E271_wide.head()

,House,Pen,TreatmentNumber,Init_Birds_D1,ProjectID,GBW_initial,Fnl_Birds_D7,GBW_7,GFI_0_7D,Cull_D7,...,Fnl_Birds_Day35,GBW_35,GFI_29_35d,Cull_D35,Mort_Cull_Wt_D35,Fnl_Birds_Day42,GBW_42,GFI_36_42d,Cull_D42,Mort_Cull_Wt_D42
0,1,1,1.0,35.0,E271,1486.0,34,4790,4900,1,...,28,56330,32600,1,0.0,28,79990,37750,0,0.0
1,1,2,2.0,35.0,E271,1490.0,32,4853,4940,3,...,28,58390,32950,1,0.0,27,78870,37040,1,1380.0
2,1,3,1.0,35.0,E271,1474.0,34,5140,5500,1,...,26,54250,30070,1,0.0,26,74810,35110,0,0.0
3,1,4,2.0,35.0,E271,1522.0,34,5241,5060,1,...,26,55480,31840,1,0.0,26,76400,35310,0,0.0
4,1,5,1.0,35.0,E271,1480.0,34,5113,5180,1,...,28,59210,33470,1,0.0,27,77960,36450,1,1560.0

In [131]:
E271_wide.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE271.csv', index=False)

In [170]:
E271_wide = calculate_columns(E271_wide)

Cannot calculate 'cFCR0_7': missing columns ['Mort_Wt_D7', 'Cull_Wt_D7']
Cannot calculate 'cFCR8_14': missing columns ['Mort_Wt_D14', 'Cull_Wt_D14']
Cannot calculate 'cFCR15_21': missing columns ['Mort_Wt_D21', 'Cull_Wt_D21']
Cannot calculate 'cFCR22_28': missing columns ['Mort_Wt_D28', 'Cull_Wt_D28']
Cannot calculate 'cFCR29_35': missing columns ['Mort_Wt_D35', 'Cull_Wt_D35']
Cannot calculate 'cFCR36_42': missing columns ['Mort_Wt_D42', 'Cull_Wt_D42']

# E267

In [188]:
E267_sem1 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Datos ensayo E-267 Aceites esenciales 21-09-2017.xlsx", "Datos 1 sem")
E267_sem1.head()

,Semana,Galpón,Corral,Tratamiento,Repetición,Número de Aves Teórico,Aves Finales de la Semana,Alimento Ofrecido (g),Alimento Sobrante (g),Peso de la canasta (g),...,Descartes,Peso Muertos + Descartes (g),% Mortalidad Semana,% Descartes Semana,% Mortalidad + Descartes,% Mortalidad + Descartes Acumulado,Peso total recibimiento (g),Peso recibimiento,Pollos iniciales semana,Unnamed: 40
0,1,1,1,5.0,1,35.0,34,43800.0,37000.0,1921.0,...,1,51,0.0,2.857143,2.857143,2.857143,1586.0,45.314286,35,28.0
1,1,1,2,8.0,1,35.0,34,43800.0,37020.0,1942.0,...,1,53,0.0,2.857143,2.857143,2.857143,1573.0,44.942857,35,NaN
2,1,1,3,4.0,1,35.0,34,43800.0,37020.0,1921.0,...,1,51,0.0,2.857143,2.857143,2.857143,1520.0,43.428571,35,NaN
3,1,1,4,1.0,1,33.0,31,43800.0,37540.0,1942.0,...,2,128,0.0,6.060606,6.060606,6.060606,1468.0,44.484848,33,NaN
4,1,1,5,6.0,2,35.0,34,43800.0,37320.0,1921.0,...,1,49,0.0,2.857143,2.857143,2.857143,1472.0,42.057143,35,NaN

In [189]:
print(list(E267_sem1.columns))
E267_sem1["ProjectID"] = 'E267'
E267_sem1.head()

['Semana', 'Galpón', 'Corral', 'Tratamiento', 'Repetición', 'Número de Aves Teórico', 'Aves Finales de la Semana', 'Alimento Ofrecido (g)', 'Alimento Sobrante (g)', 'Peso de la canasta (g)', 'Peso Canasta + Aves (g)', 'Número descartes', 'Peso mermas', 'Peso lote menos descartes', 'Consumo Semana (g)', 'Consumo semana (C) (g)', 'Consumo promedio (g)', 'Consumo Promedio (C) (g)', 'Consumo Acumulado (g)', 'Consumo Acumulado (C) (g)', 'Consumo Ave/Día (g)', 'PESO PROMEDIO FINAL', 'Peso del Lote Aves (g)', 'Peso Promedio x Ave (g)', 'Ganancia Promedio (g)', 'Conversión (g/g)', 'Conversión (g/g) ©', 'Conversión Acumulada', 'Conversión Acumulada ©', 'Conversión Biológica Acumulada', 'Muertos', 'Descartes', 'Peso Muertos + Descartes (g)', '% Mortalidad Semana', '% Descartes Semana', '% Mortalidad + Descartes', '% Mortalidad + Descartes Acumulado', 'Peso total recibimiento (g)', 'Peso recibimiento', 'Pollos iniciales semana', 'Unnamed: 40']

,Semana,Galpón,Corral,Tratamiento,Repetición,Número de Aves Teórico,Aves Finales de la Semana,Alimento Ofrecido (g),Alimento Sobrante (g),Peso de la canasta (g),...,Peso Muertos + Descartes (g),% Mortalidad Semana,% Descartes Semana,% Mortalidad + Descartes,% Mortalidad + Descartes Acumulado,Peso total recibimiento (g),Peso recibimiento,Pollos iniciales semana,Unnamed: 40,ProjectID
0,1,1,1,5.0,1,35.0,34,43800.0,37000.0,1921.0,...,51,0.0,2.857143,2.857143,2.857143,1586.0,45.314286,35,28.0,E267
1,1,1,2,8.0,1,35.0,34,43800.0,37020.0,1942.0,...,53,0.0,2.857143,2.857143,2.857143,1573.0,44.942857,35,NaN,E267
2,1,1,3,4.0,1,35.0,34,43800.0,37020.0,1921.0,...,51,0.0,2.857143,2.857143,2.857143,1520.0,43.428571,35,NaN,E267
3,1,1,4,1.0,1,33.0,31,43800.0,37540.0,1942.0,...,128,0.0,6.060606,6.060606,6.060606,1468.0,44.484848,33,NaN,E267
4,1,1,5,6.0,2,35.0,34,43800.0,37320.0,1921.0,...,49,0.0,2.857143,2.857143,2.857143,1472.0,42.057143,35,NaN,E267

In [190]:
E267_sem1['GBW, g'] = E267_sem1['Peso Canasta + Aves (g)'] - E267_sem1['Peso de la canasta (g)']

In [209]:
df1 = E267_sem1[['ProjectID', 'Galpón', 'Corral', 'Tratamiento', 'Pollos iniciales semana', 
               
               'Peso total recibimiento (g)', 
               
               'Aves Finales de la Semana',

               'GBW, g',

               'Consumo Semana (g)', 
               

                 'Muertos', 
                
                 
                 'Peso Muertos + Descartes (g)', 
               
               
             ]]
df1.head()

,ProjectID,Galpón,Corral,Tratamiento,Pollos iniciales semana,Peso total recibimiento (g),Aves Finales de la Semana,"GBW, g",Consumo Semana (g),Muertos,Peso Muertos + Descartes (g)
0,E267,1,1,5.0,35,1586.0,34,6542.0,6800,0,51
1,E267,1,2,8.0,35,1573.0,34,6181.0,6780,0,53
2,E267,1,3,4.0,35,1520.0,34,6291.0,6780,0,51
3,E267,1,4,1.0,33,1468.0,31,6134.0,6260,0,128
4,E267,1,5,6.0,35,1472.0,34,6297.0,6480,0,49

In [210]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'Tratamiento': 'TreatmentNumber',
    'Pollos iniciales semana':'Init_Birds_D1',
    'Peso total recibimiento (g)':'GBW_initial',
    'GBW, g': 'GBW_D7',
    'Aves Finales de la Semana': 'Fnl_Birds_D7',
    'Descartes': 'Cull_D7',
    'Muertos':'Mort_D7', 
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D7',
    'Consumo Semana (g)': 'GFI_0_7D'
}

df1.rename(columns=column_rename_map, inplace=True)
df1.head()

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/239285266.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns=column_rename_map, inplace=True)

,ProjectID,House,Pen,TreatmentNumber,Init_Birds_D1,GBW_initial,Fnl_Birds_D7,GBW_D7,GFI_0_7D,Mort_D7,Mort_Cull_Wt_D7
0,E267,1,1,5.0,35,1586.0,34,6542.0,6800,0,51
1,E267,1,2,8.0,35,1573.0,34,6181.0,6780,0,53
2,E267,1,3,4.0,35,1520.0,34,6291.0,6780,0,51
3,E267,1,4,1.0,33,1468.0,31,6134.0,6260,0,128
4,E267,1,5,6.0,35,1472.0,34,6297.0,6480,0,49

In [193]:
E267_sem2 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Datos ensayo E-267 Aceites esenciales 21-09-2017.xlsx", "Datos 2-6 sem")
E267_sem2.head()
E267_sem2['GBW, g'] = E267_sem2['Peso Canasta + Aves (g)'] - E267_sem2['Peso de la canasta (g)']

In [194]:
print(list(E267_sem2.columns))
E267_sem2["ProjectID"] = 'E267'
E267_sem2.head()

['Semana', 'Galpón', 'Corral', 'Tratamiento', 'Repetición', 'Número de Aves Teórico', 'Aves Finales de la Semana', 'Alimento Ofrecido (g)', 'Alimento Sobrante (g)', 'Peso de la canasta (g)', 'Peso Canasta + Aves (g)', 'Consumo Semana (g)', 'Consumo semana (C) (g)', 'Consumo promedio (g)', 'Consumo Promedio (C) (g)', 'Consumo Acumulado (g)', 'Consumo Acumulado (C) (g)', 'Consumo Ave/Día (g)', 'Peso del Lote Aves (g)', 'Peso Promedio x Ave (g)', 'Ganancia Promedio (g)', 'Conversión (g/g)', 'Conversión (C) (g/g)', 'Conversión Acumulada', 'Conversión Acumulada ©', 'Conversión Biológica Acumulada', 'Muertos', 'Descartes', 'Peso Muertos + Descartes (g)', '% Mortalidad Semana', '% Descartes Semana', '% Mortalidad + Descartes', '% Mortalidad + Descartes Acumulado', 'Peso total recibimiento (g)', 'Peso recibimiento semana 2 (g)', 'Pollos iniciales semana', 'GBW, g']

,Semana,Galpón,Corral,Tratamiento,Repetición,Número de Aves Teórico,Aves Finales de la Semana,Alimento Ofrecido (g),Alimento Sobrante (g),Peso de la canasta (g),...,Peso Muertos + Descartes (g),% Mortalidad Semana,% Descartes Semana,% Mortalidad + Descartes,% Mortalidad + Descartes Acumulado,Peso total recibimiento (g),Peso recibimiento semana 2 (g),Pollos iniciales semana,"GBW, g",ProjectID
0,1,1,1,5.0,1,NaN,-1,NaN,NaN,NaN,...,51,NaN,NaN,NaN,NaN,1586.0,45.314286,35.0,NaN,E267
1,1,1,2,8.0,1,NaN,-1,NaN,NaN,NaN,...,53,NaN,NaN,NaN,NaN,1573.0,44.942857,35.0,NaN,E267
2,1,1,3,4.0,1,NaN,-1,NaN,NaN,NaN,...,51,NaN,NaN,NaN,NaN,1520.0,43.428571,35.0,NaN,E267
3,1,1,4,1.0,1,NaN,-2,NaN,NaN,NaN,...,128,NaN,NaN,NaN,NaN,1468.0,41.942857,35.0,NaN,E267
4,1,1,5,6.0,2,NaN,-1,NaN,NaN,NaN,...,49,NaN,NaN,NaN,NaN,1472.0,42.057143,35.0,NaN,E267

In [195]:
df2 = E267_sem2[E267_sem2['Semana'] == 2]
df3 = E267_sem2[E267_sem2['Semana'] == 3]
df4 = E267_sem2[E267_sem2['Semana'] == 4]
df5 = E267_sem2[E267_sem2['Semana'] == 5]
df6 = E267_sem2[E267_sem2['Semana'] == 6]

In [196]:
df2 = df2[['ProjectID', 'Galpón', 'Corral', 'Tratamiento', 
               

               
               'Aves Finales de la Semana',

               'GBW, g',

               'Consumo Semana (g)', 
               
               
                'Descartes', 

                 'Muertos', 
                
                 
                 'Peso Muertos + Descartes (g)', 
               
               
             ]]
df2.head()

,ProjectID,Galpón,Corral,Tratamiento,Aves Finales de la Semana,"GBW, g",Consumo Semana (g),Descartes,Muertos,Peso Muertos + Descartes (g)
160,E267,1,1,5.0,27,12060.0,10460,1,0,435
161,E267,1,2,8.0,27,11980.0,9980,1,0,431
162,E267,1,3,4.0,27,11840.0,9660,1,0,444
163,E267,1,4,1.0,27,12300.0,10120,1,0,457
164,E267,1,5,6.0,27,12100.0,9640,1,0,426

In [197]:
df3 = df3[['ProjectID', 'Galpón', 'Corral', 'Tratamiento', 
               

               
               'Aves Finales de la Semana',

               'GBW, g',

               'Consumo Semana (g)', 
               
               
                'Descartes',

                 'Muertos', 
                
                 
                 'Peso Muertos + Descartes (g)', 
               
               
             ]]
df3.head()

,ProjectID,Galpón,Corral,Tratamiento,Aves Finales de la Semana,"GBW, g",Consumo Semana (g),Descartes,Muertos,Peso Muertos + Descartes (g)
320,E267,1,1,5.0,27,24200.0,20745,0,0,0
321,E267,1,2,8.0,27,24170.0,19330,0,0,0
322,E267,1,3,4.0,27,23730.0,19605,0,0,0
323,E267,1,4,1.0,26,24400.0,20121,1,0,740
324,E267,1,5,6.0,27,25130.0,19971,0,0,0

In [198]:
df4 = df4[['ProjectID', 'Galpón', 'Corral', 'Tratamiento', 
               
               
               'Aves Finales de la Semana',

               'GBW, g',

               'Consumo Semana (g)', 
               
               
                'Descartes',

                 'Muertos', 
                
                 
                 'Peso Muertos + Descartes (g)'
               
               
             ]]
df4.head()

,ProjectID,Galpón,Corral,Tratamiento,Aves Finales de la Semana,"GBW, g",Consumo Semana (g),Descartes,Muertos,Peso Muertos + Descartes (g)
480,E267,1,1,5.0,27,36830.0,27810,0,0,0
481,E267,1,2,8.0,27,38890.0,27260,0,0,0
482,E267,1,3,4.0,27,37950.0,28400,0,0,0
483,E267,1,4,1.0,26,38460.0,27570,0,0,0
484,E267,1,5,6.0,27,39140.0,26610,0,0,0

In [199]:
df5 = df5[['ProjectID', 'Galpón', 'Corral', 'Tratamiento', 
               
               
               'Aves Finales de la Semana',

               'GBW, g',

               'Consumo Semana (g)', 
               
               
                'Descartes',

                 'Muertos', 
                

           
                 'Peso Muertos + Descartes (g)']]
df5.head()

,ProjectID,Galpón,Corral,Tratamiento,Aves Finales de la Semana,"GBW, g",Consumo Semana (g),Descartes,Muertos,Peso Muertos + Descartes (g)
640,E267,1,1,5.0,26,55590.0,32310,1,0,1263
641,E267,1,2,8.0,25,54600.0,31640,2,0,3095
642,E267,1,3,4.0,26,55460.0,33340,1,0,1407
643,E267,1,4,1.0,24,53880.0,31850,1,1,3149
644,E267,1,5,6.0,26,57110.0,33870,1,0,1365

In [200]:
df6 = df6[['ProjectID', 'Galpón', 'Corral', 'Tratamiento', 
                              
               'Aves Finales de la Semana',

               'GBW, g',

               'Consumo Semana (g)', 
               
               
                'Descartes',

                 'Muertos', 
                
                 
                 'Peso Muertos + Descartes (g)', 
               
               
             ]]
df6.head()

,ProjectID,Galpón,Corral,Tratamiento,Aves Finales de la Semana,"GBW, g",Consumo Semana (g),Descartes,Muertos,Peso Muertos + Descartes (g)
800,E267,1,1,5.0,26,74290.0,30260,0,0,0
801,E267,1,2,8.0,25,73540.0,29780,0,0,0
802,E267,1,3,4.0,26,75280.0,30620,0,0,0
803,E267,1,4,1.0,24,71640.0,29000,0,0,0
804,E267,1,5,6.0,26,75420.0,30860,0,0,0

In [201]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'Tratamiento': 'TreatmentNumber',
    'GBW, g': 'GBW_D14',
    'Aves Finales de la Semana': 'Fnl_Birds_D14',
    'Descartes': 'Cull_D14',
    'Muertos':'Mort_D14', 
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D14',
    'Consumo Semana (g)': 'GFI_8_14D'
}

df2.rename(columns=column_rename_map, inplace=True)
df2.head()

,ProjectID,House,Pen,TreatmentNumber,Fnl_Birds_D14,GBW_D14,GFI_8_14D,Cull_D14,Mort_D14,Mort_Cull_Wt_D14
160,E267,1,1,5.0,27,12060.0,10460,1,0,435
161,E267,1,2,8.0,27,11980.0,9980,1,0,431
162,E267,1,3,4.0,27,11840.0,9660,1,0,444
163,E267,1,4,1.0,27,12300.0,10120,1,0,457
164,E267,1,5,6.0,27,12100.0,9640,1,0,426

In [202]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'Tratamiento': 'TreatmentNumber',
    'GBW, g': 'GBW_D21',
    'Aves Finales de la Semana': 'Fnl_Birds_D21',
    'Descartes': 'Cull_D21',
    'Muertos':'Mort_D21', 
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D21',
    'Consumo Semana (g)': 'GFI_15_21D'
}

df3.rename(columns=column_rename_map, inplace=True)
df3.head()

,ProjectID,House,Pen,TreatmentNumber,Fnl_Birds_D21,GBW_D21,GFI_15_21D,Cull_D21,Mort_D21,Mort_Cull_Wt_D21
320,E267,1,1,5.0,27,24200.0,20745,0,0,0
321,E267,1,2,8.0,27,24170.0,19330,0,0,0
322,E267,1,3,4.0,27,23730.0,19605,0,0,0
323,E267,1,4,1.0,26,24400.0,20121,1,0,740
324,E267,1,5,6.0,27,25130.0,19971,0,0,0

In [203]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'Tratamiento': 'TreatmentNumber',
    'GBW, g': 'GBW_D28',
    'Aves Finales de la Semana': 'Fnl_Birds_D28',
    'Descartes': 'Cull_D28',
    'Muertos':'Mort_D28', 
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D28',
    'Consumo Semana (g)': 'GFI_22_28D'
}

df4.rename(columns=column_rename_map, inplace=True)
df4.head()

,ProjectID,House,Pen,TreatmentNumber,Fnl_Birds_D28,GBW_D28,GFI_22_28D,Cull_D28,Mort_D28,Mort_Cull_Wt_D28
480,E267,1,1,5.0,27,36830.0,27810,0,0,0
481,E267,1,2,8.0,27,38890.0,27260,0,0,0
482,E267,1,3,4.0,27,37950.0,28400,0,0,0
483,E267,1,4,1.0,26,38460.0,27570,0,0,0
484,E267,1,5,6.0,27,39140.0,26610,0,0,0

In [204]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'Tratamiento': 'TreatmentNumber',
    'GBW, g': 'GBW_D35',
    'Aves Finales de la Semana': 'Fnl_Birds_D35',
    'Descartes': 'Cull_D35',
    'Muertos':'Mort_D35', 
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D35',
    'Consumo Semana (g)': 'GFI_29_35D'
}

df5.rename(columns=column_rename_map, inplace=True)
df5.head()

,ProjectID,House,Pen,TreatmentNumber,Fnl_Birds_D35,GBW_D35,GFI_29_35D,Cull_D35,Mort_D35,Mort_Cull_Wt_D35
640,E267,1,1,5.0,26,55590.0,32310,1,0,1263
641,E267,1,2,8.0,25,54600.0,31640,2,0,3095
642,E267,1,3,4.0,26,55460.0,33340,1,0,1407
643,E267,1,4,1.0,24,53880.0,31850,1,1,3149
644,E267,1,5,6.0,26,57110.0,33870,1,0,1365

In [205]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Galpón': 'House',
    'Corral': 'Pen',
    'Tratamiento': 'TreatmentNumber',
    'GBW, g': 'GBW_D42',
    'Aves Finales de la Semana': 'Fnl_Birds_D42',
    'Descartes': 'Cull_D42',
    'Muertos':'Mort_D42', 
    'Peso Muertos + Descartes (g)': 'Mort_Cull_Wt_D42',
    'Consumo Semana (g)': 'GFI_36_42D'
}

df6.rename(columns=column_rename_map, inplace=True)
df6.head()

,ProjectID,House,Pen,TreatmentNumber,Fnl_Birds_D42,GBW_D42,GFI_36_42D,Cull_D42,Mort_D42,Mort_Cull_Wt_D42
800,E267,1,1,5.0,26,74290.0,30260,0,0,0
801,E267,1,2,8.0,25,73540.0,29780,0,0,0
802,E267,1,3,4.0,26,75280.0,30620,0,0,0
803,E267,1,4,1.0,24,71640.0,29000,0,0,0
804,E267,1,5,6.0,26,75420.0,30860,0,0,0

In [211]:
E267_wide = df1.merge(df2, on=['House', 'Pen', 'TreatmentNumber', 'ProjectID'], how='left')\
               .merge(df3, on=['House', 'Pen', 'TreatmentNumber', 'ProjectID'], how='left')\
               .merge(df4, on=['House', 'Pen', 'TreatmentNumber', 'ProjectID'], how='left')\
               .merge(df5, on=['House', 'Pen', 'TreatmentNumber', 'ProjectID'], how='left')\
                .merge(df6, on=['House', 'Pen', 'TreatmentNumber', 'ProjectID'], how='left')

In [214]:
E267_wide.head()

,ProjectID,House,Pen,TreatmentNumber,Init_Birds_D1,GBW_initial,Fnl_Birds_D7,GBW_D7,GFI_0_7D,Mort_D7,...,GFI_29_35D,Cull_D35,Mort_D35,Mort_Cull_Wt_D35,Fnl_Birds_D42,GBW_D42,GFI_36_42D,Cull_D42,Mort_D42,Mort_Cull_Wt_D42
0,E267,1,1,5.0,35,1586.0,34,6542.0,6800,0,...,32310,1,0,1263,26,74290.0,30260,0,0,0
1,E267,1,2,8.0,35,1573.0,34,6181.0,6780,0,...,31640,2,0,3095,25,73540.0,29780,0,0,0
2,E267,1,3,4.0,35,1520.0,34,6291.0,6780,0,...,33340,1,0,1407,26,75280.0,30620,0,0,0
3,E267,1,4,1.0,33,1468.0,31,6134.0,6260,0,...,31850,1,1,3149,24,71640.0,29000,0,0,0
4,E267,1,5,6.0,35,1472.0,34,6297.0,6480,0,...,33870,1,0,1365,26,75420.0,30860,0,0,0

In [215]:
E267_wide.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE267.csv', index=False)

# E321

In [328]:
E321a = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/E-321 Sensibilidad cepas vivas coccidia 13-07-2020.xlsx", "Performance cages")
E321b = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/E-321 Sensibilidad cepas vivas coccidia 13-07-2020.xlsx", "Performance Data")

In [329]:
E321a["ProjectID"] = 'E321'
E321b["ProjectID"] = 'E321'

In [330]:
print(list(E321b.columns))
E321b.head()

['House', 'Line', 'Pen', 'Blind Trts ', '# Ini birds 1d', 'Group BW1 (g)', 'BW1/A (g)', 'Mortality wk0-7d', 'Mortality weight 0-7d (g)', 'Culling 0-7d', 'Culling weight 0-7d (g)', 'Total Mort. + cull 0-7d (g)', '# Fnl birds 7d', 'Offered feed 1d (g)', 'Leftover feed 7d (g)', 'Container weight (g)', 'Container + birds weight (g)', 'Group BW7(g)', 'BW7 /A (g)', 'Group FI 0-7d (g)', 'FI 0-7d /A (g)', 'Group BWG 0-7d (g)', 'BWG 0-7d /A (g)', 'Group BWG 0-7d corrected  (g)', 'BWG 0-7d /A corrected (g)', 'FCR 0-7d (g:g)', 'FCR 0-7d corrected (g:g)', 'BW culling den. adj.7d (g)', 'Group BW7 den. adj. (g)', 'BW7/A den. adj. (g)', 'Wk2   (8-14d)', 'Offered feed 8d (g)', 'Leftover feed 12d (g)', '# Ini birds 8d', 'Mortality 8-12d', 'Mortality weight 8-12d (g)', 'Culling 8-12d', 'Culling weight 8-12d (g)', 'Total Mort. + cull 8-12d (g)', '# Fnl birds 12d', 'Container weight (g).1', 'Container + birds weight (g).1', 'Group BW12(g)', 'BW12 /A (g)', 'Group FI 8-12d (g)', 'FI 8-12d /A (g)', 'Group BWG 8-12d (g)', 'BWG 8-12d /A (g)', 'Group BWG 8-12d corrected (g)', 'BWG 8-12d /A corrected (g) ', 'FCR 8-12d (g:g)', 'FCR 8-12d corrected (g:g) ', 'Wk3  (15-21d)', 'Offered feed wk3 (g)', 'Adition feed wk3 (g)', 'Leftover feed wk3 (g)', '# Ini birds wk3', 'Mortality wk3', 'Mortality weight wk3 (g)', 'Culling wk3', 'Culling weight wk3 (g)', 'Total Mort. + cull 15-21d (g)', '# Fnl birds wk3', 'Container weight (g).2', 'Container + birds weight (g).2', 'Group BW21 (g)', 'BW21 /A (g)', 'Group FI 15-21d (g)', 'FI 15-21d /A (g)', 'Group BWG 15-21d (g)', 'BWG 15-21d /A (g)', 'Group BWG 15-21d /A corrected (g) ', 'BWG 15-21d /A corrected (g) ', 'FCR 15-21 (g:g)', 'FCR 15-21d corrected (g:g) ', 'Wk4  (22-28d)', 'Offered feed wk4 (g)', 'Adition feed wk4 (g)', 'Leftover feed wk4 (g)', '# Ini birds wk4', 'Mortality wk4', 'Mortality weight wk4 (g)', 'Culling wk4', 'Culling weight wk4 (g)', 'Total Mort. + cull 22-28d (g)', '# Fnl birds wk4', 'Container weight (g).3', 'Container + birds weight (g).3', 'Group BW28(g)', 'BW28 /A (g)', 'Group FI 22-28d (g)', 'FI 22-28d /A (g)', 'Group BWG 22-28d (g)', 'BWG 22-28d /A (g)', 'Group BWG 22-28d corrected(g)', 'BWG 22-28d /A corrected (g)', 'FCR 22-28d (g:g)', 'FCR22-28 corrected (g:g)', 'Wk5   (29-35d)', 'Offered feed wk5 (g)', 'Adition feed wk5 (g)', 'Leftover feed wk5 (g)', '# Ini birds wk5', 'Mortality wk5', 'Mortality weight wk5 (g)', 'Culling wk5', 'Culling weight wk5 (g)', 'Total Mort. + cull 29-35d (g)', '# Fnl birds wk5', 'Container weight (g).4', 'Container + birds weight (g).4', 'Group BW31 (g)', 'BW35 /A (g)', 'Group FI 29-35 (g)', 'FI 29-35d /A (g)', 'Group BWG 29-35d (g)', 'BWG 29-35d /A (g)', 'Group BWG 29-35d corrected (g)', 'BWG 29-35d /A corrected (g) ', 'FCR 29-35d (g:g)', 'FCR 29-35d corrected (g:g) ', 'Wk6   (36-42d)', 'Offered feed wk6 (g)', 'Adition feed wk6 (g)', 'Leftover feed wk6 (g)', '# Ini birds wk6', 'Mortality wk6', 'Mortality weight wk6 (g)', 'Culling wk6', 'Culling weight wk6 (g)', 'Total Mort. + cull 36-42d (g)', '# Fnl birds wk6', 'Container weight (g).5', 'Container + birds weight (g).5', 'Group BW42 (g)', 'BW42 /A (g)', 'Group FI 36-42d (g)', 'FI 36-42d /A (g)', 'Group BWG 36-42d (g)', 'BWG 36-42d /A (g)', 'Group BWG 36-42d corrected (g)', 'BWG 36-42d /A corrected (g)', 'FCR 36-42d (g:g)', 'FCR 36-42d corrected (g:g)', 'ProjectID']

,House,Line,Pen,Blind Trts,# Ini birds 1d,Group BW1 (g),BW1/A (g),Mortality wk0-7d,Mortality weight 0-7d (g),Culling 0-7d,...,BW42 /A (g),Group FI 36-42d (g),FI 36-42d /A (g),Group BWG 36-42d (g),BWG 36-42d /A (g),Group BWG 36-42d corrected (g),BWG 36-42d /A corrected (g),FCR 36-42d (g:g),FCR 36-42d corrected (g:g),ProjectID
0,1,A,1,NaN,25,1069.0,42.76,0,0,1,...,0,0,0,0,0,0,0,#DIV/0!,#DIV/0!,E321
1,1,A,2,NaN,25,1071.0,42.84,0,0,0,...,0,0,0,0,0,0,0,#DIV/0!,#DIV/0!,E321
2,1,A,3,NaN,25,1084.0,43.36,0,0,0,...,0,0,0,0,0,0,0,#DIV/0!,#DIV/0!,E321
3,1,A,4,NaN,25,1095.0,43.80,0,0,1,...,0,0,0,0,0,0,0,#DIV/0!,#DIV/0!,E321
4,1,A,5,NaN,25,1084.0,43.36,0,0,0,...,0,0,0,0,0,0,0,#DIV/0!,#DIV/0!,E321

In [331]:
E321b[[i for i in E321b.columns if "Group FI" in i]].columns

Index(['Group FI 0-7d (g)', 'Group FI 8-12d (g)', 'Group FI 15-21d (g)',
       'Group FI 22-28d (g)', 'Group FI 29-35 (g)', 'Group FI 36-42d (g)'],
      dtype='object')

In [332]:
E321b = E321b[['ProjectID', 'House', 'Pen', 'Blind Trts ','# Ini birds 1d',

             
             'Mortality wk0-7d', 'Mortality weight 0-7d (g)', 
             
             'Culling 0-7d', 'Culling weight 0-7d (g)',

             'Group BW1 (g)', 'Group BW7(g)',
               
               'Group FI 0-7d (g)'
               
               
             ]]
E321b.head()

,ProjectID,House,Pen,Blind Trts,# Ini birds 1d,Mortality wk0-7d,Mortality weight 0-7d (g),Culling 0-7d,Culling weight 0-7d (g),Group BW1 (g),Group BW7(g),Group FI 0-7d (g)
0,E321,1,1,NaN,25,0,0,1,37,1069.0,4007,3430
1,E321,1,2,NaN,25,0,0,0,0,1071.0,4103,3630
2,E321,1,3,NaN,25,0,0,0,0,1084.0,3998,3630
3,E321,1,4,NaN,25,0,0,1,94,1095.0,3972,3480
4,E321,1,5,NaN,25,0,0,0,0,1084.0,4379,3660

In [333]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Blind Trts ': 'Treatment',
    '# Ini birds 1d':'Init_Birds_D1',
    'Mortality wk0-7d': 'Fnl_Birds_D42',
    'Mortality weight 0-7d (g)': 'Cull_D42',
    'Culling 0-7d':'Mort_D42', 
    'Culling weight 0-7d (g)': 'Mort_Cull_Wt_D42',
    'Group BW1 (g)': 'GBW_initial',
    'Group BW7(g)': 'GBW_7',
    'Group FI 0-7d (g)':'GFI_D7'
}

E321b.rename(columns=column_rename_map, inplace=True)
E321b.head()

,ProjectID,House,Pen,Treatment,Init_Birds_D1,Fnl_Birds_D42,Cull_D42,Mort_D42,Mort_Cull_Wt_D42,GBW_initial,GBW_7,GFI_D7
0,E321,1,1,NaN,25,0,0,1,37,1069.0,4007,3430
1,E321,1,2,NaN,25,0,0,0,0,1071.0,4103,3630
2,E321,1,3,NaN,25,0,0,0,0,1084.0,3998,3630
3,E321,1,4,NaN,25,0,0,1,94,1095.0,3972,3480
4,E321,1,5,NaN,25,0,0,0,0,1084.0,4379,3660

In [334]:
E321a.head()
print(list(E321a.columns))

['Battery', 'Floor', 'Cage', 'Trts ', '# Ini birds Blck 1', 'Group BW12 (g)', 'BW12/A (g)', 'Mortality 13-21d', 'Mortality weight  13-14d (g)', 'Culling 13-14d', 'Culling weight 13-14d (g)', 'Total Mort. + cull 13-14d(g)', '# Fnl birds 13-14d', 'Offered feed 12-13d (g)', 'Leftover feed 14d (g)', 'Container weight (g)', 'Container + birds weight (g)', 'Group BW14(g)', 'BW14 /A (g)', 'Group FI 13-14d (g)', 'FI 13-14d /A (g)', 'Group BWG 13-14d (g)', 'BWG 13-14d /A (g)', 'Group BWG 13-14d corrected  (g)', 'BWG 13-14d /A corrected (g)', 'FCR 13-14d (g:g)', 'FCR 13-14d corrected (g:g)', 'Mortality 15-21d', 'Mortality weight  15-21d (g)', 'Culling 15-21d', 'Culling weight 15-21d (g)', 'Total Mort. + cull 15-21d(g)', '# Fnl birds 21d', 'Offered feed 15-19d (g)', 'Leftover feed 21d (g)', 'Container weight (g).1', 'Container + birds weight (g).1', 'Group BW21(g)', 'BW21 /A (g)', 'Group FI 15-21d (g)', 'FI 15-21d /A (g)', 'Group BWG 15-21d (g)', 'BWG 15-21d /A (g)', 'Group BWG 15-21d corrected  (g)', 'BWG 15-21d /A corrected (g)', 'FCR 15-21d (g:g)', 'FCR 15-21d corrected (g:g)', 'Mortality 22-24d', 'Mortality weight  22-24d (g)', 'Culling 22-24d', 'Culling weight 22-24d (g)', 'Total Mort. + cull 22-24d(g)', '# Fnl birds 24d', 'Offered feed 22-24d (g)', 'Leftover feed 24d (g)', 'Group BW24(g)', 'BW24 /A (g)', 'Group FI 22-24d (g)', 'FI 22-24d /A (g)', 'Group BWG 22-24d (g)', 'BWG 22-24d /A (g)', 'Group BWG 22-24d corrected  (g)', 'BWG 22-24d /A corrected (g)', 'FCR 22-24d (g:g)', 'FCR 22-24d corrected (g:g)', 'ProjectID']

In [335]:
E321a[[i for i in E321a.columns if "Mortality" in i]].columns

Index(['Mortality 13-21d', 'Mortality weight  13-14d (g)', 'Mortality 15-21d',
       'Mortality weight  15-21d (g)', 'Mortality 22-24d',
       'Mortality weight  22-24d (g)'],
      dtype='object')

In [337]:
E321a = E321a[['ProjectID', 'Battery', 'Cage', 'Trts ','# Ini birds Blck 1',


               '# Fnl birds 13-14d', '# Fnl birds 21d', '# Fnl birds 24d',


               
               'Mortality weight  13-14d (g)', 'Mortality weight  15-21d (g)', 'Mortality weight  22-24d (g)',
               
               'Culling 13-14d', 'Culling weight 13-14d (g)', 'Culling 15-21d',
               'Culling weight 15-21d (g)', 'Culling 22-24d',
               'Culling weight 22-24d (g)',
               
               'Group BW12 (g)', 'Group BW14(g)', 'Group BW21(g)', 'Group BW24(g)',

               'Group FI 13-14d (g)', 'Group FI 15-21d (g)', 'Group FI 22-24d (g)'
               
               
             ]]
E321a.head()

,ProjectID,Battery,Cage,Trts,# Ini birds Blck 1,# Fnl birds 13-14d,# Fnl birds 21d,# Fnl birds 24d,Mortality weight 13-14d (g),Mortality weight 15-21d (g),...,Culling weight 15-21d (g),Culling 22-24d,Culling weight 22-24d (g),Group BW12 (g),Group BW14(g),Group BW21(g),Group BW24(g),Group FI 13-14d (g),Group FI 15-21d (g),Group FI 22-24d (g)
0,E321,1,1,2,12,12,11,10,NaN,NaN,...,388,1,855,3804,4684,9520,11470,1039,6726,3769
1,E321,1,2,2,12,12,11,10,NaN,NaN,...,397,1,927,3808,4606,9500,11440,1016,6659,3752
2,E321,1,3,1,12,12,11,10,NaN,NaN,...,363,1,826,3798,4695,8820,10590,1191,6058,3704
3,E321,1,4,5,12,12,11,10,NaN,NaN,...,412,1,664,3815,4674,8960,10900,1148,6552,3623
4,E321,1,5,3,12,12,11,10,NaN,NaN,...,333,1,829,3823,4750,9180,10780,1166,6439,3581

In [275]:
E321a.columns

Index(['ProjectID', 'Battery', 'Cage', 'Trts ', '# Ini birds Blck 1',
       '# Fnl birds 13-14d', '# Fnl birds 21d', '# Fnl birds 24d',
       'Mortality weight  13-14d (g)', 'Mortality weight  15-21d (g)',
       'Mortality weight  22-24d (g)', 'Culling 13-14d',
       'Culling weight 13-14d (g)', 'Culling 15-21d',
       'Culling weight 15-21d (g)', 'Culling 22-24d',
       'Culling weight 22-24d (g)', 'Group BW12 (g)', 'Group BW14(g)',
       'Group BW21(g)', 'Group BW24(g)'],
      dtype='object')

In [338]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Battery': 'House',
    'Cage': 'Pen',
    'Trts ': 'Treatment',
    '# Ini birds Blck 1':'Init_Birds_D12', 

    '# Fnl birds 13-14d':'Fnl_Birds_D14',
    '# Fnl birds 21d':'Fnl_Birds_D21',
    '# Fnl birds 24d':'Fnl_Birds_D24',
    
    'Mortality 13-21d':'Fnl_Birds_D7',
    'Mortality 15-21d':'Mort_15_D21',
    'Mortality 22-24d':'Mort_22_D24',
    
    'Mortality weight  13-14d (g)':'Mort_Wt_D14',
    'Mortality weight  15-21d (g)':'Mort_Wt_D21',
    'Mortality weight  22-24d (g)': 'Mort_Wt_D24',
    
    'Culling weight 13-14d (g)':'Cull_Wt_D14',
    'Culling weight 15-21d (g)':'Cull_Wt_D21', 
    'Culling weight 22-24d (g)':'Cull_Wt_D24',
    
    'Culling 13-14d':'Cull_D14',
    'Culling 15-21d':'Cull_D21',
    'Culling 22-24d':'Cull_D24',
    
    'Group BW12 (g)':'GBW_12',
    'Group BW14(g)':'GBW_14',
    'Group BW21(g)':'GBW_21',
    'Group BW24(g)':'GBW_24',

    'Group FI 13-14d (g)':'GFI_0_D14', 
    'Group FI 15-21d (g)':'GFI_D21', 
    'Group FI 22-24d (g)':'GFI_D24'
}

E321a.rename(columns=column_rename_map, inplace=True)
E321a.head()

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_5804/3719540405.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  E321a.rename(columns=column_rename_map, inplace=True)

,ProjectID,House,Pen,Treatment,Init_Birds_D12,Fnl_Birds_D14,Fnl_Birds_D21,Fnl_Birds_D24,Mort_Wt_D14,Mort_Wt_D21,...,Cull_Wt_D21,Cull_D24,Cull_Wt_D24,GBW_12,GBW_14,GBW_21,GBW_24,GFI_0_D14,GFI_D21,GFI_D24
0,E321,1,1,2,12,12,11,10,NaN,NaN,...,388,1,855,3804,4684,9520,11470,1039,6726,3769
1,E321,1,2,2,12,12,11,10,NaN,NaN,...,397,1,927,3808,4606,9500,11440,1016,6659,3752
2,E321,1,3,1,12,12,11,10,NaN,NaN,...,363,1,826,3798,4695,8820,10590,1191,6058,3704
3,E321,1,4,5,12,12,11,10,NaN,NaN,...,412,1,664,3815,4674,8960,10900,1148,6552,3623
4,E321,1,5,3,12,12,11,10,NaN,NaN,...,333,1,829,3823,4750,9180,10780,1166,6439,3581

In [339]:
E321a.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE321a.csv', index=False)  
E321b.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE321b.csv', index=False)

# E325

In [373]:
E325 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/E-325 Promotores vs Alura Natural solutions 30-09-2020.xlsx", "Performance Data")

In [374]:
E325["ProjectID"] = 'E325'

In [376]:
print(list(E325.columns))
E325.head()

['House', 'Line', 'Pen', 'Blind Trts ', '# Ini birds 1d', 'Group BW1 (g)', 'BW1/A (g)', 'Mortality wk0-7d', 'Mortality weight 0-7d (g)', 'Culling 0-7d', 'Culling weight 0-7d (g)', 'Total Mort. + cull 0-7d (g)', '# Fnl birds 7d', 'Offered feed 1d (g)', 'Leftover feed 7d (g)', 'Container weight (g)', 'Container + birds weight (g)', 'Group BW7(g)', 'BW7 /A (g)', 'Group FI 0-7d (g)', 'FI 0-7d /A (g)', 'Group BWG 0-7d (g)', 'BWG 0-7d /A (g)', 'Group BWG 0-7d corrected  (g)', 'BWG 0-7d /A corrected (g)', 'FCR 0-7d (g:g)', 'FCR 0-7d corrected (g:g)', 'Mortality (%)', 'Culling (%)', 'Mort.+Cull 0-7 d (%)', 'Wk2   (8-14d)', 'Offered feed 8d (g)', 'Leftover feed 14d (g)', '# Ini birds 8d', 'Mortality 8-14d', 'Mortality weight 8-14d (g)', 'Culling 8-14d', 'Culling weight 8-14d (g)', 'Total Mort. + cull 8-14d (g)', '# Fnl birds 14d', 'Container weight (g).1', 'Container + birds weight (g).1', 'Group BW14(g)', 'BW14 /A (g)', 'Group FI 8-14d (g)', 'FI 8-14d /A (g)', 'Group BWG 8-14d (g)', 'BWG 8-14d /A (g)', 'Group BWG 8-14d corrected (g)', 'BWG 8-14d /A corrected (g) ', 'FCR 8-14d (g:g)', 'FCR 8-14d corrected (g:g) ', 'Wk3  (15-21d)', 'Offered feed wk3 (g)', 'Adition feed wk3 (g)', 'Leftover feed wk3 (g)', '# Ini birds wk3', 'Mortality wk3', 'Mortality weight wk3 (g)', 'Culling wk3', 'Culling weight wk3 (g)', 'Total Mort. + cull 15-21d (g)', '# Fnl birds wk3', 'Container weight (g).2', 'Container + birds weight (g).2', 'Group BW21 (g)', 'BW21 /A (g)', 'Group FI 15-21d (g)', 'FI 15-21d /A (g)', 'Group BWG 15-21d (g)', 'BWG 15-21d /A (g)', 'Group BWG 15-21d /A corrected (g) ', 'BWG 15-21d /A corrected (g) ', 'FCR 15-21 (g:g)', 'FCR 15-21d corrected (g:g) ', 'Wk4  (22-28d)', 'Offered feed wk4 (g)', 'Adition feed wk4 (g)', 'Leftover feed wk4 (g)', '# Ini birds wk4', 'Mortality wk4', 'Mortality weight wk4 (g)', 'Culling wk4', 'Culling weight wk4 (g)', 'Total Mort. + cull 22-28d (g)', '# Fnl birds wk4', 'Container weight (g).3', 'Container + birds weight (g).3', 'Group BW28(g)', 'BW28 /A (g)', 'Group FI 22-28d (g)', 'FI 22-28d /A (g)', 'Group BWG 22-28d (g)', 'BWG 22-28d /A (g)', 'Group BWG 22-28d corrected(g)', 'BWG 22-28d /A corrected (g)', 'FCR 22-28d (g:g)', 'FCR22-28 corrected (g:g)', 'Wk5   (29-35d)', 'Offered feed wk5 (g)', 'Adition feed wk5 (g)', 'Leftover feed wk5 (g)', '# Ini birds wk5', 'Mortality wk5', 'Mortality weight wk5 (g)', 'Culling wk5', 'Culling weight wk5 (g)', 'Total Mort. + cull 29-35d (g)', '# Fnl birds wk5', 'Container weight (g).4', 'Container + birds weight (g).4', 'Group BW31 (g)', 'BW35 /A (g)', 'Group FI 29-35 (g)', 'FI 29-35d /A (g)', 'Group BWG 29-35d (g)', 'BWG 29-35d /A (g)', 'Group BWG 29-35d corrected (g)', 'BWG 29-35d /A corrected (g) ', 'FCR 29-35d (g:g)', 'FCR 29-35d corrected (g:g) ', 'Wk6   (36-42d)', 'Offered feed wk6 (g)', 'Adition feed wk6 (g)', 'Leftover feed wk6 (g)', '# Ini birds wk6', 'Mortality wk6', 'Mortality weight wk6 (g)', 'Culling wk6', 'Culling weight wk6 (g)', 'Total Mort. + cull 36-42d (g)', '# Fnl birds wk6', 'Container weight (g).5', 'Container + birds weight (g).5', 'Group BW42 (g)', 'BW42 /A (g)', 'Group FI 36-42d (g)', 'FI 36-42d /A (g)', 'Group BWG 36-42d (g)', 'BWG 36-42d /A (g)', 'Group BWG 36-42d corrected (g)', 'BWG 36-42d /A corrected (g)', 'FCR 36-42d (g:g)', 'FCR 36-42d corrected (g:g)', 'ProjectID']

,House,Line,Pen,Blind Trts,# Ini birds 1d,Group BW1 (g),BW1/A (g),Mortality wk0-7d,Mortality weight 0-7d (g),Culling 0-7d,...,BW42 /A (g),Group FI 36-42d (g),FI 36-42d /A (g),Group BWG 36-42d (g),BWG 36-42d /A (g),Group BWG 36-42d corrected (g),BWG 36-42d /A corrected (g),FCR 36-42d (g:g),FCR 36-42d corrected (g:g),ProjectID
0,1,A,1,6,30,1270,42.333333,0,0,0,...,0,15820,545.517241,-62920,-2169.655172,-62920,-2169.655172,-0.251430,-0.251430,E325
1,1,A,2,11,30,1254,41.800000,0,0,0,...,0,17690,631.785714,-58614,-2093.357143,-58614,-2093.357143,-0.301805,-0.301805,E325
2,1,A,3,2,30,1251,41.700000,0,0,0,...,0,19460,671.034483,-62810,-2165.862069,-62810,-2165.862069,-0.309823,-0.309823,E325
3,1,A,4,9,30,1247,41.566667,0,0,1,...,0,21920,782.857143,-59020,-2107.857143,-59020,-2107.857143,-0.371400,-0.371400,E325
4,1,A,5,7,30,1254,41.800000,0,0,0,...,0,14700,490.000000,-61950,-2065.000000,-61950,-2065.000000,-0.237288,-0.237288,E325

In [386]:
E325[[i for i in E325.columns if "Group FI" in i]].columns

Index(['Group FI 0-7d (g)', 'Group FI 8-14d (g)', 'Group FI 15-21d (g)',
       'Group FI 22-28d (g)', 'Group FI 29-35 (g)', 'Group FI 36-42d (g)'],
      dtype='object')

In [387]:
E325 = E325[['ProjectID', 'House', 'Pen', 'Blind Trts ', '# Ini birds 1d',
             
             'Group BW1 (g)', 'Group BW7(g)', 'Group BW14(g)', 'Group BW21 (g)', 'Group BW28(g)', 'Group BW31 (g)', 'Group BW42 (g)',
             
             
             '# Fnl birds 7d', '# Fnl birds 14d', '# Fnl birds wk3',
             '# Fnl birds wk4', '# Fnl birds wk5', '# Fnl birds wk6',

              
               
             'Mortality weight 0-7d (g)', 'Mortality weight 8-14d (g)', 
             'Mortality weight wk3 (g)', 'Mortality weight wk4 (g)',
             'Mortality weight wk5 (g)', 'Mortality weight wk6 (g)',
             
             'Culling weight 0-7d (g)', 'Culling weight 8-14d (g)',
             'Culling weight wk3 (g)', 'Culling weight wk4 (g)',
             'Culling weight wk5 (g)', 'Culling weight wk6 (g)',

             'Culling 0-7d', 'Culling 8-14d', 'Culling wk3', 
             'Culling wk4', 'Culling wk5','Culling wk6',

               

             'Group FI 0-7d (g)', 'Group FI 8-14d (g)', 'Group FI 15-21d (g)',
             'Group FI 22-28d (g)', 'Group FI 29-35 (g)', 'Group FI 36-42d (g)'
               
               
               
             ]]
E325.head()

,ProjectID,House,Pen,Blind Trts,# Ini birds 1d,Group BW1 (g),Group BW7(g),Group BW14(g),Group BW21 (g),Group BW28(g),...,Culling wk3,Culling wk4,Culling wk5,Culling wk6,Group FI 0-7d (g),Group FI 8-14d (g),Group FI 15-21d (g),Group FI 22-28d (g),Group FI 29-35 (g),Group FI 36-42d (g)
0,E325,1,1,6,30,1270,5672,12560,27860,45920,...,0,0,1,0,5360,9620,20280,27210,30690,15820
1,E325,1,2,11,30,1254,5870,12900,27700,45160,...,0,0,0,0,5460,9340,20030,26300,28200,17690
2,E325,1,3,2,30,1251,5764,12780,27310,44510,...,0,0,0,0,5220,8980,19650,25900,30140,19460
3,E325,1,4,9,30,1247,5473,12120,25630,40920,...,0,0,0,0,5380,9140,19150,24880,28480,21920
4,E325,1,5,7,30,1254,5658,12260,26660,42830,...,0,0,0,0,5300,8880,19560,26250,30530,14700

In [388]:
E325.columns

Index(['ProjectID', 'House', 'Pen', 'Blind Trts ', '# Ini birds 1d',
       'Group BW1 (g)', 'Group BW7(g)', 'Group BW14(g)', 'Group BW21 (g)',
       'Group BW28(g)', 'Group BW31 (g)', 'Group BW42 (g)', '# Fnl birds 7d',
       '# Fnl birds 14d', '# Fnl birds wk3', '# Fnl birds wk4',
       '# Fnl birds wk5', '# Fnl birds wk6', 'Mortality weight 0-7d (g)',
       'Mortality weight 8-14d (g)', 'Mortality weight wk3 (g)',
       'Mortality weight wk4 (g)', 'Mortality weight wk5 (g)',
       'Mortality weight wk6 (g)', 'Culling weight 0-7d (g)',
       'Culling weight 8-14d (g)', 'Culling weight wk3 (g)',
       'Culling weight wk4 (g)', 'Culling weight wk5 (g)',
       'Culling weight wk6 (g)', 'Culling 0-7d', 'Culling 8-14d',
       'Culling wk3', 'Culling wk4', 'Culling wk5', 'Culling wk6',
       'Group FI 0-7d (g)', 'Group FI 8-14d (g)', 'Group FI 15-21d (g)',
       'Group FI 22-28d (g)', 'Group FI 29-35 (g)', 'Group FI 36-42d (g)'],
      dtype='object')

In [390]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Blind Trts ': 'TreatmentNumber',
    '# Ini birds 1d':'Init_Birds_D1', 



    'Group BW1 (g)':'GBW_initial', 
    'Group BW7(g)':'GBW_D7', 
    'Group BW14(g)':'GBW_D14', 
    'Group BW21 (g)':'GBW_D21',
    'Group BW28(g)':'GBW_D28', 
    'Group BW31 (g)':'GBW_D35', 
    'Group BW42 (g)':'GBW_D42', 
    
    
    '# Fnl birds 7d':'Fnl_Birds_D7',
    '# Fnl birds 14d':'Fnl_Birds_D14', 
    '# Fnl birds wk3':'Fnl_Birds_D21', 
    '# Fnl birds wk4':'Fnl_Birds_D28',
    '# Fnl birds wk5':'Fnl_Birds_D35', 
    '# Fnl birds wk6':'Fnl_Birds_D42', 
    
    
    'Mortality weight 0-7d (g)':'Mort_Wt_D7',
    'Mortality weight 8-14d (g)':'Mort_Wt_D14', 
    'Mortality weight wk3 (g)':'Mort_Wt_D21',
    'Mortality weight wk4 (g)':'Mort_Wt_D28', 
    'Mortality weight wk5 (g)':'Mort_Wt_D35',
    'Mortality weight wk6 (g)':'Mort_Wt_D42',

    
    'Culling weight 0-7d (g)':'Cull_Wt_D7',
    'Culling weight 8-14d (g)':'Cull_Wt_D14', 
    'Culling weight wk3 (g)':'Cull_Wt_D21',
    'Culling weight wk4 (g)':'Cull_Wt_D28', 
    'Culling weight wk5 (g)':'Cull_Wt_D35',
    'Culling weight wk6 (g)':'Cull_Wt_D42', 

    
    'Culling 0-7d':'Cull_D7', 
    'Culling 8-14d':'Cull_D14',
    'Culling wk3':'Cull_D21', 
    'Culling wk4':'Cull_D28', 
    'Culling wk5':'Cull_D35', 
    'Culling wk6':'Cull_D42',

    
    'Group FI 0-7d (g)':'GFI_D7', 
    'Group FI 8-14d (g)':'GFI_D14', 
    'Group FI 15-21d (g)':'GFI_D21',
    'Group FI 22-28d (g)':'GFI_D28', 
    'Group FI 29-35 (g)':'GFI_D35', 
    'Group FI 36-42d (g)':'GFI_D42'
    
}

E325.rename(columns=column_rename_map, inplace=True)
E325.head()

,ProjectID,House,Pen,TreatmentNumber,Init_Birds_D1,GBW_initial,GBW_D7,GBW_D14,GBW_D21,GBW_D28,...,Cull_D21,Cull_D28,Cull_D35,Cull_D42,GFI_D7,GFI_D14,GFI_D21,GFI_D28,GFI_D35,GFI_D42
0,E325,1,1,6,30,1270,5672,12560,27860,45920,...,0,0,1,0,5360,9620,20280,27210,30690,15820
1,E325,1,2,11,30,1254,5870,12900,27700,45160,...,0,0,0,0,5460,9340,20030,26300,28200,17690
2,E325,1,3,2,30,1251,5764,12780,27310,44510,...,0,0,0,0,5220,8980,19650,25900,30140,19460
3,E325,1,4,9,30,1247,5473,12120,25630,40920,...,0,0,0,0,5380,9140,19150,24880,28480,21920
4,E325,1,5,7,30,1254,5658,12260,26660,42830,...,0,0,0,0,5300,8880,19560,26250,30530,14700

In [391]:
E325.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE325.csv', index=False)

# E326

In [365]:
E326 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/E-326 Sensibilidad cepas vivas coccidia 24-02-2021.xlsx", "Performance cages")

In [366]:
E326["ProjectID"] = 'E326'

In [367]:
E326["ProjectID"] = 'E326'
print(list(E326.columns))
E326.head()

['Battery', 'Floor', 'Cage', 'Trts ', '# Ini birds Blck 1', 'Group BW12 (g)', 'BW12/A (g)', 'Mortality 13-14d', 'Mortality weight  13-14d (g)', 'Culling 13-14d', 'Culling weight 13-14d (g)', 'Total Mort. + cull 13-14d(g)', '# Fnl birds 13-14d', 'Offered feed 12-13d (g)', 'Leftover feed 14d (g)', 'Container weight (g)', 'Container + birds weight (g)', 'Group BW14(g)', 'BW14 /A (g)', 'Group FI 13-14d (g)', 'FI 13-14d /A (g)', 'Group BWG 13-14d (g)', 'BWG 13-14d /A (g)', 'Group BWG 13-14d corrected  (g)', 'BWG 13-14d /A corrected (g)', 'FCR 13-14d (g:g)', 'FCR 13-14d corrected (g:g)', 'Mortality 15-20d', 'Mortality weight  15-20d (g)', 'Culling 15-20d', 'Culling weight 15-20d (g)', 'Mortality 21d', 'Mortality weight 21d (g)', 'Culling 21d ', 'Culling weight 21d (g)', 'Sampling 21d', 'sampling weight 21d', 'Total Mort. + cull 15-21d(g)', '# Fnl birds 21d', 'Offered feed 15-21d (g)', 'Leftover feed 21d (g)', 'Container weight (g).1', 'Container + birds weight (g).1', 'Group BW21(g)', 'BW21 /A (g)', 'Group FI 15-21d (g)', 'FI 15-21d /A (g)', 'Group BWG 15-21d (g)', 'BWG 15-21d /A (g)', 'Group BWG 15-21d corrected  (g)', 'BWG 15-21d /A corrected (g)', 'FCR 15-21d (g:g)', 'FCR 15-21d corrected (g:g)', 'Mortality 22-27d', 'Mortality weight  22-27d (g)', 'Culling 22-27d', 'Culling weight 22-27d (g)', 'Mortality 28d', 'Mortality weight 28d (g)', 'Culling 28d', 'Culling weight 28d (g)', 'Samplig 28d', 'weight Sampling 28d', 'Total Mort. + cull 22-28d(g)', '# Fnl birds 28d', 'Offered feed 22-28d (g)', 'Leftover feed 28d (g)', 'Group BW28(g)', 'BW28 /A (g)', 'Group FI 22-28d (g)', 'FI 22-28d /A (g)', 'Group BWG 22-28d (g)', 'BWG 22-28d /A (g)', 'Group BWG 22-28d corrected  (g)', 'BWG 22-28d /A corrected (g)', 'FCR 22-28d (g:g)', 'FCR 22-28d corrected (g:g)', 'Mortality 29-35d', 'Mortality weight  29-35d (g)', 'Culling 29-35d', 'Culling weight 29-35d (g)', 'Total Mort. + cull 29-35d(g)', '# Fnl birds 35d', 'Offered feed 29-35d (g)', 'Leftover feed 35d (g)', 'Group BW35(g)', 'BW35 /A (g)', 'Group FI 29-35d (g)', 'FI 29-35d /A (g)', 'Group BWG 29-35d (g)', 'BWG 29-35d /A (g)', 'Group BWG 29-35d corrected  (g)', 'BWG 29-35d /A corrected (g)', 'FCR 29-35d (g:g)', 'FCR 29-35d corrected (g:g)', 'ProjectID']

,Battery,Floor,Cage,Trts,# Ini birds Blck 1,Group BW12 (g),BW12/A (g),Mortality 13-14d,Mortality weight 13-14d (g),Culling 13-14d,...,BW35 /A (g),Group FI 29-35d (g),FI 29-35d /A (g),Group BWG 29-35d (g),BWG 29-35d /A (g),Group BWG 29-35d corrected (g),BWG 29-35d /A corrected (g),FCR 29-35d (g:g),FCR 29-35d corrected (g:g),ProjectID
0,1,5,1,2,12,4290,357.500000,NaN,NaN,NaN,...,2237.777778,9129,1014.333333,5645,627.222222,5645,627.222222,1.617183,1.617183,E326
1,1,5,2,6,12,4260,355.000000,NaN,NaN,NaN,...,2012.500000,7995,999.375000,5153,644.125000,5153,644.125000,1.551523,1.551523,E326
2,1,4,3,1,12,4320,360.000000,NaN,NaN,NaN,...,2270.000000,9645,1071.666667,6516,724.000000,6516,724.000000,1.480203,1.480203,E326
3,1,4,4,5,12,4280,356.666667,NaN,NaN,NaN,...,2227.500000,8663,1082.875000,5676,709.500000,5676,709.500000,1.526251,1.526251,E326
4,1,3,5,3,12,4330,360.833333,NaN,NaN,NaN,...,2148.888889,9924,1102.666667,6611,734.555556,6611,734.555556,1.501134,1.501134,E326

In [368]:
E326[[i for i in E326.columns if "Samplig" in i]].columns

Index(['Samplig 28d'], dtype='object')

In [369]:
E326 = E326[['ProjectID', 'Battery', 'Cage', 'Trts ','# Ini birds Blck 1',

               'Group BW12 (g)', 'Group BW14(g)', 'Group BW21(g)', 'Group BW28(g)', 'Group BW35(g)',


               '# Fnl birds 13-14d', '# Fnl birds 21d', '# Fnl birds 28d', '# Fnl birds 35d',

              'Sampling 21d', 'Samplig 28d',

             
               'sampling weight 21d', 'weight Sampling 28d',
             
               
               'Mortality weight  13-14d (g)', 'Mortality weight  15-20d (g)', 'Mortality weight 21d (g)', 
               'Mortality weight  22-27d (g)', 'Mortality weight 28d (g)', 'Mortality weight  29-35d (g)',
               
               'Culling weight 13-14d (g)', 'Culling weight 15-20d (g)',
               'Culling weight 21d (g)', 'Culling weight 22-27d (g)',
               'Culling weight 28d (g)', 'Culling weight 29-35d (g)',

               'Culling 13-14d','Culling 15-20d','Culling 21d ','Culling 22-27d','Culling 28d','Culling 29-35d',

             'Group FI 13-14d (g)', 'Group FI 15-21d (g)', 'Group FI 22-28d (g)', 'Group FI 29-35d (g)'
               
               
               
             ]]
E326.head()

,ProjectID,Battery,Cage,Trts,# Ini birds Blck 1,Group BW12 (g),Group BW14(g),Group BW21(g),Group BW28(g),Group BW35(g),...,Culling 13-14d,Culling 15-20d,Culling 21d,Culling 22-27d,Culling 28d,Culling 29-35d,Group FI 13-14d (g),Group FI 15-21d (g),Group FI 22-28d (g),Group FI 29-35d (g)
0,E326,1,1,2,12,4290,5110,11230,16170,20140,...,NaN,NaN,NaN,NaN,NaN,NaN,1101,7090,9485,9129
1,E326,1,2,6,12,4260,5040,8700,12450,16100,...,NaN,NaN,NaN,NaN,NaN,NaN,1054,6030,7884,7995
2,E326,1,3,1,12,4320,5280,10020,15100,20430,...,NaN,NaN,NaN,NaN,NaN,NaN,1206,6401,9180,9645
3,E326,1,4,5,12,4280,5080,8930,13480,17820,...,NaN,NaN,NaN,NaN,NaN,NaN,1091,6350,8460,8663
4,E326,1,5,3,12,4330,5240,9680,14090,19340,...,NaN,NaN,NaN,NaN,NaN,NaN,1184,6256,9053,9924

In [370]:
E326.columns

Index(['ProjectID', 'Battery', 'Cage', 'Trts ', '# Ini birds Blck 1',
       'Group BW12 (g)', 'Group BW14(g)', 'Group BW21(g)', 'Group BW28(g)',
       'Group BW35(g)', '# Fnl birds 13-14d', '# Fnl birds 21d',
       '# Fnl birds 28d', '# Fnl birds 35d', 'Sampling 21d', 'Samplig 28d',
       'sampling weight 21d', 'weight Sampling 28d',
       'Mortality weight  13-14d (g)', 'Mortality weight  15-20d (g)',
       'Mortality weight 21d (g)', 'Mortality weight  22-27d (g)',
       'Mortality weight 28d (g)', 'Mortality weight  29-35d (g)',
       'Culling weight 13-14d (g)', 'Culling weight 15-20d (g)',
       'Culling weight 21d (g)', 'Culling weight 22-27d (g)',
       'Culling weight 28d (g)', 'Culling weight 29-35d (g)', 'Culling 13-14d',
       'Culling 15-20d', 'Culling 21d ', 'Culling 22-27d', 'Culling 28d',
       'Culling 29-35d', 'Group FI 13-14d (g)', 'Group FI 15-21d (g)',
       'Group FI 22-28d (g)', 'Group FI 29-35d (g)'],
      dtype='object')

In [371]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Battery': 'House',
    'Cage': 'Pen',
    'Trts ': 'Treatment',
    '# Ini birds Blck 1':'Init_Birds_D12', 


    'Group BW12 (g)':'GBW_12',
    'Group BW14(g)':'GBW_14',
    'Group BW21(g)':'GBW_21',
    'Group BW28(g)':'GBW_28',
    'Group BW35(g)':'GBW_35',
    

    '# Fnl birds 13-14d':'Fnl_Birds_D14',
    '# Fnl birds 21d':'Fnl_Birds_D21',
    '# Fnl birds 28d':'Fnl_Birds_D24',
    '# Fnl birds 35d':'Fnl_Birds_D35',
    
    


    'Mortality weight  13-14d (g)':'Mort_Wt_D14',
    'Mortality weight  15-20d (g)': 'Mort_Wt_D20',
    'Mortality weight 21d (g)':'Mort_Wt_D21',
    'Mortality weight  22-27d (g)': 'Mort_Wt_D27',
    'Mortality weight 28d (g)':'Mort_Wt_D28',
    'Mortality weight  29-35d (g)': 'Mort_Wt_D35',

    

    'Culling weight 13-14d (g)':'Cull_Wt_D14',
    'Culling weight 15-20d (g)':'Cull_Wt_D20', 
    'Culling weight 21d (g)':'Cull_Wt_D21',
    'Culling weight 22-27d (g)':'Cull_Wt_D27', 
    'Culling weight 28d (g)':'Cull_Wt_D28',
    'Culling weight 29-35d (g)':'Cull_Wt_D35',


    'Culling 13-14d':'Cull_D14',
    'Culling 15-20d':'Cull_D20',
    'Culling 21d ':'Cull_D21',
    'Culling 22-27d':'Cull_D27',
    'Culling 28d':'Cull_D28',
    'Culling 29-35d':'Cull_D35',

    'Group FI 13-14d (g)':'GFI_D14', 
    'Group FI 15-21d (g)':'GFI_D21', 
    'Group FI 22-28d (g)':'GFI_D28', 
    'Group FI 29-35d (g)':'GFI_D35',


    'Sampling 21d':'Samp_D21', 
    'Samplig 28d':'Samp_D28',

             
     'sampling weight 21d':'Samp_Wt_D21', 
    'weight Sampling 28d':'Samp_Wt_D28',
    
   


    
}

E326.rename(columns=column_rename_map, inplace=True)
E326.head()

,ProjectID,House,Pen,Treatment,Init_Birds_D12,GBW_12,GBW_14,GBW_21,GBW_28,GBW_35,...,Cull_D14,Cull_D20,Cull_D21,Cull_D27,Cull_D28,Cull_D35,GFI_D14,GFI_D21,GFI_D28,GFI_D35
0,E326,1,1,2,12,4290,5110,11230,16170,20140,...,NaN,NaN,NaN,NaN,NaN,NaN,1101,7090,9485,9129
1,E326,1,2,6,12,4260,5040,8700,12450,16100,...,NaN,NaN,NaN,NaN,NaN,NaN,1054,6030,7884,7995
2,E326,1,3,1,12,4320,5280,10020,15100,20430,...,NaN,NaN,NaN,NaN,NaN,NaN,1206,6401,9180,9645
3,E326,1,4,5,12,4280,5080,8930,13480,17820,...,NaN,NaN,NaN,NaN,NaN,NaN,1091,6350,8460,8663
4,E326,1,5,3,12,4330,5240,9680,14090,19340,...,NaN,NaN,NaN,NaN,NaN,NaN,1184,6256,9053,9924

In [372]:
E326.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE326.csv', index=False)

# E335

In [411]:
E335 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/E-335 Performance_Datos Niveles de calcio y alpha D3 + MK7 26-12-2022.xlsx", "Performance Data")

In [412]:
E335["ProjectID"] = 'E335'
print(list(E335.columns))
E335.head()
E335['Group FI 29-33 (g)'] = E335['Group FI 22-33 (g)'] * E335['Group FI 22-28d (g)']

['House', 'Line', 'Pen', 'Blind Trts ', '# Ini birds 1d', 'Group BW1 (g)', 'BWhatch/A (g)', 'Mortality wk0-10d', 'Mortality weight 0-10d (g)', 'Culling 0-10d', 'Culling weight 0-10d (g)', 'Total Mort. + cull 0-10d (g)', 'Offered feed 1d (g)', 'Offered water 1d (g)', 'Water addition', 'Leftover feed 10d (g)', 'Leftover water 10d (g)', 'Container weight (g)', 'Container + birds weight (g)', '# Fnl birds 10d', 'Group BW10(g)', 'BW10 /A (g)', 'Group FI 0-10d (g)', 'FI 0-10d /A (g)', 'Group WC 0-10d (g)', 'WC 0-10d /A (g)', 'Group BWG 0-10d (g)', 'BWG 0-10d /A (g)', 'Group BWG 0-10d corrected  (g)', 'BWG 0-10d /A corrected (g)', 'FCR 0-10d (g:g)', 'FCR 0-10d corrected (g:g)', 'Mortality 0-10d (%)', 'Culling 0-10d (%)', 'Mort + Cull 0-10d (%)', 'Wk2   (11-14d)', 'Offered feed 11d (g)', 'Leftover feed 14d (g)', 'Water addition.1', 'Leftover water 14d (g)', '# Ini birds 11d', 'Mortality 8-14d', 'Mortality weight 11-14d (g)', 'Culling 11-14d', 'Culling weight 11-14d (g)', 'Total Mort. + cull 11-14d (g)', '# Fnl birds 14d', 'Container weight (g).1', 'Container + birds weight (g).1', 'Group BW14(g)', 'BW14 /A (g)', 'Group FI 11-14d (g)', 'FI 11-14d /A (g)', 'Group WC 11-14d (g)', 'WC 11-14d /A (g)', 'Group BWG 11-14d (g)', 'BWG 11-14d /A (g)', 'Group BWG 11-14d corrected (g)', 'BWG 11-14d /A corrected (g) ', 'FCR 11-14d (g:g)', 'FCR 11-14d corrected (g:g) ', 'Wk3  (15-21d)', 'Offered feed wk3 (g)', 'Adition feed wk3 (g)', 'Water Adition wk3 (g)', 'Water Adition 2 WK3 (g)', 'Leftover feed wk3 (g)', 'Leftover water WK3 (g)', '# Ini birds wk3', 'Mortality wk3', 'Mortality weight wk3 (g)', 'Culling wk3', 'Culling weight wk3 (g)', 'Total Mort. + cull 15-21d (g)', '# Fnl birds wk3', 'Container weight (g).2', 'Container + birds weight (g).2', 'Group BW21 (g)', 'BW21 /A (g)', 'Group FI 15-21d (g)', 'FI 15-21d /A (g)', 'Group WC 15-21d /A (g)', 'WC/ A 15-21d /A (g)', 'Group BWG 15-21d (g)', 'BWG 15-21d /A (g)', 'Group BWG 15-21d /A corrected (g) ', 'BWG 15-21d /A corrected (g) ', 'FCR 15-21 (g:g)', 'FCR 15-21d corrected (g:g) ', 'Mortality 11-21d (%)', 'Culling 11-21dd (%)', 'Mort + Cull 11-21d (%)', 'Wk4  (22-28d)', 'Offered feed wk4 (g)', 'Adition feed wk4 (g)', 'Leftover feed wk4 (g)', 'Water Adition WK 4 (07/05/21)', 'Water adition WK  4 (10/05/2021)', 'Water adition WK 4 (12/05/2021)', 'Leftover water wk4 (g)', '# Ini birds wk4', 'Mortality wk4', 'Mortality weight wk4 (g)', 'Culling wk4', 'Culling weight wk4 (g)', 'Total Mort. + cull 22-28d (g)', 'Mortality 22-28d (%)', 'Culling 22-28dd (%)', 'Mort + Cull 22-28d (%)', '# Fnl birds wk4', 'Container weight (g).3', 'Container + birds weight (g).3', 'Group BW28(g)', 'BW28 /A (g)', 'Group FI 22-28d (g)', 'FI 22-28d /A (g)', 'Group BWG 22-28d (g)', 'BWG 22-28d /A (g)', 'Group BWG 22-28d corrected(g)', 'BWG 22-28d /A corrected (g)', 'FCR 22-28d (g:g)', 'FCR22-28 corrected (g:g)', 'Wk5   (29-35d)', 'Offered feed wk5 (g)', 'Adition feed wk5 (g) (15/05/2021)', 'Subtracted feed (g) 14/05/2021', 'Leftover feed wk5 (g)', 'Unnamed: 127', 'Water Adition WK 5 (14/05/2021)', 'Leftover water WK 5', '# Ini birds wk5', 'Mortality wk5', 'Mortality weight wk5 (g)', 'Culling wk5', 'Culling weight wk5 (g)', 'Total Mort. + cull 29-33d (g)', '# Fnl birds wk5', 'Container weight (g).4', 'Container + birds weight (g).4', 'Group BW33 (g)', 'BW33 /A (g)', 'Group FI 22-33 (g)', 'FI 22-33d /A (g)', 'Group WC 22-33 (g)', 'WC 22 - 33d/A (g)', 'Group BWG 22-33d (g)', 'BWG 22-33d /A (g)', 'Group BWG 22-33d corrected (g)', 'BWG 22-33d /A corrected (g) ', 'FCR 22-33d (g:g)', 'FCR 22-33d corrected (g:g) ', 'Mortality 22-33d (%)', 'Culling 22-33d (%)', 'Mort + Cull 22-33d (%)', 'ProjectID']

In [413]:
E335[[i for i in E335.columns if "Group FI" in i]].columns

Index(['Group FI 0-10d (g)', 'Group FI 11-14d (g)', 'Group FI 15-21d (g)',
       'Group FI 22-28d (g)', 'Group FI 22-33 (g)', 'Group FI 29-33 (g)'],
      dtype='object')

In [414]:
E335 = E335[['ProjectID', 'House', 'Pen', 'Blind Trts ', '# Ini birds 1d',
             
             'Group BW1 (g)', 'Group BW10(g)', 'Group BW14(g)', 'Group BW21 (g)', 'Group BW28(g)', 'Group BW33 (g)', 
             
             
             '# Fnl birds 10d', '# Fnl birds 14d', '# Fnl birds wk3','# Fnl birds wk4', '# Fnl birds wk5',

              
               
             'Mortality weight 0-10d (g)', 'Mortality weight 11-14d (g)',
             'Mortality weight wk3 (g)', 'Mortality weight wk4 (g)',
             'Mortality weight wk5 (g)',
             
             'Culling weight 0-10d (g)', 'Culling weight 11-14d (g)',
             'Culling weight wk3 (g)', 'Culling weight wk4 (g)',
             'Culling weight wk5 (g)',

             'Culling 0-10d', 'Culling 11-14d', 'Culling wk3', 
             'Culling wk4', 'Culling wk5',

               

             'Group FI 0-10d (g)', 'Group FI 11-14d (g)', 'Group FI 15-21d (g)',
             'Group FI 22-28d (g)', 'Group FI 29-33 (g)'
               
               
               
             ]]
E335.head()

,ProjectID,House,Pen,Blind Trts,# Ini birds 1d,Group BW1 (g),Group BW10(g),Group BW14(g),Group BW21 (g),Group BW28(g),...,Culling 0-10d,Culling 11-14d,Culling wk3,Culling wk4,Culling wk5,Group FI 0-10d (g),Group FI 11-14d (g),Group FI 15-21d (g),Group FI 22-28d (g),Group FI 29-33 (g)
0,E335,1,1,5,40,1819,10560,13660,28520,0,...,0,0,0,0,0,11060,7150,20450,0,0
1,E335,1,2,7,40,1762,9880,12200,25200,0,...,0,0,0,0,1,10910,6780,19970,0,0
2,E335,1,3,12,40,1801,10100,12800,26300,0,...,0,0,0,0,0,10790,6840,19750,0,0
3,E335,1,4,11,40,1768,9880,10500,23600,0,...,0,0,0,0,0,10560,4440,17780,0,0
4,E335,1,5,9,40,1794,10220,12650,25600,0,...,0,0,0,0,0,10640,6580,19120,0,0

In [408]:
E335.columns

Index(['ProjectID', 'House', 'Pen', 'Blind Trts ', '# Ini birds 1d',
       'Group BW1 (g)', 'Group BW10(g)', 'Group BW14(g)', 'Group BW21 (g)',
       'Group BW28(g)', 'Group BW33 (g)', '# Fnl birds 10d', '# Fnl birds 14d',
       '# Fnl birds wk3', '# Fnl birds wk4', '# Fnl birds wk5',
       'Mortality weight 0-10d (g)', 'Mortality weight 11-14d (g)',
       'Mortality weight wk3 (g)', 'Mortality weight wk4 (g)',
       'Mortality weight wk5 (g)', 'Culling weight 0-10d (g)',
       'Culling weight 11-14d (g)', 'Culling weight wk3 (g)',
       'Culling weight wk4 (g)', 'Culling weight wk5 (g)', 'Culling 0-10d',
       'Culling 11-14d', 'Culling wk3', 'Culling wk4', 'Culling wk5',
       'Group FI 0-10d (g)', 'Group FI 11-14d (g)', 'Group FI 15-21d (g)',
       'Group FI 22-28d (g)', 'Group FI 22-33 (g)'],
      dtype='object')

In [415]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Blind Trts ': 'Treatment',
    '# Ini birds 1d':'Init_Birds_D1', 


    'Group BW1 (g)':'GBW_initial', 
    'Group BW10(g)':'GBW_10', 
    'Group BW14(g)':'GBW_14', 
    'Group BW21 (g)':'GBW_21',
    'Group BW28(g)':'GBW_28', 
    'Group BW33 (g)':'GBW_33', 

    
    '# Fnl birds 10d':'Fnl_Birds_D10', 
    '# Fnl birds 14d':'Fnl_Birds_D14',
    '# Fnl birds wk3':'Fnl_Birds_D21', 
    '# Fnl birds wk4':'Fnl_Birds_D28', 
    '# Fnl birds wk5':'Fnl_Birds_D33',
    
    'Mortality weight 0-10d (g)':'Mort_Wt_D10', 
    'Mortality weight 11-14d (g)':'Mort_Wt_D14',
    'Mortality weight wk3 (g)':'Mort_Wt_D21', 
    'Mortality weight wk4 (g)':'Mort_Wt_D28',
    'Mortality weight wk5 (g)':'Mort_Wt_D33', 

    
    'Culling weight 0-10d (g)':'Cull_Wt_D10',
    'Culling weight 11-14d (g)':'Cull_Wt_D14', 
    'Culling weight wk3 (g)':'Cull_Wt_D21',
    'Culling weight wk4 (g)':'Cull_Wt_D28', 
    'Culling weight wk5 (g)':'Cull_Wt_D33', 

    
    'Culling 0-10d':'Cull_D10',
    'Culling 11-14d':'Cull_D14', 
    'Culling wk3':'Cull_D21', 
    'Culling wk4':'Cull_D28', 
    'Culling wk5':'Cull_D33',

    
    'Group FI 0-10d (g)':'GFI_D10', 
    'Group FI 11-14d (g)':'GFI_D14', 
    'Group FI 15-21d (g)':'GFI_D21',
    'Group FI 22-28d (g)':'GFI_D28', 
    'Group FI 29-33 (g)':'GFI_D33'
    
   


    
}

E335.rename(columns=column_rename_map, inplace=True)
E335.head()

,ProjectID,House,Pen,Treatment,Init_Birds_D1,GBW_initial,GBW_10,GBW_14,GBW_21,GBW_28,...,Cull_D10,Cull_D14,Cull_D21,Cull_D28,Cull_D33,GFI_D10,GFI_D14,GFI_D21,GFI_D28,GFI_D33
0,E335,1,1,5,40,1819,10560,13660,28520,0,...,0,0,0,0,0,11060,7150,20450,0,0
1,E335,1,2,7,40,1762,9880,12200,25200,0,...,0,0,0,0,1,10910,6780,19970,0,0
2,E335,1,3,12,40,1801,10100,12800,26300,0,...,0,0,0,0,0,10790,6840,19750,0,0
3,E335,1,4,11,40,1768,9880,10500,23600,0,...,0,0,0,0,0,10560,4440,17780,0,0
4,E335,1,5,9,40,1794,10220,12650,25600,0,...,0,0,0,0,0,10640,6580,19120,0,0

In [416]:
E335.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE335.csv', index=False)

# E345

In [447]:
E345 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Raw Data E-345 Enzybox 12-10-2021.xlsx", "Performance Data")

In [448]:
E345["ProjectID"] = 'E345'
print(list(E345.columns))
E345.head()

['House', 'Line', 'Pen', 'Blind Trts ', 'Operator', '# Ini birds 1d', 'Group BWh (g)', 'BW hatch (g)', 'Mortality 0-6d', 'Mortality weight 0-6d (g)', 'Culling 0-6d', 'Culling weight 0-6d (g)', 'Total Mort. + cull 0-6d (g)', 'Mortality 7d', 'Mortality weight 7d (g)', 'Culling 7d', 'Culling weight 7d (g)', 'Total Mort. + cull 7d (g)', 'Sampling 7d', 'Sampling weight 7d', 'Offered feed 1d (g)', 'Offered water 1d (g)', 'Leftover feed 7d (g)', 'Leftover water 7d (g)', 'Container weight (g)', 'Container + birds weight (g)', '# Fnl birds 7d', 'Group BW7(g)', 'BW7 (g)', 'Group FI 0-7d (g)', 'FI 0-7d (g)', 'Group WC 0-7d (g)', 'WC 0-7d(g)', 'Group BWG 0-7d (g)', 'BWG 0-7d (g)', 'Group BWG 0-7d corrected  (g)', 'BWG 0-7d corrected (g)', 'FCR 0-7d (g:g)', 'FCR 0-7d corrected (g:g)', 'Mortality 0-7d (%)', 'Culling 0-7d (%)', 'Mort + Cull 0-7d (%)', 'Wk2   (8-14d)', '# Ini birds 8d', 'Ini GBW8', 'Offered feed 8d (g)', 'Leftover feed 14d (g)', 'Offered Water 8d', 'Leftover water 14d (g)', 'Mortality 8-13d', 'Mortality weight 8-13d (g)', 'Culling 8-13d', 'Culling weight 8-13d (g)', 'Total Mort. + cull 8-13d (g)', 'Mortality 14d', 'Mortality weight 14d', 'Culling 14d', 'Culling weight 14d', 'Mort + Cull 14d (g)', 'Sampling 14d', 'Sampling weight 14d (g)', 'Container weight (g).1', 'Container + birds weight (g).1', 'Fnl birds 14d', 'Group BW14(g)', 'BW14  (g)', 'Group FI 8-14d (g)', 'FI 8-14d  (g)', 'Group WC 8-14d (g)', 'WC 8-14d  (g)', 'Group BWG 8-14d (g)', 'BWG 8-14d  (g)', 'Group BWG 8-14d corrected (g)', 'BWG 8-14d  corrected (g) ', 'FCR 8-14d (g:g)', 'FCR 8-14d corrected (g:g) ', 'Mortality 8-14d (%)', 'Culling 8-14d (%)', 'Mort + Cull 8-14d (%)', 'Wk3  (15-21d)', '# Ini birds 15d', 'Ini GBW 15d', 'Offered feed 15-21 (g)', 'Offered water 15-21 (g)', 'Feed Adition 15-21(g)', 'Leftover feed 15-21d (g)', 'Leftover water 15-21 (g)', 'Mortality 15-20d', 'Mortality weight 15-20d (g)', 'Culling 15-20d', 'Culling weight 15-20d (g)', 'Total Mort. + cull 15-20d (g)', 'Mortality 21d', 'Mortality weight 21d', 'Culling 21d', 'Culling weight 21d', 'Total Mort + Cull 21d (g)', 'Sampling 21d', 'Sampling weight 21d', 'Container weight (g).2', 'Container + birds weight (g).2', '# Fnl birds 21d', 'Group BW21 (g)', 'BW21  (g)', 'Group FI 15-21d (g)', 'FI 15-21d  (g)', 'Group WC 15-21d /A (g)', 'WC/ A 15-21d  (g)', 'Group BWG 15-21d (g)', 'BWG 15-21d  (g)', 'Group BWG 15-21d  corrected (g) ', 'BWG 15-21d  corrected (g) ', 'FCR 15-21d (g:g)', 'FCR 15-21d corrected (g:g) ', 'Mortality 15-21d (%)', 'Culling 15-21dd (%)', 'Mort + Cull 15-21d (%)', 'Wk4  (22-28d)', '#Ini birds 22d', 'Ini GBW 22d', 'Offered feed 22-28d (g)', 'Subtracted feed (g) 7/09/21 (g)', 'Leftover feed 22-28d (g)', 'Offered water 22 -28d (g)', 'Leftover water 22-28d (g)', 'Mortality 22-26d', 'Mortality weight 22-26d (g)', 'Culling 22-26d', 'Culling weight 22-26d (g)', 'Total Mort. + Cull 22-26d (g)', 'Mortality 27d', 'Mortality weight 27d (g)', 'Culling 27d', 'Culling weight 27d (g)', 'Total Mort + Cull 27d (g)', 'Sampling 27d', 'Sampling weight 27d (g)', 'Container weight (g).3', 'Container + birds weight (g).3', '# Fnl birds 27d', 'Group BW28(g)', 'BW28 (g)', 'Group FI 22-28d (g)', 'FI 22-28d  (g)', 'Group BWG 22-28d (g)', 'BWG 22-28d (g)', 'Group BWG 22-28d corrected(g)', 'BWG 22-28d corrected (g)', 'FCR 22-28d (g:g)', 'FCR22-28 corrected (g:g)', 'Mortality 22-28d (%)', 'Culling 22-28d (%)', 'Mort + Cull 22-28d (%)', 'Wk5   (29-35d)', '#Ini birds 28d', 'Ini GBW 28d', 'Offered feed 29-35d (g)', 'Adition feed 29-35d (g)', 'Adition feed 29 - 35d (g) 20/09/2021', 'Leftover feed 29-35d (g)', 'Offered water 29-35d (g)', 'Leftover water 29-35d (g)', 'Mortality 28-34d', 'Mortality weight 28-34d (g)', 'Culling 28-34d', 'Culling weight 28-34d (g)', 'Total Mort. + cull 28-34d (g)', 'Mortality 35d', 'Mortality weight 35d (g)', 'Culling 35d', 'Culling weight 35d', 'Total Mort + Cull 35d (g)', 'Sampling 35d', 'Sampling weight 35d', 'Container weight (g).4', 'Container + birds weight (g).4', '# Fnl birds 35d', 'Group BW 35 (g)', 'BW35  (g)', 'Group FI 29-35d (g)', 'FI 29-35d (g)', 'Group WC 29-35d (g)', 'WC 29 - 35d/A (g)', 'Group BWG 29-35d (g)', 'BWG 29-35d (g)', 'Group BWG 29-35d corrected (g)', 'BWG 29-35d corrected (g) ', 'FCR 29-35d (g:g)', 'FCR 29-35d corrected (g:g) ', 'Mortality 29-35d (%)', 'Culling 29-35d (%)', 'Mort + Cull 29-35d (%)', 'Wk5   (36-42d)', '# Ini Birds 36d', 'Ini GBW 36d', 'Offered feed 36-42d (g)', 'Sustracted feed 36-42d (g)', 'Leftover feed 36-42d (g)', 'Offered water 26-42d (g)', 'Leftover water 36 - 42d (g)', 'Mortality 36-41d', 'Mortality weight 36-41d (g)', 'Culling 36-41d', 'Culling weight 36-41d (g)', 'Total Mort. + cull 36-41d (g)', 'Mortality 42d', 'Mortality weight 42d (g)', 'Culling 42d', 'Culling weight 42d (g)', 'Total Mort + Cull 42d (g)', 'Sampling 42d', 'Sampling weight 42d (g)', 'Container weight (g).5', 'Container + birds weight (g).5', '# Fnl birds 42d', 'Group BW 42d (g)', 'BW 42d (g)', 'Group FI 36-42d (g)', 'FI 36-42d (g)', 'Group WC 29-35 (g)', 'WC 29 - 35d (g)', 'Group BWG 36-42d (g)', 'BWG 36-42d (g)', 'Group BWG 36-42d corrected (g)', 'BWG 36-42d corrected (g) ', 'FCR 36-42d (g:g)', 'FCR 36-42d corrected (g:g) ', 'Mortality 36-42d (%)', 'Culling 36-42d (%)', 'Mort + Cull 36-42d (%)', 'ProjectID']

,House,Line,Pen,Blind Trts,Operator,# Ini birds 1d,Group BWh (g),BW hatch (g),Mortality 0-6d,Mortality weight 0-6d (g),...,Group BWG 36-42d (g),BWG 36-42d (g),Group BWG 36-42d corrected (g),BWG 36-42d corrected (g),FCR 36-42d (g:g),FCR 36-42d corrected (g:g),Mortality 36-42d (%),Culling 36-42d (%),Mort + Cull 36-42d (%),ProjectID
0,1,A,1,2,NaN,25,1062,42.48,0,0,...,13225,601.136364,13225,601.136364,1.888091,1.888091,0.0,0,0.0,E345
1,1,A,2,8,NaN,25,1042,41.68,1,89,...,11875,539.772727,11875,539.772727,2.148211,2.148211,0.0,0,0.0,E345
2,1,A,3,5,NaN,25,1062,42.48,0,0,...,14788,672.181818,14788,672.181818,1.865702,1.865702,0.0,0,0.0,E345
3,1,A,4,3,NaN,25,1036,41.44,0,0,...,13047,593.045455,13047,593.045455,2.059477,2.059477,0.0,0,0.0,E345
4,1,A,5,1,NaN,25,1032,41.28,0,0,...,13081,568.739130,13081,568.739130,2.054124,2.054124,0.0,0,0.0,E345

In [433]:
E345[[i for i in E345.columns if "Group FI" in i]].columns

Index(['Group FI 0-7d (g)', 'Group FI 8-14d (g)', 'Group FI 15-21d (g)',
       'Group FI 22-28d (g)', 'Group FI 29-35d (g)', 'Group FI 36-42d (g)'],
      dtype='object')

In [449]:
E345 = E345[['ProjectID', 'House', 'Pen', 'Blind Trts ', '# Ini birds 1d',
             
             'Group BWh (g)', 'Group BW7(g)', 'Group BW14(g)', 'Group BW21 (g)', 'Group BW28(g)', 'Group BW 35 (g)', 'Group BW 42d (g)',
             
             
             '# Fnl birds 7d', 'Fnl birds 14d', '# Fnl birds 21d', '# Fnl birds 27d', '# Fnl birds 35d', '# Fnl birds 42d',

              
               
             'Mortality weight 0-6d (g)', 'Mortality weight 7d (g)',
             'Mortality weight 8-13d (g)', 'Mortality weight 14d',
             'Mortality weight 15-20d (g)', 'Mortality weight 21d',
           'Mortality weight 22-26d (g)', 'Mortality weight 27d (g)',
           'Mortality weight 28-34d (g)', 'Mortality weight 35d (g)',
           'Mortality weight 36-41d (g)', 'Mortality weight 42d (g)',
             
             'Culling 0-6d', 'Culling weight 0-6d (g)', 'Culling 7d',
           'Culling weight 7d (g)',  'Culling 8-13d',
           'Culling weight 8-13d (g)', 'Culling 14d', 'Culling weight 14d',
           'Culling 15-20d', 'Culling weight 15-20d (g)',
           'Culling 21d', 'Culling weight 21d', 
           'Culling 22-26d', 'Culling weight 22-26d (g)', 'Culling 27d',
           'Culling weight 27d (g)', 'Culling 28-34d',
           'Culling weight 28-34d (g)', 'Culling 35d', 'Culling weight 35d',
           'Culling 36-41d', 'Culling weight 36-41d (g)',
           'Culling 42d', 'Culling weight 42d (g)', 

               

             'Group FI 0-7d (g)', 'Group FI 8-14d (g)', 'Group FI 15-21d (g)',
           'Group FI 22-28d (g)', 'Group FI 29-35d (g)', 'Group FI 36-42d (g)'
               
               
               
             ]]
E345.head()

,ProjectID,House,Pen,Blind Trts,# Ini birds 1d,Group BWh (g),Group BW7(g),Group BW14(g),Group BW21 (g),Group BW28(g),...,Culling 36-41d,Culling weight 36-41d (g),Culling 42d,Culling weight 42d (g),Group FI 0-7d (g),Group FI 8-14d (g),Group FI 15-21d (g),Group FI 22-28d (g),Group FI 29-35d (g),Group FI 36-42d (g)
0,E345,1,1,2,25,1062,4081,9180,20140,32470,...,0,0,0,0,3480,7060,14800,19250,30940,24970
1,E345,1,2,8,25,1042,4030,9990,21100,32520,...,0,0,0,0,3460,8130,16130,19090,32520,25510
2,E345,1,3,5,25,1062,3829,8870,18940,29810,...,0,0,0,0,3280,7470,14870,17870,30040,27590
3,E345,1,4,3,25,1036,3993,9820,20440,32420,...,0,0,0,0,3400,7920,15540,18790,31820,26870
4,E345,1,5,1,25,1032,4116,10040,21440,34610,...,0,0,0,0,3360,7600,15500,19610,31820,26870

In [435]:
E345.columns

Index(['ProjectID', 'House', 'Pen', 'Blind Trts ', '# Ini birds 1d',
       'Group BWh (g)', 'Group BW7(g)', 'Group BW14(g)', 'Group BW21 (g)',
       'Group BW28(g)', 'Group BW 35 (g)', 'Group BW 42d (g)',
       '# Fnl birds 7d', 'Fnl birds 14d', '# Fnl birds 21d', '# Fnl birds 27d',
       '# Fnl birds 35d', '# Fnl birds 42d', 'Mortality weight 0-6d (g)',
       'Mortality weight 7d (g)', 'Mortality weight 8-13d (g)',
       'Mortality weight 14d', 'Mortality weight 15-20d (g)',
       'Mortality weight 21d', 'Mortality weight 22-26d (g)',
       'Mortality weight 27d (g)', 'Mortality weight 28-34d (g)',
       'Mortality weight 35d (g)', 'Mortality weight 36-41d (g)',
       'Mortality weight 42d (g)', 'Culling 0-6d', 'Culling weight 0-6d (g)',
       'Culling 7d', 'Culling weight 7d (g)', 'Culling 0-7d (%)',
       'Culling 8-13d', 'Culling weight 8-13d (g)', 'Culling 14d',
       'Culling weight 14d', 'Culling 8-14d (%)', 'Culling 15-20d',
       'Culling weight 15-20d (g)', 'Culling 21d', 'Culling weight 21d',
       'Culling 15-21dd (%)', 'Culling 22-26d', 'Culling weight 22-26d (g)',
       'Culling 27d', 'Culling weight 27d (g)', 'Culling 22-28d (%)',
       'Culling 28-34d', 'Culling weight 28-34d (g)', 'Culling 35d',
       'Culling weight 35d', 'Culling 29-35d (%)', 'Culling 36-41d',
       'Culling weight 36-41d (g)', 'Culling 42d', 'Culling weight 42d (g)',
       'Culling 36-42d (%)', 'Group FI 0-7d (g)', 'Group FI 8-14d (g)',
       'Group FI 15-21d (g)', 'Group FI 22-28d (g)', 'Group FI 29-35d (g)',
       'Group FI 36-42d (g)'],
      dtype='object')

In [450]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Blind Trts ': 'Treatment',
    '# Ini birds 1d':'Init_Birds_D1', 


    'Group BWh (g)':'GBW_initial', 
    'Group BW7(g)':'GBW_7', 
    'Group BW14(g)':'GBW_14', 
    'Group BW21 (g)':'GBW_21', 
    'Group BW28(g)':'GBW_28', 
    'Group BW 35 (g)':'GBW_35', 
    'Group BW 42d (g)':'GBW_42',
             
             
     '# Fnl birds 7d':'Fnl_Birds_D7', 
    'Fnl birds 14d':'Fnl_Birds_D14', 
    '# Fnl birds 21d':'Fnl_Birds_D21', 
    '# Fnl birds 27d':'Fnl_Birds_D27', 
    '# Fnl birds 35d':'Fnl_Birds_D35', 
    '# Fnl birds 42d':'Fnl_Birds_D42',

              
               
     'Mortality weight 0-6d (g)':'Mort_Wt_D6', 
    'Mortality weight 7d (g)':'Mort_Wt_D7',
     'Mortality weight 8-13d (g)':'Mort_Wt_D13', 
    'Mortality weight 14d':'Mort_Wt_D14',
     'Mortality weight 15-20d (g)':'Mort_Wt_D20', 
    'Mortality weight 21d':'Mort_Wt_D21',
    'Mortality weight 22-26d (g)':'Mort_Wt_D26', 
    'Mortality weight 27d (g)':'Mort_Wt_D27',
   'Mortality weight 28-34d (g)':'Mort_Wt_D34', 
    'Mortality weight 35d (g)':'Mort_Wt_D35',
   'Mortality weight 36-41d (g)':'Mort_Wt_D41', 
    'Mortality weight 42d (g)':'Mort_Wt_D42',
     
     'Culling 0-6d':'Cull_D6', 
    'Culling weight 0-6d (g)':'Cull_Wt_D6', 
    'Culling 7d':'Cull_D7',
   'Culling weight 7d (g)':'Cull_Wt_D7', 
    'Culling 8-13d':'Cull_D13',
   'Culling weight 8-13d (g)':'Cull_Wt_D13', 
    'Culling 14d':'Cull_D14', 
    'Culling weight 14d':'Cull_Wt_D14',
    'Culling 15-20d':'Cull_D20', 
    'Culling weight 15-20d (g)':'Cull_Wt_D20',
   'Culling 21d':'Cull_D21', 
    'Culling weight 21d':'Cull_Wt_D21', 
   'Culling 22-26d':'Cull_D26', 
    'Culling weight 22-26d (g)':'Cull_Wt_D26', 
    'Culling 27d':'Cull_D27',
   'Culling weight 27d (g)':'Cull_Wt_D27', 
    'Culling 28-34d':'Cull_D34',
   'Culling weight 28-34d (g)':'Cull_Wt_D34', 
    'Culling 35d':'Cull_D35', 
    'Culling weight 35d':'Cull_Wt_D35',
    'Culling 36-41d':'Cull_D41', 
    'Culling weight 36-41d (g)':'Cull_Wt_D41',
   'Culling 42d':'Cull_D42', 
    'Culling weight 42d (g)':'Cull_Wt_D42', 

       

     'Group FI 0-7d (g)':'GFI_D7', 
    'Group FI 8-14d (g)':'GFI_D14', 
    'Group FI 15-21d (g)':'GFI_D21',
   'Group FI 22-28d (g)':'GFI_D28', 
    'Group FI 29-35d (g)':'GFI_D35', 
    'Group FI 36-42d (g)':'GFI_D42'

    
    
   


    
}

E345.rename(columns=column_rename_map, inplace=True)
E345.head()

,ProjectID,House,Pen,Treatment,Init_Birds_D1,GBW_initial,GBW_7,GBW_14,GBW_21,GBW_28,...,Cull_D41,Cull_Wt_D41,Cull_D42,Cull_Wt_D42,GFI_D7,GFI_D14,GFI_D21,GFI_D28,GFI_D35,GFI_D42
0,E345,1,1,2,25,1062,4081,9180,20140,32470,...,0,0,0,0,3480,7060,14800,19250,30940,24970
1,E345,1,2,8,25,1042,4030,9990,21100,32520,...,0,0,0,0,3460,8130,16130,19090,32520,25510
2,E345,1,3,5,25,1062,3829,8870,18940,29810,...,0,0,0,0,3280,7470,14870,17870,30040,27590
3,E345,1,4,3,25,1036,3993,9820,20440,32420,...,0,0,0,0,3400,7920,15540,18790,31820,26870
4,E345,1,5,1,25,1032,4116,10040,21440,34610,...,0,0,0,0,3360,7600,15500,19610,31820,26870

In [472]:
E345.columns

Index(['ProjectID', 'House', 'Pen', 'Treatment', 'Init_Birds_D1',
       'GBW_initial', 'GBW_7', 'GBW_14', 'GBW_21', 'GBW_28', 'GBW_35',
       'GBW_42', 'Fnl_Birds_D7', 'Fnl_Birds_D14', 'Fnl_Birds_D21',
       'Fnl_Birds_D27', 'Fnl_Birds_D35', 'Fnl_Birds_D42', 'Mort_Wt_D6',
       'Mort_Wt_D7', 'Mort_Wt_D13', 'Mort_Wt_D14', 'Mort_Wt_D20',
       'Mort_Wt_D21', 'Mort_Wt_D26', 'Mort_Wt_D27', 'Mort_Wt_D34',
       'Mort_Wt_D35', 'Mort_Wt_D41', 'Mort_Wt_D42', 'Cull_D6', 'Cull_Wt_D6',
       'Cull_D7', 'Cull_Wt_D7', 'Cull_D13', 'Cull_Wt_D13', 'Cull_D14',
       'Cull_Wt_D14', 'Cull_D20', 'Cull_Wt_D20', 'Cull_D21', 'Cull_Wt_D21',
       'Cull_D26', 'Cull_Wt_D26', 'Cull_D27', 'Cull_Wt_D27', 'Cull_D34',
       'Cull_Wt_D34', 'Cull_D35', 'Cull_Wt_D35', 'Cull_D41', 'Cull_Wt_D41',
       'Cull_D42', 'Cull_Wt_D42', 'GFI_D7', 'GFI_D14', 'GFI_D21', 'GFI_D28',
       'GFI_D35', 'GFI_D42'],
      dtype='object')

In [451]:
E345.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE345.csv', index=False)

# E347

In [476]:
E347 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/E-347 Niveles de Sodio 24-01-2022.xlsx", "Performance Data")

In [477]:
E347["ProjectID"] = 'E347'
print(list(E347.columns))
E347.head()

['House', 'Line', 'Pen', 'Blind Trts ', 'TrtSt', 'TrtFn', 'Operator', '# Ini birds 1d', 'Group BWh (g)', 'BW hatch (g)', 'Mortality 0-6d', 'Mortality weight 0-6d (g)', 'Culling 0-6d', 'Culling weight 0-6d (g)', 'Total Mort. + cull 0-6d (g)', 'Mortality 7d', 'Mortality weight 7d (g)', 'Culling 7d', 'Culling weight 7d (g)', 'Total Mort. + cull 7d (g)', 'Sampling 7d', 'Sampling weight 7d', 'Offered feed 1d (g)', 'Offered water 1d (g)', 'Leftover feed 7d (g)', 'Leftover water 7d (g)', 'Container weight (g)', 'Container + birds weight (g)', '# Fnl birds 7d', 'Group BW7(g)', 'BW7 (g)', 'Group FI 0-7d (g)', 'FI 0-7d (g)', 'Group WC 0-7d (g)', 'WC 0-7d(g)', 'Group BWG 0-7d (g)', 'BWG 0-7d (g)', 'Group BWG 0-7d corrected  (g)', 'BWG 0-7d corrected (g)', 'FCR 0-7d (g:g)', 'FCR 0-7d corrected (g:g)', 'Mortality 0-7d (%)', 'Culling 0-7d (%)', 'Mort + Cull 0-7d (%)', 'Wk2   (8-14d)', '# Ini birds 8d', 'Ini GBW8', 'Offered feed 8d (g)', 'Leftover feed 14d (g)', 'Offered Water 8d', 'Leftover water 14d (g)', 'Mortality 8-13d', 'Mortality weight 8-13d (g)', 'Culling 8-13d', 'Culling weight 8-13d (g)', 'Total Mort. + cull 8-13d (g)', 'Mortality 14d', 'Mortality weight 14d', 'Culling 14d', 'Culling weight 14d', 'Mort + Cull 14d (g)', 'Sampling 14d', 'Sampling weight 14d (g)', 'Container weight (g).1', 'Container + birds weight (g).1', 'Fnl birds 14d', 'Group BW14(g)', 'BW14  (g)', 'Group FI 8-14d (g)', 'FI 8-14d  (g)', 'Group WC 8-14d (g)', 'WC 8-14d  (g)', 'Group BWG 8-14d (g)', 'BWG 8-14d  (g)', 'Group BWG 8-14d corrected (g)', 'BWG 8-14d  corrected (g) ', 'FCR 8-14d (g:g)', 'FCR 8-14d corrected (g:g) ', 'Mortality 8-14d (%)', 'Culling 8-14d (%)', 'Mort + Cull 8-14d (%)', 'Wk3  (15-21d)', '# Ini birds 15d', 'Ini GBW 15d', 'Offered feed 15-21 (g)', 'Offered water 15-21 (g)', 'Water addition (g) 19/11/2021', 'Water addition (g) 23/11/2021', 'Feed addition (g) ', 'Leftover feed 15-21d (g)', 'Leftover water 15-21 (g)', 'Mortality 15-20d', 'Mortality weight 15-20d (g)', 'Culling 15-20d', 'Culling weight 15-20d (g)', 'Total Mort. + cull 15-20d (g)', 'Mortality 21d', 'Mortality weight 21d', 'Culling 21d', 'Culling weight 21d', 'Total Mort + Cull 21d (g)', 'Sampling 21d', 'Sampling weight 21d', 'Container weight (g).2', 'Container + birds weight (g).2', '# Fnl birds 21d', 'Group BW21 (g)', 'BW21  (g)', 'Group FI 15-21d (g)', 'FI 15-21d  (g)', 'Group WC 15-21d /A (g)', 'WC/ A 15-21d  (g)', 'Group BWG 15-21d (g)', 'BWG 15-21d  (g)', 'Group BWG 15-21d  corrected (g) ', 'BWG 15-21d  corrected (g) ', 'FCR 15-21d (g:g)', 'FCR 15-21d corrected (g:g) ', 'Mortality 15-21d (%)', 'Culling 15-21dd (%)', 'Mort + Cull 15-21d (%)', 'Wk4  (22-28d)', '#Ini birds 22d', 'Ini GBW 22d', 'Offered feed 22-28d (g)', 'Feed adition 22-28d (g)', 'Leftover feed 22-28d (g)', 'Offered water 22 -28d (g)', 'Water adition 22-28d (g) (26-11-2021)', 'Water adition 22-28d (g) (29-11-2021)', 'Leftover water 22-28d (g)', 'Mortality 22-27d', 'Mortality weight 22-27d (g)', 'Culling 22-27d', 'Culling weight 22-27d (g)', 'Total Mort. + Cull 22-27d (g)', 'Mortality 28d', 'Mortality weight 28d (g)', 'Culling 28d', 'Culling weight 28d (g)', 'Total Mort + Cull 28d (g)', 'Sampling 28d', 'Sampling weight 28d (g)', 'Container weight (g).3', 'Container + birds weight (g).3', '# Fnl birds 28d', 'Group BW28(g)', 'BW28 (g)', 'Group FI 22-28d (g)', 'FI 22-28d  (g)', 'Group WC 22-28d /A (g)', 'WC/ A 22-28d  (g)', 'Group BWG 22-28d (g)', 'BWG 22-28d (g)', 'Group BWG 22-28d corrected(g)', 'BWG 22-28d corrected (g)', 'FCR 22-28d (g:g)', 'FCR22-28 corrected (g:g)', 'Mortality 22-28d (%)', 'Culling 22-28d (%)', 'Mort + Cull 22-28d (%)', 'Wk5   (29-35d)', '#Ini birds 29d', 'Ini GBW 29d', 'Offered feed 29-35d (g)', 'Adition feed 29-35d (g)', 'Leftover feed 29-35d (g)', 'Offered water 29-35d (g)', 'Water adition 29-35d (3-12-21)', 'Water adition 29-35d (8-12-21)', 'Leftover water 29-35d (g)', 'Mortality 29-34d', 'Mortality weight 29-34d (g)', 'Culling 29-34d', 'Culling weight 29-34d (g)', 'Total Mort. + cull 29-34d (g)', 'Mortality 35d', 'Mortality weight 35d (g)', 'Culling 35d', 'Culling weight 35d', 'Total Mort + Cull 35d (g)', 'Sampling 35d', 'Sampling weight 35d', 'Container weight (g).4', 'Container + birds weight (g).4', '# Fnl birds 35d', 'Group BW 35 (g)', 'BW35  (g)', 'Group FI 29-35d (g)', 'FI 29-35d (g)', 'Group WC 29-35d (g)', 'WC 29 - 35d/A (g)', 'Group BWG 29-35d (g)', 'BWG 29-35d (g)', 'Group BWG 29-35d corrected (g)', 'BWG 29-35d corrected (g) ', 'FCR 29-35d (g:g)', 'FCR 29-35d corrected (g:g) ', 'Mortality 29-35d (%)', 'Culling 29-35d (%)', 'Mort + Cull 29-35d (%)', 'Wk5   (36-42d)', '# Ini Birds 36d', 'Ini GBW 36d', 'Offered feed 36-42d (g)', 'Leftover feed 36-42d (g)', 'Offered water 26-42d (g)', 'Water adition 36-42d (10/12/21) (g)', 'Water adition 36-42d (13/12/21) (g)', 'Leftover water 36 - 42d (g)', 'Mortality 36-41d', 'Mortality weight 36-41d (g)', 'Culling 36-41d', 'Culling weight 36-41d (g)', 'Total Mort. + cull 36-41d (g)', 'Mortality 42d', 'Mortality weight 42d (g)', 'Culling 42d', 'Culling weight 42d (g)', 'Total Mort + Cull 42d (g)', 'Sampling 42d', 'Sampling weight 42d (g)', 'Container weight (g).5', 'Container + birds weight (g).5', '# Fnl birds 42d', 'Group BW 42d (g)', 'BW 42d (g)', 'Group FI 36-42d (g)', 'FI 36-42d (g)', 'Group WC 36-42 (g)', 'WC 36 - 42d (g)', 'Group BWG 36-42d (g)', 'BWG 36-42d (g)', 'Group BWG 36-42d corrected (g)', 'BWG 36-42d corrected (g) ', 'FCR 36-42d (g:g)', 'FCR 36-42d corrected (g:g) ', 'Mortality 36-42d (%)', 'Culling 36-42d (%)', 'Mort + Cull 36-42d (%)', 'Initial Litter Weight (g)', 'Initial sample litter weight (g)', 'Final sample litter weight (g)', 'Litter Moisture, %', 'ProjectID']

,House,Line,Pen,Blind Trts,TrtSt,TrtFn,Operator,# Ini birds 1d,Group BWh (g),BW hatch (g),...,FCR 36-42d (g:g),FCR 36-42d corrected (g:g),Mortality 36-42d (%),Culling 36-42d (%),Mort + Cull 36-42d (%),Initial Litter Weight (g),Initial sample litter weight (g),Final sample litter weight (g),"Litter Moisture, %",ProjectID
0,1,A,1,8,Na0.28Cl0.42,Na0.28Cl0.52,D,25,1051,42.04,...,1.539048,1.539048,0,0.0,0.0,20000,148,NaN,-,E347
1,1,A,2,5,Na0.34Cl0.25,Na0.34Cl0.25,D,25,1041,41.64,...,1.589568,1.589568,0,0.0,0.0,20000,309,NaN,-,E347
2,1,A,3,10,Na0.40Cl0.57,Na0.40Cl0.71,D,25,1034,41.36,...,1.950207,1.950207,0,0.0,0.0,20000,240,NaN,-,E347
3,1,A,4,6,Na0.40Cl0.25,Na0.40Cl0.25,D,25,1023,40.92,...,2.087951,1.792781,5,0.0,5.0,20000,203,NaN,-,E347
4,1,A,5,3,Na0.22Cl0.25,Na0.22Cl0.25,D,25,1043,41.72,...,1.782996,1.782996,0,0.0,0.0,20000,137,NaN,-,E347

In [478]:
E347[[i for i in E347.columns if "Group FI" in i]].columns

Index(['Group FI 0-7d (g)', 'Group FI 8-14d (g)', 'Group FI 15-21d (g)',
       'Group FI 22-28d (g)', 'Group FI 29-35d (g)', 'Group FI 36-42d (g)'],
      dtype='object')

In [479]:
E347 = E347[['ProjectID', 'House', 'Pen', 'Blind Trts ', '# Ini birds 1d',
             
             'Group BWh (g)', 'Group BW7(g)', 'Group BW14(g)', 'Group BW21 (g)', 'Group BW28(g)', 'Group BW 35 (g)', 'Group BW 42d (g)',
             
             
             '# Fnl birds 7d', 'Fnl birds 14d', '# Fnl birds 21d', '# Fnl birds 28d', '# Fnl birds 35d', '# Fnl birds 42d',

              
               
             'Mortality weight 0-6d (g)', 'Mortality weight 7d (g)',
           'Mortality weight 8-13d (g)', 'Mortality weight 14d',
           'Mortality weight 15-20d (g)', 'Mortality weight 21d',
           'Mortality weight 22-27d (g)', 'Mortality weight 28d (g)',
           'Mortality weight 29-34d (g)', 'Mortality weight 35d (g)',
           'Mortality weight 36-41d (g)', 'Mortality weight 42d (g)',
             
            'Culling 0-6d', 'Culling weight 0-6d (g)', 'Culling 7d',
       'Culling weight 7d (g)', 'Culling 8-13d',
       'Culling weight 8-13d (g)', 'Culling 14d', 'Culling weight 14d',
        'Culling 15-20d', 'Culling weight 15-20d (g)',
       'Culling 21d', 'Culling weight 21d', 
       'Culling 22-27d', 'Culling weight 22-27d (g)', 'Culling 28d',
       'Culling weight 28d (g)', 'Culling 29-34d',
       'Culling weight 29-34d (g)', 'Culling 35d', 'Culling weight 35d',
        'Culling 36-41d', 'Culling weight 36-41d (g)',
       'Culling 42d', 'Culling weight 42d (g)', 

               

             'Group FI 0-7d (g)', 'Group FI 8-14d (g)', 'Group FI 15-21d (g)',
       'Group FI 22-28d (g)', 'Group FI 29-35d (g)', 'Group FI 36-42d (g)'
               
               
               
             ]]
E347.head()

,ProjectID,House,Pen,Blind Trts,# Ini birds 1d,Group BWh (g),Group BW7(g),Group BW14(g),Group BW21 (g),Group BW28(g),...,Culling 36-41d,Culling weight 36-41d (g),Culling 42d,Culling weight 42d (g),Group FI 0-7d (g),Group FI 8-14d (g),Group FI 15-21d (g),Group FI 22-28d (g),Group FI 29-35d (g),Group FI 36-42d (g)
0,E347,1,1,8,25,1051,5196,8320,16420,26290,...,0,0,0,0,4000,4700,10380,13460,18020,24240
1,E347,1,2,5,25,1041,5192,8220,16380,26360,...,0,0,0,0,4160,4640,10480,13520,17920,23160
2,E347,1,3,10,25,1034,5044,8200,16360,26030,...,0,0,0,0,3940,4740,10560,13500,18140,23500
3,E347,1,4,6,25,1023,4893,8100,16240,26010,...,0,0,0,0,3800,4640,10480,13640,17960,23740
4,E347,1,5,3,25,1043,5196,8220,16380,22160,...,0,0,0,0,3990,4680,10440,13300,14320,22020

In [480]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Blind Trts ': 'Treatment',
    '# Ini birds 1d':'Init_Birds_D1', 


    'Group BWh (g)':'GBW_initial', 
    'Group BW7(g)':'GBW_7', 
    'Group BW14(g)':'GBW_14', 
    'Group BW21 (g)':'GBW_21', 
    'Group BW28(g)':'GBW_28', 
    'Group BW 35 (g)':'GBW_35', 
    'Group BW 42d (g)':'GBW_42',
             
             
     '# Fnl birds 7d':'Fnl_Birds_D7', 
    'Fnl birds 14d':'Fnl_Birds_D14', 
    '# Fnl birds 21d':'Fnl_Birds_D21', 
    '# Fnl birds 28d':'Fnl_Birds_D28', 
    '# Fnl birds 35d':'Fnl_Birds_D35', 
    '# Fnl birds 42d':'Fnl_Birds_D42',

              
               
     'Mortality weight 0-6d (g)':'Mort_Wt_D6', 
    'Mortality weight 7d (g)':'Mort_Wt_D7',
     'Mortality weight 8-13d (g)':'Mort_Wt_D13', 
    'Mortality weight 14d':'Mort_Wt_D14',
     'Mortality weight 15-20d (g)':'Mort_Wt_D20', 
    'Mortality weight 21d':'Mort_Wt_D21',
    'Mortality weight 22-27d (g)':'Mort_Wt_D27', 
    'Mortality weight 28d (g)':'Mort_Wt_D28',
   'Mortality weight 29-34d (g)':'Mort_Wt_D34', 
    'Mortality weight 35d (g)':'Mort_Wt_D35',
   'Mortality weight 36-41d (g)':'Mort_Wt_D41', 
    'Mortality weight 42d (g)':'Mort_Wt_D42',
     
     'Culling 0-6d':'Cull_D6', 
    'Culling weight 0-6d (g)':'Cull_Wt_D6', 
    'Culling 7d':'Cull_D7',
   'Culling weight 7d (g)':'Cull_Wt_D7', 
    'Culling 8-13d':'Cull_D13',
   'Culling weight 8-13d (g)':'Cull_Wt_D13', 
    'Culling 14d':'Cull_D14', 
    'Culling weight 14d':'Cull_Wt_D14',
    'Culling 15-20d':'Cull_D20', 
    'Culling weight 15-20d (g)':'Cull_Wt_D20',
   'Culling 21d':'Cull_D21', 
    'Culling weight 21d':'Cull_Wt_D21', 
   'Culling 22-27d':'Cull_D27', 
    'Culling weight 22-27d (g)':'Cull_Wt_D27', 
    'Culling 28d':'Cull_D28',
   'Culling weight 28d (g)':'Cull_Wt_D28', 
    'Culling 29-34d':'Cull_D34',
   'Culling weight 29-34d (g)':'Cull_Wt_D34', 
    'Culling 35d':'Cull_D35', 
    'Culling weight 35d':'Cull_Wt_D35',
    'Culling 36-41d':'Cull_D41', 
    'Culling weight 36-41d (g)':'Cull_Wt_D41',
   'Culling 42d':'Cull_D42', 
    'Culling weight 42d (g)':'Cull_Wt_D42', 

       

     'Group FI 0-7d (g)':'GFI_D7', 
    'Group FI 8-14d (g)':'GFI_D14', 
    'Group FI 15-21d (g)':'GFI_D21',
   'Group FI 22-28d (g)':'GFI_D28', 
    'Group FI 29-35d (g)':'GFI_D35', 
    'Group FI 36-42d (g)':'GFI_D42'

    
    
   


    
}

E347.rename(columns=column_rename_map, inplace=True)
E347.head()

,ProjectID,House,Pen,Treatment,Init_Birds_D1,GBW_initial,GBW_7,GBW_14,GBW_21,GBW_28,...,Cull_D41,Cull_Wt_D41,Cull_D42,Cull_Wt_D42,GFI_D7,GFI_D14,GFI_D21,GFI_D28,GFI_D35,GFI_D42
0,E347,1,1,8,25,1051,5196,8320,16420,26290,...,0,0,0,0,4000,4700,10380,13460,18020,24240
1,E347,1,2,5,25,1041,5192,8220,16380,26360,...,0,0,0,0,4160,4640,10480,13520,17920,23160
2,E347,1,3,10,25,1034,5044,8200,16360,26030,...,0,0,0,0,3940,4740,10560,13500,18140,23500
3,E347,1,4,6,25,1023,4893,8100,16240,26010,...,0,0,0,0,3800,4640,10480,13640,17960,23740
4,E347,1,5,3,25,1043,5196,8220,16380,22160,...,0,0,0,0,3990,4680,10440,13300,14320,22020

In [481]:
E347.columns

Index(['ProjectID', 'House', 'Pen', 'Treatment', 'Init_Birds_D1',
       'GBW_initial', 'GBW_7', 'GBW_14', 'GBW_21', 'GBW_28', 'GBW_35',
       'GBW_42', 'Fnl_Birds_D7', 'Fnl_Birds_D14', 'Fnl_Birds_D21',
       'Fnl_Birds_D28', 'Fnl_Birds_D35', 'Fnl_Birds_D42', 'Mort_Wt_D6',
       'Mort_Wt_D7', 'Mort_Wt_D13', 'Mort_Wt_D14', 'Mort_Wt_D20',
       'Mort_Wt_D21', 'Mort_Wt_D27', 'Mort_Wt_D28', 'Mort_Wt_D34',
       'Mort_Wt_D35', 'Mort_Wt_D41', 'Mort_Wt_D42', 'Cull_D6', 'Cull_Wt_D6',
       'Cull_D7', 'Cull_Wt_D7', 'Cull_D13', 'Cull_Wt_D13', 'Cull_D14',
       'Cull_Wt_D14', 'Cull_D20', 'Cull_Wt_D20', 'Cull_D21', 'Cull_Wt_D21',
       'Cull_D27', 'Cull_Wt_D27', 'Cull_D28', 'Cull_Wt_D28', 'Cull_D34',
       'Cull_Wt_D34', 'Cull_D35', 'Cull_Wt_D35', 'Cull_D41', 'Cull_Wt_D41',
       'Cull_D42', 'Cull_Wt_D42', 'GFI_D7', 'GFI_D14', 'GFI_D21', 'GFI_D28',
       'GFI_D35', 'GFI_D42'],
      dtype='object')

In [482]:
E347.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE347.csv', index=False)

# E351

In [39]:
E351 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/E-351 Programa Pigmentex Colombia 31-05-2022.xlsx", "Performance Data")

In [40]:
E351["ProjectID"] = 'E351'
print(list(E351.columns))
E351.head()

['House', 'Line', 'Pen', 'Blind Trts ', 'Operator', '# Ini birds 1d', 'Group BWh, g', 'BW placement, g', 'Mortality 0-6d', 'Mortality weight 0-6d, g', 'Culling 0-6d', 'Culling weight 0-6d, g', 'Total Mort. + cull 0-6d, g', 'Mortality 7d', 'Mortality weight 7d, g', 'Culling 7d', 'Culling weight 7d, g', 'Total Weight Mort. + cull 7d, g', 'Discount 7d', 'Sampling weight 7d, g', 'Offered feed 1d, g', 'Offered water 1d, g', 'Leftover feed 7d, g', 'Leftover water 7d, g', 'Container weight, g', 'Container + birds weight, g', '# Fnl birds 7d', 'Average birds 0-7', 'Group BW7, g', 'BW7, g', 'Group FI 0-7d, g', 'FI 0-7d, g', 'Group WC 0-7d, g', 'WC 0-7d, g', 'Group BWG 0-7d, g', 'BWG 0-7d, g', 'Group BWG 0-7d corrected, g', 'BWG 0-7d corrected, g', 'FCR 0-7d, g:g', 'FCR 0-7d corrected, g:g', 'Mortality 0-7d, %', 'Culling 0-7d, %', 'Mort + Cull 0-7d, %', 'Wk2   (8-14d)', '# Ini birds 8d', 'Ini GBW8, g', 'Offered feed 8d, g', 'Leftover feed 14d, g', 'Offered Water 8d, g', 'Leftover water 14d, g', 'Mortality 8-13d', 'Mortality weight 8-13d, g', 'Culling 8-13d', 'Culling weight 8-13d, g', 'Total Mort. + cull 8-13d, g', 'Mortality 14d', 'Mortality weight 14d, g', 'Culling 14d', 'Culling weight 14d, g', 'Mort + Cull 14d (g)', 'Sampling 14d', 'Sampling weight 14d, g', 'Container weight, g.1', 'Container + birds weight, g.1', 'Fnl birds 14d', 'Average bird 8-14d', 'Weighted Av 8-14', 'Group BW14, g', 'BW14, g', 'Group FI 8-14d, g', 'FI 8-14d, g', 'FI 8-14d corrected av b, g', 'FI 8-14d corrected wav b, g', 'Unnamed: 73', 'Group WC 8-14d, g', 'WC 8-14d, g', 'Group BWG 8-14d, g', 'BWG 8-14d, g', 'Group BWG 8-14d corrected, g', 'BWG 8-14d  corrected, g', 'FCR 8-14d, g:g', 'FCR 8-14d corrected, g:g', 'Mortality 8-14d, %', 'Culling 8-14d, %', 'Mort + Cull 8-14d, %', 'Wk3  (15-21d)', '# Ini birds 15d', 'Ini GBW 15d, g', 'INI GBW 8D', 'Offered feed 15-21d, g', 'Offered water 15-21, g', '0FFERED FEED 8-21', 'Feed addition 15-21d, g (07/04/2022)', 'Leftover feed 15-21d, g', 'Leftover water 15-21, g', 'Mortality 15-20d', 'Mortality weight 15-20d, g', 'Culling 15-20d', 'Culling weight 15-20d, g', 'Total Mort. + cull 15-20d, g', 'Mortality 21d', 'Mortality weight 21d, g', 'Culling 21d', 'Culling weight 21d, g', 'Total Mort + Cull 21d, g', 'Sampling 21d', 'Sampling weight 21d, g', 'Container weight, g.2', 'Container + birds weight, g.2', '# Fnl birds 21d', 'Average bird 15-21', 'Weighted Av 15-21', 'Average bird 8-21', 'Weighted Av 8-21', 'Group BW 21d, g', 'BW 21d, g', 'Group FI 15-21d, g', 'FI 15-21d, g', 'Group WC 15-21d, g', 'WC 15-21d, g', 'FI 15-21d corrected av b, g', 'FI 15-21d corrected wav b, g', 'Group BWG 15-21d, g', 'BWG 15-21d, g', 'Group BWG 15-21d  corrected, g', 'BWG 15-21d  corrected, g', 'FCR 15-21d, g:g', 'FCR 15-21d corrected, g:g', 'Mortality 15-21d, %', 'Culling 15-21d, %', 'Mort + Cull 15-21d, %', 'Group FI 8-21d, g', 'FI 8-21d, g', 'FI 8-21d corrected av b,g', 'FI 8-21d corrected wav b,g', 'Group BWG 8-21d, g', 'BWG 8-21d, g', 'Group BWG 8-21d  corrected, g', 'BWG 8-21d  corrected, g', 'FCR 8-21d, g:g', 'FCR 8-21d corrected, g:g', 'Mortality 8-21d, %', 'Culling 8-21d, %', 'Mort + Cull 8-21d, %', 'Wk4  (22-28d)', '#Ini birds 22d', 'Ini GBW 22d, g', 'Offered feed 22-28d, g', 'Feed adition 22-28d, g', 'Leftover feed 22-28d, g', 'Offered water 22 -28d, g', 'Leftover water 22-28d, g', 'Mortality 22-27d', 'Mortality weight 22-27d, g', 'Culling 22-27d', 'Culling weight 22-27d, g', 'Total Mort. + Cull 22-27d, g', 'Mortality 28d', 'Mortality weight 28d, g', 'Culling 28d', 'Culling weight 28d, g', 'Total Mort + Cull 28d, g', 'Sampling 28d', 'Sampling weight 28d, g', 'Container weight, g.3', 'Container + birds weight, g.3', '# Fnl birds 28d', 'Average birds 22-28d', 'Weighted Av 22-28d', 'Group BW28d, g', 'BW28d, g', 'Group FI 22-28d, g', 'FI 22-28d, g', 'FI 22-28d corrected av b,g', 'FI 22-28d corrected wav b,g', 'Group WC 22-28d, g', 'WC 22-28d, g', 'Group BWG 22-28d, g', 'BWG 22-28d, g', 'Group BWG 22-28d corrected, g', 'BWG 22-28d corrected, g', 'FCR 22-28d, g:g', 'FCR22-28 corrected, g:g', 'Mortality 22-28d, %', 'Culling 22-28d, %', 'Mort + Cull 22-28d, %', 'Wk5   (29-35d)', '#Ini birds 29d', 'Ini GBW 29d, g', 'Offered feed 29-35d, g', 'Adition feed 29-35d, g', 'Leftover feed 29-35d, g', 'Offered water 29-35d, g', 'Leftover water 29-35d, g', 'Mortality 29-34d', 'Mortality weight 29-34d, g', 'Culling 29-34d', 'Culling weight 29-34d, g', 'Total Mort. + cull 29-34d, g', 'Mortality 35d', 'Mortality weight 35d, g', 'Culling 35d', 'Culling weight 35d', 'Total Mort + Cull 35d, g', 'Sampling 35d', 'Sampling weight 35d, g', 'Container weight (g)', 'Container + birds weight (g)', '# Fnl birds 35d', 'Average birds 29-35d', 'Weighted Av 29-35d', 'Group BW 35d, g', 'BW35d, g', 'Group FI 29-35d, g', 'FI 29-35d, g', 'FI 29-35d corrected av b, g', 'FI 29-35d corrected wav b, g', 'Group WC 29-35d, g', 'WC 29 - 35d, g', 'Group BWG 29-35d, g', 'BWG 29-35d, g', 'Group BWG 29-35d corrected, g', 'BWG 29-35d corrected, g', 'FCR 29-35d, g:g', 'FCR 29-35d corrected, g:g', 'Mortality 29-35d, %', 'Culling 29-35d, %', 'Mort + Cull 29-35d, %', 'Wk5   (36-42d)', '# Ini Birds 36d', 'Ini GBW 36d, g', 'Offered feed 36-42d, g', 'Adition feed 36-42d, g', 'Leftover feed 36-42d, g', 'Offered water 26-42d, g', 'Leftover water 36 - 42d, g', 'Mortality 36-41d', 'Mortality weight 36-41d, g', 'Culling 36-41d', 'Culling weight 36-41d, g', 'Total Mort. + cull 36-41d, g', 'Mortality 42d', 'Mortality weight 42d, g', 'Culling 42d', 'Culling weight 42d, g', 'Total Mort + Cull 42d, g', 'Sampling 42d', 'Sampling weight 42d, g', 'Container weight, g.4', 'Container + birds weight, g.4', '# Fnl birds 42d', 'Average birds 36-42d', 'Weighted av birds 36-42d', 'Group BW 42d, g', 'BW 42d, g', 'Group FI 36-42d, g', 'FI 36-42d, g', 'FI 36-42d corrected av b, g', 'FI 36-42d corrected wav b, g', 'Group WC 36-42d, g', 'WC 36 - 42d, g', 'Group BWG 36-42d, g', 'BWG 36-42d, g', 'Group BWG 36-42d corrected, g', 'BWG 36-42d corrected, g', 'FCR 36-42d, g:g', 'FCR 36-42d corrected, g:g', 'Mortality 36-42d, %', 'Culling 36-42d, %', 'Mort + Cull 36-42d, %', 'FI 22-42d, g', 'FI 22-42d corrected av b, g', 'FI 22-42d corrected wav b, g', 'Group BWG 22-42d, g', 'BWG 22-42d, g', 'Group BWG 22-42d  corrected, g', 'BWG 22-42d  corrected, g', 'FCR 22-42d, g:g', 'FCR 22-42d corrected, g:g', 'Mortality 22-42d, %', 'Culling 22-42d, %', 'Mort + Cull 22-42d, %', 'ProjectID']

,House,Line,Pen,Blind Trts,Operator,# Ini birds 1d,"Group BWh, g","BW placement, g",Mortality 0-6d,"Mortality weight 0-6d, g",...,"Group BWG 22-42d, g","BWG 22-42d, g","Group BWG 22-42d corrected, g","BWG 22-42d corrected, g","FCR 22-42d, g:g","FCR 22-42d corrected, g:g","Mortality 22-42d, %","Culling 22-42d, %","Mort + Cull 22-42d, %",ProjectID
0,1.0,A,1.0,10.0,A,30.0,1281.0,42.700000,0.0,0.0,...,55340.0,2128.461538,55340.0,2128.461538,1.570112,1.570112,0.000000,0.000000,0.000000,E351
1,1.0,A,2.0,1.0,A,30.0,1267.0,42.233333,0.0,0.0,...,54290.0,2088.076923,54290.0,2088.076923,1.648554,1.648554,0.000000,0.000000,0.000000,E351
2,1.0,A,3.0,9.0,A,30.0,1302.0,43.400000,1.0,136.0,...,50230.0,2092.916667,50230.0,2092.916667,1.597054,1.597054,0.000000,0.000000,0.000000,E351
3,1.0,A,4.0,11.0,A,30.0,1286.0,42.866667,1.0,176.0,...,41990.0,1999.523810,46676.0,2222.666667,1.709606,1.537972,12.862319,0.000000,12.862319,E351
4,1.0,A,5.0,8.0,A,30.0,1310.0,43.666667,1.0,176.0,...,46200.0,2008.695652,48829.0,2123.000000,1.659506,1.570156,0.000000,11.858974,11.858974,E351

In [464]:
E351[[i for i in E351.columns if "Group FI" in i]].columns

Index(['Group FI 0-7d, g', 'Group FI 8-14d, g', 'Group FI 15-21d, g',
       'Group FI 8-21d, g', 'Group FI 22-28d, g', 'Group FI 29-35d, g',
       'Group FI 36-42d, g'],
      dtype='object')

In [41]:
E351 = E351[['ProjectID', 'House', 'Pen', 'Blind Trts ', '# Ini birds 1d',
             
             'Group BWh, g', 'Group BW7, g', 'Group BW14, g', 'Group BW 21d, g', 'Group BW28d, g', 'Group BW 35d, g', 'Group BW 42d, g',
             
             
             '# Fnl birds 7d', 'Fnl birds 14d', '# Fnl birds 21d', '# Fnl birds 28d','# Fnl birds 35d', '# Fnl birds 42d',

              
               
             'Mortality weight 0-6d, g', 'Mortality weight 7d, g',
       'Mortality weight 8-13d, g', 'Mortality weight 14d, g',
       'Mortality weight 15-20d, g', 'Mortality weight 21d, g',
       'Mortality weight 22-27d, g', 'Mortality weight 28d, g',
       'Mortality weight 29-34d, g', 'Mortality weight 35d, g',
       'Mortality weight 36-41d, g', 'Mortality weight 42d, g',
             
           'Culling 0-6d', 'Culling weight 0-6d, g', 'Culling 7d',
       'Culling weight 7d, g', 'Culling 8-13d',
       'Culling weight 8-13d, g', 'Culling 14d', 'Culling weight 14d, g',
        'Culling 15-20d', 'Culling weight 15-20d, g',
       'Culling 21d', 'Culling weight 21d, g',
        'Culling 22-27d', 'Culling weight 22-27d, g',
       'Culling 28d', 'Culling weight 28d, g', 
       'Culling 29-34d', 'Culling weight 29-34d, g', 'Culling 35d',
       'Culling weight 35d', 'Culling 36-41d',
       'Culling weight 36-41d, g', 'Culling 42d', 'Culling weight 42d, g',


               

        'Group FI 0-7d, g', 'Group FI 8-14d, g', 'Group FI 15-21d, g',
        'Group FI 22-28d, g', 'Group FI 29-35d, g',
       'Group FI 36-42d, g'
               
               
               
             ]]
E351.head()

,ProjectID,House,Pen,Blind Trts,# Ini birds 1d,"Group BWh, g","Group BW7, g","Group BW14, g","Group BW 21d, g","Group BW28d, g",...,Culling 36-41d,"Culling weight 36-41d, g",Culling 42d,"Culling weight 42d, g","Group FI 0-7d, g","Group FI 8-14d, g","Group FI 15-21d, g","Group FI 22-28d, g","Group FI 29-35d, g","Group FI 36-42d, g"
0,E351,1.0,1.0,10.0,30.0,1281.0,6139.0,0.0,25740.0,0.0,...,0.0,0.0,0.0,0.0,4720.0,0.0,25790.0,25490,30930,30470
1,E351,1.0,2.0,1.0,30.0,1267.0,5903.0,12730.0,25570.0,0.0,...,0.0,0.0,0.0,0.0,4430.0,8630.0,17070.0,25620,32930,30950
2,E351,1.0,3.0,9.0,30.0,1302.0,5775.0,0.0,23710.0,0.0,...,0.0,0.0,0.0,0.0,4420.0,0.0,24070.0,22580,29490,28150
3,E351,1.0,4.0,11.0,30.0,1286.0,5578.0,0.0,23050.0,0.0,...,0.0,0.0,0.0,0.0,4220.0,0.0,23840.0,22680,27690,25510
4,E351,1.0,5.0,8.0,30.0,1310.0,5782.0,12060.0,23940.0,0.0,...,1.0,1173.0,0.0,0.0,4320.0,7990.0,16160.0,22670,28710,27430

In [469]:
E351.columns

Index(['ProjectID', 'House', 'Pen', 'Treatment', 'Init_Birds_D1',
       'GBW_initial', 'GBW_7', 'GBW_14', 'GBW_21', 'GBW_28', 'GBW_35',
       'GBW_42', 'Fnl_Birds_D7', 'Fnl_Birds_D14', 'Fnl_Birds_D21',
       'Fnl_Birds_D27', 'Fnl_Birds_D35', 'Fnl_Birds_D42',
       'Mortality weight 0-6d, g', 'Mortality weight 7d, g',
       'Mortality weight 8-13d, g', 'Mortality weight 14d, g',
       'Mortality weight 15-20d, g', 'Mortality weight 21d, g',
       'Mortality weight 22-27d, g', 'Mortality weight 28d, g',
       'Mortality weight 29-34d, g', 'Mortality weight 35d, g',
       'Mortality weight 36-41d, g', 'Mortality weight 42d, g', 'Cull_D6',
       'Culling weight 0-6d, g', 'Cull_D7', 'Culling weight 7d, g', 'Cull_D13',
       'Culling weight 8-13d, g', 'Cull_D14', 'Culling weight 14d, g',
       'Cull_D20', 'Culling weight 15-20d, g', 'Cull_D21',
       'Culling weight 21d, g', 'Cull_D26', 'Culling weight 22-27d, g',
       'Cull_D27', 'Culling weight 28d, g', 'Cull_D34',
       'Culling weight 29-34d, g', 'Cull_D35', 'Cull_Wt_D35', 'Cull_D41',
       'Culling weight 36-41d, g', 'Cull_D42', 'Culling weight 42d, g',
       'Culling 36-42d, %', 'Group FI 0-7d, g', 'Group FI 8-14d, g',
       'Group FI 15-21d, g', 'Group FI 22-28d, g', 'Group FI 29-35d, g',
       'Group FI 36-42d, g'],
      dtype='object')

In [42]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Blind Trts ': 'Treatment',
    '# Ini birds 1d':'Init_Birds_D1', 


    'Group BWh, g':'GBW_initial',  
    'Group BW7, g':'GBW_7', 
    'Group BW14, g':'GBW_14', 
    'Group BW 21d, g':'GBW_21',
    'Group BW28d, g':'GBW_28',
    'Group BW 35d, g':'GBW_35', 
    'Group BW 42d, g':'GBW_42',
             
             
     '# Fnl birds 7d':'Fnl_Birds_D7', 
    'Fnl birds 14d':'Fnl_Birds_D14', 
    '# Fnl birds 21d':'Fnl_Birds_D21', 
    '# Fnl birds 28d':'Fnl_Birds_D27', 
    '# Fnl birds 35d':'Fnl_Birds_D35', 
    '# Fnl birds 42d':'Fnl_Birds_D42',

     'Mortality weight 0-6d, g':'Mort_Wt_D6',
    'Mortality weight 7d, g':'Mort_Wt_D7',
       'Mortality weight 8-13d, g':'Mort_Wt_D13', 
    'Mortality weight 14d, g':'Mort_Wt_D14',
       'Mortality weight 15-20d, g' :'Mort_Wt_D20', 
    'Mortality weight 21d, g':'Mort_Wt_D21',
       'Mortality weight 22-27d, g' :'Mort_Wt_D27',
    'Mortality weight 28d, g':'Mort_Wt_D28',
       'Mortality weight 29-34d, g':'Mort_Wt_D34', 
    'Mortality weight 35d, g':'Mort_Wt_D35',
       'Mortality weight 36-41d, g' :'Mort_Wt_D41', 
    'Mortality weight 42d, g':'Mort_Wt_D42',


             
           'Culling 0-6d':'Cull_D6',
    'Culling weight 0-6d, g' :'Cull_Wt_D6', 
    'Culling 7d':'Cull_D7',
       'Culling weight 7d, g':'Cull_Wt_D7', 
    'Culling 8-13d':'Cull_D13',
       'Culling weight 8-13d, g':'Cull_Wt_D13', 
    'Culling 14d' :'Cull_D14',
    'Culling weight 14d, g':'Cull_Wt_D14', 
        'Culling 15-20d' :'Cull_D20',
    'Culling weight 15-20d, g':'Cull_Wt_D20', 
       'Culling 21d' :'Cull_D21',
    'Culling weight 21d, g':'Cull_Wt_D21', 
        'Culling 22-27d' :'Cull_D27',
    'Culling weight 22-27d, g':'Cull_Wt_D27', 
       'Culling 28d':'Cull_D28',
    'Culling weight 28d, g':'Cull_Wt_D28', 
       'Culling 29-34d':'Cull_D34', 
    'Culling weight 29-34d, g':'Cull_Wt_D34', 
    'Culling 35d':'Cull_D35',
       'Culling weight 35d':'Cull_Wt_D35', 
    'Culling 36-41d':'Cull_D41',
       'Culling weight 36-41d, g':'Cull_Wt_D41', 
    'Culling 42d':'Cull_D42',
    'Culling weight 42d, g':'Cull_Wt_D42', 




    


    

        'Group FI 0-7d, g':'GFI_D7', 
    'Group FI 8-14d, g':'GFI_D14', 
    'Group FI 15-21d, g':'GFI_D21',
        'Group FI 22-28d, g':'GFI_D28', 
    'Group FI 29-35d, g':'GFI_D35',
       'Group FI 36-42d, g':'GFI_D42',

    

    
}

E351.rename(columns=column_rename_map, inplace=True)
E351.head()

,ProjectID,House,Pen,Treatment,Init_Birds_D1,GBW_initial,GBW_7,GBW_14,GBW_21,GBW_28,...,Cull_D41,Cull_Wt_D41,Cull_D42,Cull_Wt_D42,GFI_D7,GFI_D14,GFI_D21,GFI_D28,GFI_D35,GFI_D42
0,E351,1.0,1.0,10.0,30.0,1281.0,6139.0,0.0,25740.0,0.0,...,0.0,0.0,0.0,0.0,4720.0,0.0,25790.0,25490,30930,30470
1,E351,1.0,2.0,1.0,30.0,1267.0,5903.0,12730.0,25570.0,0.0,...,0.0,0.0,0.0,0.0,4430.0,8630.0,17070.0,25620,32930,30950
2,E351,1.0,3.0,9.0,30.0,1302.0,5775.0,0.0,23710.0,0.0,...,0.0,0.0,0.0,0.0,4420.0,0.0,24070.0,22580,29490,28150
3,E351,1.0,4.0,11.0,30.0,1286.0,5578.0,0.0,23050.0,0.0,...,0.0,0.0,0.0,0.0,4220.0,0.0,23840.0,22680,27690,25510
4,E351,1.0,5.0,8.0,30.0,1310.0,5782.0,12060.0,23940.0,0.0,...,1.0,1173.0,0.0,0.0,4320.0,7990.0,16160.0,22670,28710,27430

In [43]:
E351.columns

Index(['ProjectID', 'House', 'Pen', 'Treatment', 'Init_Birds_D1',
       'GBW_initial', 'GBW_7', 'GBW_14', 'GBW_21', 'GBW_28', 'GBW_35',
       'GBW_42', 'Fnl_Birds_D7', 'Fnl_Birds_D14', 'Fnl_Birds_D21',
       'Fnl_Birds_D27', 'Fnl_Birds_D35', 'Fnl_Birds_D42', 'Mort_Wt_D6',
       'Mort_Wt_D7', 'Mort_Wt_D13', 'Mort_Wt_D14', 'Mort_Wt_D20',
       'Mort_Wt_D21', 'Mort_Wt_D27', 'Mort_Wt_D28', 'Mort_Wt_D34',
       'Mort_Wt_D35', 'Mort_Wt_D41', 'Mort_Wt_D42', 'Cull_D6', 'Cull_Wt_D6',
       'Cull_D7', 'Cull_Wt_D7', 'Cull_D13', 'Cull_Wt_D13', 'Cull_D14',
       'Cull_Wt_D14', 'Cull_D20', 'Cull_Wt_D20', 'Cull_D21', 'Cull_Wt_D21',
       'Cull_D27', 'Cull_Wt_D27', 'Cull_D28', 'Cull_Wt_D28', 'Cull_D34',
       'Cull_Wt_D34', 'Cull_D35', 'Cull_Wt_D35', 'Cull_D41', 'Cull_Wt_D41',
       'Cull_D42', 'Cull_Wt_D42', 'GFI_D7', 'GFI_D14', 'GFI_D21', 'GFI_D28',
       'GFI_D35', 'GFI_D42'],
      dtype='object')

In [44]:
E351.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE351.csv', index=False)

### ETL for correlation ---

In [23]:
E351 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/E-351 Programa Pigmentex Colombia 31-05-2022.xlsx", "Data to stat") 

E351["ProjectID"] = 'E351'
print(list(E351.columns))
E351.head()

['House', 'Line', 'Block 1', 'Pen', 'Operator', 'Trts', 'Trts.', 'Block 2', 'Formulated EM Pst, Kcal/kg', 'Formulated EM St, kcal/kg', 'Formulated EM Gr, kcal/kg', 'Formulated EM Fn, kcal/kg', 'Formulated dLys Pst, %', 'Formulated dLys St, %', 'Formulated dLys Gr, %', 'Formulated dLys Fn, %', 'Analyzed Ca Pst, %', 'Analyzed Fat St, %', 'Analyzed Fat Fn, %', 'Oil St; %', 'Oil Fn, %', 'Zeaxanthin Pre-St, ppm', 'Zeaxanthin St, ppm', 'Zeaxanthin Fn, ppm', 'Yellow Xantophyll 4% St, ppm', 'Yellow Xantophyll 4% Fn, ppm', 'Canthaxanthin St, ppm', 'Canthaxanthin Fn, ppm', 'Bixin St, ppm', 'Bixin Fn, ppm', 'Pst diet cost, $/Kg', 'St diet cost, $/Kg', 'Gr diet cost, $/Kg', 'Fn diet cost, $/Kg', 'BW1, g', 'BW 7d, g', 'BW 8d, g', 'FI 0-7d, g', 'WC 0-7d, g', 'BWG 0-7d, g', 'BWG 0-7d, g correct', 'FCR 0-7d, g:g', 'FCR 0-7d corrected, g:g', 'Mortality 0-7d, %', 'Culling 0-7d, %', 'Mort + Cull 0-7d, %', 'kg/m2 0-7d', 'EM intake 0-7d, kcal', 'kcal intake/Kg 0-7d', 'g dLys intake 0-7d', 'g dLys intake/kg BWG 0-7d', 'Zeaxntin Intake 8-14d, mg', '$/kg BWG 0-7d', 'BW 14d, g', 'FI 8-14d, g', 'FI 8-14d corrected av b, g', 'FI 8-14d corrected wav b, g', 'BWG 8-14d, g', 'BWG 8-14d correct, g', 'FCR 8-14d, g:g', 'FCR 8-14d corrected, g:g', 'Mortality 8-14d, %', 'Culling 8-14d, %', 'Mort + Cull 8-14d, %', 'kg/m2 8-14d', 'EM intake 8-14d, kcal', 'kcal intake/Kg 8-14d', 'g dLys intake 8-14d', 'g dLys intake/kg BWG 8-14d', 'Fat intake 8-14d', 'Fat intake/kg BWG 8-14d', 'Zeaxntin Intake 8-14d, mg.1', 'Yellow Xant Intake 8-14d, mg', 'Canthaxantin Intake 8-14d, mg', 'Total Xantophyll intake 8-14d, mg', 'Xant + Cant intake 8-14, mg', '$/kg BWG 8-14d', 'BW 21d, g', 'FI 15-21d, g', 'FI 15-21d corrected av b, g', 'WC 15-21d, g', 'FI 15-21d corrected wav b, g', 'BWG 15-21d, g', 'BWG 15-21d correct, g', 'FCR 15-21d, g:g', 'FCR 15-21d corrected, g:g', 'Mortality 15-21d, %', 'Culling 15-21d, %', 'Mort + Cull 15-21d, %', 'kg/m2 15-21d', 'EM intake 15-21dl kcal', 'kcal intake/Kg 15-21d', 'g dLys intake 15-21d', 'g dLys intake/kg BWG 15-21d', 'Fat intake 15-21d', 'Fat intake/kg BWG 15-21d', 'Zeaxntin Intake 15-21d, mg', 'Yellow Xant Intake 15-21d, mg', 'Canthaxantin Intake 15-21d, mg', 'Total Xantophyll intake 15-21d, mg', 'Xant + Cant intake 15-21, mg', '$/kg BWG 15-21d', 'FI 8-21d, g', 'WC 0-21d, g', 'FI 8-21d corrected av b, g', 'FI 8-21d corrected wav b, g', 'BWG 8-21d, g', 'BWG 8-21d correct, g', 'FCR 8-21d, g:g', 'FCR 8-21d corrected, g:g', 'Mortality 8 - 21d, %', 'Culling 8 - 21d, %', 'Mort + Cull 8 - 21d, %', 'EM intake 8-21d, kcal', 'kcal intake/Kg 8-21d', 'g dLys intake 8-21d', 'g dLys intake/kg BWG 8-21d', 'Fat intake 8-21d', 'Fat intake/kg BWG 8-21d', 'Added Oil Intake 8-21, g', 'Zeaxntin Intake 8-21d, mg', 'Yellow Xant Intake 8-21d, mg', 'Canthaxantin Intake 8-21d, mg', 'Total Xantophyll intake 8-21d, mg', 'Xant + Cant intake 8-21, mg', '$/kg BWG 8-21d', 'BW 28d, g', 'FI 22-28d, g', 'FI 22-28d corrected av b, g', 'WC 22-28d, g', 'FI 22-28d corrected wav b, g', 'BWG 22-28d, g', 'BWG 22-28d correct, g', 'FCR 22-28d, g:g', 'FCR 22-28d corrected, g:g', 'Mortality 22 - 28d, %', 'Culling 22 - 28d, %', 'Mort + Cull 22 - 28d, %', 'kg/m2 22-28d', 'EM intake 22-28d, kcal', 'kcal intake/Kg 22-28d', 'g dLys intake 22-28d', 'g dLys intake/kg BWG 22-28d', 'Fat intake 22-28d, g', 'Zeaxntin Intake 22-28d, mg', 'Yellow Xant Intake 22-28d, mg', 'Canthaxantin Intake 22-28d, mg', 'Total Xantophyll intake 22-28d, mg', 'Bixin intake 22-28d, mg', 'Bix + Xant + Cant intake 22-28, mg', '$/kg BWG 22-28d', 'BW 35d, g', 'FI 29-35d, g', 'FI 29-35d corrected av b, g', 'WC 29-35d, g', 'FI 29-35d corrected wav b, g', 'BWG 29-35d, g', 'BWG 29-35d correct, g', 'FCR 29-35d, g:g', 'FCR 29-35d corrected, g:g', 'Mortality 29 - 35d, %', 'Culling 29 - 35d, %', 'Mort + Cull 29 - 35d, %', 'kg/m2 29-35d', 'EM intake 29-35d (kcal)', 'kcal intake/Kg 29-35d', 'g dLys intake 29-35d', 'g dLys intake/kg BWG 29-35d', 'Fat intake 29-35d, g', 'Zeaxntin Intake 29-35d, mg', 'Yellow Xant Intake 29-35d, mg', 'Canthaxantin Intake 29-35d, mg', 'Total Xantophyll intake 29-35d, mg', 'Bixin intake 29-35d, mg', 'Bix + Xant + Cant intake 29-35, mg', '$/kg BWG 29-35d', 'BW 42d, g', 'FI 36-42d, g', 'WC 36-42d, g', 'FI 36-42d corrected av b, g', 'FI 36-42d corrected av b, g.1', 'BWG 36-42d, g', 'BWG 36-42d, g correct', 'FCR 36-42d, g:g', 'FCR 36-42d corrected, g:g', 'Mortality 36 - 42d, %', 'Culling 36 - 42d, %', 'Mort + Cull 36 - 42d, %', 'kg/m2 36-42d', 'EM intake 36-42d, kcal', 'kcal intake/Kg 36-42d', 'g dLys intake 36-42d', 'g dLys intake/kg BWG 36-42d', 'Fat intake 36-42d, g', 'Zeaxntin Intake 36-42d, mg', 'Yellow Xant Intake 36-42d, mg', 'Canthaxantin Intake 36-42d, mg', 'Total Xantophyll intake 36-42d, mg', 'Bixin intake 36-42d, mg', 'Bix + Xant + Cant intake 36-42, mg', '$/kg BWG 36-42d', 'FI 22-42, g', 'WC 22-42, g', 'FI 22-42 corrected av b, g', 'FI 22-42 corrected wav b, g', 'BWG 22-42d, g', 'BWG 22-42d corrected, g', 'FCR 22-42d, g:g', 'FCR 22-42d corrected, g:g', 'Mortality 22 - 42d, %', 'Culling 22 - 42d, %', 'Mort + Cull 22 - 42d, %', 'EM intake 22-42d, kcal', 'kcal intake/Kg 22-42d', 'g dLys intake 22-42d', 'g dLys intake/kg BWG 22-42d', 'Fat intake 22-42d, g', 'Fat intake/BWG 22-42d, g:kg', 'Added Oil intake 22-42d, %', 'Zeaxntin Intake 22-42d, mg', 'Yellow Xant Intake 22-42d, mg', 'Canthaxantin Intake 22-42d, mg', 'Total Xantophyll intake 22-42d, mg', 'Bixin intake 22-42d, mg', 'Bix + Xant + Cant intake 22-42, mg', '$/kg BWG 22-42d', 'FI 8-42d, g', 'WC 0-42d, g', 'FI 8-42d corrected av b, g', 'FI 8-42d corrected wav b, g', 'BWG 8-42d, g', 'BWG 8-42d correct, g', 'FCR 8-42d, g:g', 'FCR 8-42d corrected, g:g', 'Mortality 8 - 42d, %', 'Culling 8 - 42d, %', 'Mort + Cull 8 - 42d, %', 'Fat intake 8-42d, g', 'Fat intake/BWG 8-42d, g:kg', 'Added oil intake 8-42d, g', 'Zeaxntin Intake 0-42d, mg', 'Yellow Xant Intake 0-42d, mg', 'Canthaxantin Intake 0-42d, mg', 'Total Xantophyll intake 0-42d, mg', 'Bixin intake 0-42d, mg', 'Bix + Xant + Cant intake 0-42, mg', 'ProjectID']

,House,Line,Block 1,Pen,Operator,Trts,Trts.,Block 2,"Formulated EM Pst, Kcal/kg","Formulated EM St, kcal/kg",...,"Fat intake 8-42d, g","Fat intake/BWG 8-42d, g:kg","Added oil intake 8-42d, g","Zeaxntin Intake 0-42d, mg","Yellow Xant Intake 0-42d, mg","Canthaxantin Intake 0-42d, mg","Total Xantophyll intake 0-42d, mg","Bixin intake 0-42d, mg","Bix + Xant + Cant intake 0-42, mg",ProjectID
0,1,A,1A,1,A,10,NaN,1,NaN,3078,...,290.619346,99.708414,164.718115,33.337321,185.075700,6.683846,218.413021,50.262523,275.359390,E351
1,1,A,1A,2,A,1,NaN,1,NaN,3078,...,297.280385,103.632012,168.501923,34.009300,0.000000,0.000000,34.009300,0.000000,34.009300,E351
2,1,A,1A,3,A,9,NaN,1,NaN,3078,...,289.774082,101.272396,163.529784,33.246879,116.018175,3.008250,149.265054,0.000000,152.273304,E351
3,1,A,1A,4,A,11,NaN,1,NaN,3078,...,294.202759,107.297282,165.493183,33.653137,163.016080,8.495731,196.669216,133.756783,338.921730,E351
4,1,A,1A,5,A,8,NaN,1,NaN,3078,...,284.729769,104.261238,159.993870,32.625054,115.001850,2.981898,147.626904,0.000000,150.608802,E351

In [29]:
E351[[i for i in E351.columns if "FCR 0-" in i]].columns

Index(['FCR 0-7d, g:g', 'FCR 0-7d corrected, g:g'], dtype='object')

In [30]:
E351 = E351[['ProjectID', 'House', 'Pen', 'Trts', 
             
            'FCR 36-42d corrected, g:g',


             'BWG 36-42d, g correct',

                                    


             'BW 42d, g'

             
             
               
             ]]
E351.head()

,ProjectID,House,Pen,Trts,"FCR 36-42d corrected, g:g","BWG 36-42d, g correct","BW 42d, g"
0,E351,1,1,10,0.375802,3118.461538,3118.461538
1,E351,1,2,1,0.387553,3071.538462,3071.538462
2,E351,1,3,9,1.657833,707.500000,3080.833333
3,E351,1,4,11,0.379834,3198.142857,3097.142857
4,E351,1,5,8,0.384642,3100.565217,3049.565217

In [31]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Trts': 'Treatment',



    'FCR 36-42d corrected, g:g':'FCRbefore', 
    'BWG 36-42d, g correct':'BWGbefore', 
    'BW 42d, g':'BW'




    
}

E351.rename(columns=column_rename_map, inplace=True)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_3447/1503644421.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  E351.rename(columns=column_rename_map, inplace=True)

In [32]:
E351["Age"] = '42'
E351.head()

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_3447/1046271129.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  E351["Age"] = '42'

  ProjectID  House  Pen  Treatment  FCRbefore    BWGbefore           BW Age
0      E351      1    1         10   0.375802  3118.461538  3118.461538  42
1      E351      1    2          1   0.387553  3071.538462  3071.538462  42
2      E351      1    3          9   1.657833   707.500000  3080.833333  42
3      E351      1    4         11   0.379834  3198.142857  3097.142857  42
4      E351      1    5          8   0.384642  3100.565217  3049.565217  42

In [33]:
E351.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE351.csv', index=False)

# E352

In [34]:
E352 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Broiler Pigmentex 04-11-2022.xlsx", "Performance Data") 
E352["ProjectID"] = 'E352'
print(list(E352.columns))
E352.head()

['House', 'Line', 'Pen', 'Blind Trts ', 'Diet', 'Operator', '# Ini birds 1d', 'Group BWh, g', 'BW placement, g', 'Mortality 0-6d', 'Mortality weight 0-6d, g', 'Culling 0-6d', 'Culling weight 0-6d, g', 'Total Mort. + cull 0-6d, g', 'Mortality 7d', 'Mortality weight 7d, g', 'Culling 7d', 'Culling weight 7d, g', 'Total Weight Mort. + cull 7d, g', 'Sampling 7d', 'Sampling weight 7d, g', 'Offered feed 1d, g', 'Offered water 1d, g', 'Leftover feed 7d, g', 'Leftover water 7d, g', 'Container weight, g', 'Container + birds weight, g', '# Fnl birds 7d', 'Group BW7, g', 'BW7, g', 'Group FI 0-7d, g', 'FI 0-7d, g', 'Group WC 0-7d, g', 'WC 0-7d, g', 'Group BWG 0-7d, g', 'BWG 0-7d, g', 'Group BWG 0-7d corrected, g', 'BWG 0-7d corrected, g', 'FCR 0-7d, g:g', 'FCR 0-7d corrected, g:g', 'Mortality 0-7d, %', 'Culling 0-7d, %', 'Mort + Cull 0-7d, %', 'Wk2   (8-14d)', '# Ini birds 8d', 'Ini GBW8, g', 'Offered feed 8d, g', 'Leftover feed 14d, g', 'Offered Water 8d, g', 'Leftover water 14d, g', 'Mortality 8-13d', 'Mortality weight 8-13d, g', 'Culling 8-13d', 'Culling weight 8-13d, g', 'Total Mort. + cull 8-13d, g', 'Mortality 14d', 'Mortality weight 14d, g', 'Culling 14d', 'Culling weight 14d, g', 'Mort + Cull 14d (g)', 'Sampling 14d', 'Sampling weight 14d, g', 'Container weight, g.1', 'Container + birds weight, g.1', 'Fnl birds 14d', 'Group BW14, g', 'BW14, g', 'Group FI 8-14d, g', 'FI 8-14d, g', 'Group WC 8-14d, g', 'WC 8-14d, g', 'Group BWG 8-14d, g', 'BWG 8-14d, g', 'Group BWG 8-14d corrected, g', 'BWG 8-14d  corrected, g', 'FCR 8-14d, g:g', 'FCR 8-14d corrected, g:g', 'Mortality 8-14d, %', 'Culling 8-14d, %', 'Mort + Cull 8-14d, %', 'Wk3  (15-21d)', '# Ini birds 8d.1', 'Ini GBW 8d, g', 'Offered feed 8-21, g', 'Offered water 15-21, g', 'Feed addition 8-21, g', 'Leftover feed 8-21d, g', 'Leftover water 15-21, g', 'Mortality 8-20d', 'Mortality weight 8-20d, g', 'Culling 8-20d', 'Culling weight 8-20d, g', 'Total Mort. + cull 8-20d, g', 'Mortality 21d', 'Mortality weight 21d, g', 'Culling 21d', 'Culling weight 21d, g', 'Total Mort + Cull 21d, g', 'Sampling 21d', 'Sampling weight 21d, g', 'Container weight, g.2', 'Container + birds weight, g.2', '# Fnl birds 21d', 'Group BW 21d, g', 'BW 21d, g', 'Group FI 8-21d, g', 'FI 8-21d, g', 'Group WC 8-21d, g', 'WC 8-21d, g', 'Group BWG 8-21d, g', 'BWG 8-21d, g', 'Group BWG 8-21d  corrected, g', 'BWG 8-21d  corrected, g', 'FCR 8-21d, g:g', 'FCR 8-21d corrected, g:g', 'Mortality 8-21d, %', 'Culling 8-21d, %', 'Mort + Cull 8-21d, %', 'Wk4  (22-28d)', '#Ini birds 22d', 'Ini GBW 22d, g', 'Offered feed 22-27d, g', 'Feed adition 22-27d, g', 'Leftover feed 22-27d, g', 'Mortality 22-26d', 'Mortality weight 22-26d, g', 'Culling 22-26d', 'Culling weight 22-26d, g', 'Total Mort. + Cull 22-26d, g', 'Mortality 27d', 'Mortality weight 27d, g', 'Culling 27d', 'Culling weight 27d, g', 'Total Mort + Cull 27d, g', 'Sampling 27d', 'Sampling weight 27d, g', 'Container weight, g.3', 'Container + birds weight, g.3', 'AV Final birds 27d', '# Fnl birds 27d', 'Group BW28d, g', 'BW28d, g', 'Group FI 22-27d, g', 'FI 22-27d, g', 'Group WC 22-28d, g', 'WC 22-28d, g', 'FI 22-27d, g corrected', 'Group BWG 22-28d, g', 'BWG 22-28d, g', 'Group BWG 22-28d corrected, g', 'BWG 22-28d corrected, g', 'FCR 22-28d, g:g', 'FCR22-28 corrected, g:g', 'Mortality 22-27d, %', 'Culling 22-27d, %', 'Mort + Cull 22-27d, %', 'Wk5   (28-34d)', '#Ini birds 28d', 'Ini GBW 28d, g', 'Offered feed 28-34d, g', 'Adition feed 28-34d, g', 'Leftover feed 28-34d, g', 'Mortality 28-33d', 'Mortality weight 28-33d, g', 'Culling 28-33d', 'Culling weight 28-33d, g', 'Total Mort. + cull 28-33d, g', 'Mortality 34d', 'Mortality weight 34d, g', 'Culling 34d', 'Culling weight 34d', 'Total Mort + Cull 34d, g', 'Sampling 34d', 'Sampling weight 34d, g', 'Container weight (g)', 'Container + birds weight (g)', 'Av Fnl birds 28-34d', '# Fnl birds 34d', 'Group BW 35d, g', 'BW35d, g', 'Group FI 28-34d, g', 'FI 28-34d, g', 'FI 28-34d, g corrected', 'Group BWG 29-35d, g', 'BWG 29-35d, g', 'Group BWG 29-35d corrected, g', 'BWG 29-35d corrected, g', 'FCR 29-35d, g:g', 'FCR 29-35d corrected, g:g', 'Mortality 29-35d, %', 'Culling 29-35d, %', 'Mort + Cull 29-35d, %', 'Wk5   (36-42d)', '# Ini Birds 35d', 'Ini GBW 35d, g', 'Offered feed 35-41d, g', 'Adition feed 35-41d, g', 'Leftover feed 35-41d, g', 'Mortality 35-40d', 'Mortality weight 35-40d, g', 'Culling 35-40d', 'Culling weight 35-40d, g', 'Total Mort. + cull 35-40d, g', 'Mortality 41d', 'Mortality weight 41d, g', 'Culling 41d', 'Culling weight 41d, g', 'Total Mort + Cull 41d, g', 'Sampling 41d', 'Sampling weight 41d, g', 'Container weight, g.4', 'Container + birds weight, g.4', 'Av Birds 35-42d', '# Fnl birds 42d', 'Group BW 42d, g', 'BW 42d, g', 'Group FI 36-42d, g', 'FI 36-42d, g', 'Group WC 36-42d, g', 'WC 36 - 42d, g', 'Group BWG 36-42d, g', 'BWG 36-42d, g', 'Group BWG 36-42d corrected, g', 'BWG 36-42d corrected, g', 'FCR 36-42d, g:g', 'FCR 36-42d corrected, g:g', 'FI 36-42d, g corrected', 'Mortality 36-42d, %', 'Culling 36-42d, %', 'Mort + Cull 36-42d, %', 'FI 22-42d, g', 'FI 22-42d, g corrected.', 'Group BWG 22-42d, g', 'BWG 22-42d, g', 'Group BWG 22-42d  corrected, g', 'BWG 22-42d  corrected, g', 'FCR 22-42d, g:g', 'FCR 22-42d corrected, g:g', 'Mortality 22-42d, %', 'Culling 22-42d, %', 'Mort + Cull 22-42d, %', 'ProjectID']

,House,Line,Pen,Blind Trts,Diet,Operator,# Ini birds 1d,"Group BWh, g","BW placement, g",Mortality 0-6d,...,"Group BWG 22-42d, g","BWG 22-42d, g","Group BWG 22-42d corrected, g","BWG 22-42d corrected, g","FCR 22-42d, g:g","FCR 22-42d corrected, g:g","Mortality 22-42d, %","Culling 22-42d, %","Mort + Cull 22-42d, %",ProjectID
0,1,A,1,9,Raza,NaN,28,1206,43.071429,0,...,44420,1850.833333,45398,1891.583333,1.621945,1.587004,0.0,4.0,4.0,E352
1,1,A,2,12,Mejia,NaN,28,1211,43.250000,0,...,44800,1866.666667,46670,1944.583333,1.683589,1.616130,0.0,4.0,4.0,E352
2,1,A,3,16,Raza,NaN,28,1211,43.250000,0,...,42800,1860.869565,45578,1981.652174,1.632080,1.532604,4.0,4.0,8.0,E352
3,1,A,4,2,Mejia,NaN,28,1217,43.464286,0,...,46230,1926.250000,47672,1986.333333,1.668466,1.617998,4.0,0.0,4.0,E352
4,1,A,5,15,Raza,NaN,28,1203,42.964286,0,...,45910,1836.400000,45910,1836.400000,1.595295,1.595295,0.0,0.0,0.0,E352

In [500]:
E352[[i for i in E352.columns if "Mortality" in i]].columns

Index(['Mortality 0-6d', 'Mortality weight 0-6d, g', 'Mortality 7d',
       'Mortality weight 7d, g', 'Mortality 0-7d, %', 'Mortality 8-13d',
       'Mortality weight 8-13d, g', 'Mortality 14d', 'Mortality weight 14d, g',
       'Mortality 8-14d, %', 'Mortality 8-20d', 'Mortality weight 8-20d, g',
       'Mortality 21d', 'Mortality weight 21d, g', 'Mortality 8-21d, %',
       'Mortality 22-26d', 'Mortality weight 22-26d, g', 'Mortality 27d',
       'Mortality weight 27d, g', 'Mortality 22-27d, %', 'Mortality 28-33d',
       'Mortality weight 28-33d, g', 'Mortality 34d',
       'Mortality weight 34d, g', 'Mortality 29-35d, %', 'Mortality 35-40d',
       'Mortality weight 35-40d, g', 'Mortality 41d',
       'Mortality weight 41d, g', 'Mortality 36-42d, %',
       'Mortality 22-42d, %'],
      dtype='object')

In [35]:
E352 = E352[['ProjectID', 'House', 'Pen', 'Blind Trts ', '# Ini birds 1d',
             
             'Group BWh, g', 'Group BW7, g', 'Group BW14, g', 'Group BW 21d, g', 'Group BW28d, g', 'Group BW 35d, g', 'Group BW 42d, g',
             
             
           '# Fnl birds 7d', 'Fnl birds 14d', '# Fnl birds 21d', '# Fnl birds 27d',
        '# Fnl birds 34d', '# Fnl birds 42d',

              
               
        'Mortality weight 0-6d, g', 'Mortality weight 7d, g',
       'Mortality weight 8-13d, g', 'Mortality weight 14d, g',
       'Mortality weight 8-20d, g', 'Mortality weight 21d, g',
       'Mortality weight 22-26d, g', 'Mortality weight 27d, g',
       'Mortality weight 28-33d, g', 'Mortality weight 34d, g',
       'Mortality weight 35-40d, g', 'Mortality weight 41d, g',
             
        
             
             'Culling 0-6d', 'Culling weight 0-6d, g', 'Culling 7d',
       'Culling weight 7d, g',  'Culling 8-13d',
       'Culling weight 8-13d, g', 'Culling 14d', 'Culling weight 14d, g',
        'Culling 8-20d', 'Culling weight 8-20d, g',
       'Culling 21d', 'Culling weight 21d, g', 
       'Culling 22-26d', 'Culling weight 22-26d, g', 'Culling 27d',
       'Culling weight 27d, g',  'Culling 28-33d',
       'Culling weight 28-33d, g', 'Culling 34d', 'Culling weight 34d',
        'Culling 35-40d', 'Culling weight 35-40d, g',
       'Culling 41d', 'Culling weight 41d, g',


               

        'Group FI 0-7d, g', 'Group FI 8-14d, g', 'Group FI 8-21d, g',
       'Group FI 22-27d, g', 'Group FI 28-34d, g', 'Group FI 36-42d, g'
               
               
               
             ]]
E352.head()

,ProjectID,House,Pen,Blind Trts,# Ini birds 1d,"Group BWh, g","Group BW7, g","Group BW14, g","Group BW 21d, g","Group BW28d, g",...,Culling 35-40d,"Culling weight 35-40d, g",Culling 41d,"Culling weight 41d, g","Group FI 0-7d, g","Group FI 8-14d, g","Group FI 8-21d, g","Group FI 22-27d, g","Group FI 28-34d, g","Group FI 36-42d, g"
0,E352,1,1,9,28,1206,5223,0,21710,0,...,1,978,0,0,3770,35560,23070,19050,25030,29730
1,E352,1,2,12,28,1211,5492,0,23390,0,...,1,1870,0,0,4240,35310,23630,20260,26870,30180
2,E352,1,3,16,28,1211,5389,0,20410,0,...,0,0,0,0,3960,35500,22310,19280,24830,28320
3,E352,1,4,2,28,1217,5632,0,23600,0,...,0,0,0,0,4350,34860,23790,20670,26310,30980
4,E352,1,5,15,28,1203,5280,0,20410,0,...,0,0,0,0,3910,35620,22050,18310,24300,30630

In [36]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Blind Trts ': 'Treatment',
    '# Ini birds 1d':'Init_Birds_D1', 


    'Group BWh, g':'GBW_initial',  
    'Group BW7, g':'GBW_7', 
    'Group BW14, g':'GBW_14', 
    'Group BW 21d, g':'GBW_21',
    'Group BW28d, g':'GBW_28',
    'Group BW 35d, g':'GBW_35', 
    'Group BW 42d, g':'GBW_42',
             
             
     '# Fnl birds 7d':'Fnl_Birds_D7', 
    'Fnl birds 14d':'Fnl_Birds_D14', 
    '# Fnl birds 21d':'Fnl_Birds_D21', 
    '# Fnl birds 27d':'Fnl_Birds_D27', 
    '# Fnl birds 34d':'Fnl_Birds_D35', 
    '# Fnl birds 42d':'Fnl_Birds_D42',


    'Mortality weight 0-6d, g':'Mort_Wt_D6',
    'Mortality weight 7d, g':'Mort_Wt_D7',
       'Mortality weight 8-13d, g' :'Mort_Wt_D13',
    'Mortality weight 14d, g':'Mort_Wt_D14',
       'Mortality weight 8-20d, g':'Mort_Wt_D20',
    'Mortality weight 21d, g':'Mort_Wt_D21',
       'Mortality weight 22-26d, g':'Mort_Wt_D26',
    'Mortality weight 27d, g':'Mort_Wt_D27',
       'Mortality weight 28-33d, g':'Mort_Wt_D33',
    'Mortality weight 34d, g':'Mort_Wt_D34',
       'Mortality weight 35-40d, g':'Mort_Wt_D40', 
    'Mortality weight 41d, g':'Mort_Wt_D41',



     'Culling 0-6d' :'Cull_D6',
    'Culling weight 0-6d, g' :'Cull_Wt_D6', 
    'Culling 7d':'Cull_D7',
       'Culling weight 7d, g':'Cull_Wt_D7',  
    'Culling 8-13d':'Cull_D13',
       'Culling weight 8-13d, g' :'Cull_Wt_D13', 
    'Culling 14d':'Cull_D14',
    'Culling weight 14d, g':'Cull_Wt_D14', 
        'Culling 8-20d':'Cull_D20',
    'Culling weight 8-20d, g':'Cull_Wt_D20', 
       'Culling 21d':'Cull_D21',
    'Culling weight 21d, g' :'Cull_Wt_D21', 
       'Culling 22-26d':'Cull_D26',
    'Culling weight 22-26d, g' :'Cull_Wt_D26', 
    'Culling 27d':'Cull_D27',
       'Culling weight 27d, g' :'Cull_Wt_D27',  
    'Culling 28-33d':'Cull_D33',
       'Culling weight 28-33d, g':'Cull_Wt_D33', 
    'Culling 34d':'Cull_D34',
    'Culling weight 34d':'Cull_Wt_D34', 
        'Culling 35-40d' :'Cull_D40',
    'Culling weight 35-40d, g':'Cull_Wt_D40', 
       'Culling 41d':'Cull_D41',
    'Culling weight 41d, g':'Cull_Wt_D41', 

    

    
     
    
    'Group FI 0-7d, g' :'GFI_D7', 
    'Group FI 8-14d, g' :'GFI_D14', 
    'Group FI 8-21d, g':'GFI_D21', 
       'Group FI 22-27d, g' :'GFI_D27', 
    'Group FI 28-34d, g' :'GFI_D34', 
    'Group FI 36-42d, g':'GFI_D42' 

    

    

    
}

E352.rename(columns=column_rename_map, inplace=True)
E352.head()

,ProjectID,House,Pen,Treatment,Init_Birds_D1,GBW_initial,GBW_7,GBW_14,GBW_21,GBW_28,...,Cull_D40,Cull_Wt_D40,Cull_D41,Cull_Wt_D41,GFI_D7,GFI_D14,GFI_D21,GFI_D27,GFI_D34,GFI_D42
0,E352,1,1,9,28,1206,5223,0,21710,0,...,1,978,0,0,3770,35560,23070,19050,25030,29730
1,E352,1,2,12,28,1211,5492,0,23390,0,...,1,1870,0,0,4240,35310,23630,20260,26870,30180
2,E352,1,3,16,28,1211,5389,0,20410,0,...,0,0,0,0,3960,35500,22310,19280,24830,28320
3,E352,1,4,2,28,1217,5632,0,23600,0,...,0,0,0,0,4350,34860,23790,20670,26310,30980
4,E352,1,5,15,28,1203,5280,0,20410,0,...,0,0,0,0,3910,35620,22050,18310,24300,30630

In [37]:
E352.columns

Index(['ProjectID', 'House', 'Pen', 'Treatment', 'Init_Birds_D1',
       'GBW_initial', 'GBW_7', 'GBW_14', 'GBW_21', 'GBW_28', 'GBW_35',
       'GBW_42', 'Fnl_Birds_D7', 'Fnl_Birds_D14', 'Fnl_Birds_D21',
       'Fnl_Birds_D27', 'Fnl_Birds_D35', 'Fnl_Birds_D42', 'Mort_Wt_D6',
       'Mort_Wt_D7', 'Mort_Wt_D13', 'Mort_Wt_D14', 'Mort_Wt_D20',
       'Mort_Wt_D21', 'Mort_Wt_D26', 'Mort_Wt_D27', 'Mort_Wt_D33',
       'Mort_Wt_D34', 'Mort_Wt_D40', 'Mort_Wt_D41', 'Cull_D6', 'Cull_Wt_D6',
       'Cull_D7', 'Cull_Wt_D7', 'Cull_D13', 'Cull_Wt_D13', 'Cull_D14',
       'Cull_Wt_D14', 'Cull_D20', 'Cull_Wt_D20', 'Cull_D21', 'Cull_Wt_D21',
       'Cull_D26', 'Cull_Wt_D26', 'Cull_D27', 'Cull_Wt_D27', 'Cull_D33',
       'Cull_Wt_D33', 'Cull_D34', 'Cull_Wt_D34', 'Cull_D40', 'Cull_Wt_D40',
       'Cull_D41', 'Cull_Wt_D41', 'GFI_D7', 'GFI_D14', 'GFI_D21', 'GFI_D27',
       'GFI_D34', 'GFI_D42'],
      dtype='object')

In [38]:
E352.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE352.csv', index=False)

In [ ]:
### ETL for correlation ---

In [16]:
E352 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Broiler Pigmentex 04-11-2022.xlsx", "Data to stat") 
E352["ProjectID"] = 'E352'
print(list(E352.columns))
E352.head()

['House', 'Line', 'Block 1', 'Pen', 'Operator', 'Trts', 'Diet_Pst_St', 'Diet_St', 'Block_2', 'Formulated EM Pst, Kcal/kg', 'Formulated EM St, kcal/kg', 'Formulated EM Gr, kcal/kg', 'Formulated EM Fn, kcal/kg', 'Formulated dLys Pst, %', 'Formulated dLys St, %', 'Formulated dLys Gr, %', 'Formulated dLys Fn, %', 'Yellow_Xantophyll_ppm', 'Yellow_Lucantin_ppm', 'Red_Lucantin_ppm', 'Zeaxanthin_St_ppm', 'Zeaxanthin_Fn_ppm', 'Fat Pst, %', 'Fat St, %', 'Fat Fn, %', 'Added Oil Pst, %', 'Added Oil St, %', 'Added Oil Fn, %', 'Pst diet cost, $/Kg', 'St diet cost, $/Kg', 'Gr diet cost, $/Kg', 'Fn diet cost, $/Kg', 'BW1, g', 'BW 7d, g', 'FI 0-7d, g', 'WC 0-7d, g', 'BWG 0-7d, g', 'BWG 0-7d, g correct', 'FCR 0-7d, g:g', 'FCR 0-7d corrected, g:g', 'FCR 0-7d Corrected BW1, g:g', 'Mortality 0-7d, %', 'Culling 0-7d, %', 'Mort + Cull 0-7d, %', 'kg/m2 0-7d', 'EM intake 0-7d, kcal', 'kcal intake/Kg 0-7d', 'g dLys intake 0-7d', 'g dLys intake/kg BWG 0-7d', 'Fat intake 0-7d, g', 'Added oil intake 0-7d, g', 'Zeaxanthin intake 0-7d, ppm', 'Total Pigment intake 0-7d, ppm', 'g Ca intake 0-7d', 'g Ca intake/ kg BWG 0-7d', 'g P intake 0-7d', 'g P intake/ kg BWG 0-7d', '$/kg BWG 0-7d', 'BW 14d, g', 'FI 8-14d, g', 'WC 8-14d, g', 'BWG 8-14d, g', 'BWG 8-14d correct, g', 'FCR 8-14d, g:g', 'FCR 8-14d corrected, g:g', 'Mortality 8-14d, %', 'Culling 8-14d, %', 'Mort + Cull 8-14d, %', 'kg/m2 8-14d', 'EM intake 8-14d, kcal', 'kcal intake/Kg 8-14d', 'g dLys intake 8-14d', 'g dLys intake/kg BWG 8-14d', 'g Ca intake 8-14d', 'g Ca intake/ kg BWG 8-14d', 'g P intake 8-14d', 'g P intake/ kg BWG 8-14d', '$/kg BWG 8-14d', 'BW 21d, g', 'BW 22d, g', 'FI 8-21d, g', 'WC 8-21d, g', 'BWG 8-21d, g', 'BWG 8-21d correct, g', 'FCR 8-21d, g:g', 'FCR 8-21d corrected, g:g', 'Mortality 8-21d, %', 'Culling 8-21d, %', 'Mort + Cull 8-21d, %', 'kg/m2 8-21d', 'EM intake 8-21dl kcal', 'kcal intake/Kg 8-21d', 'g dLys intake 8-21d', 'g dLys intake/kg BWG 8-21d', 'Fat intake 8-21d, g', 'Added oil intake 8-21d, g', 'Zeaxanthin intake 8-21d, ppm', 'Fat intake 0-21d, g', 'Added oil intake 0-21d, g', 'Zeaxanthin intake 0-21d, ppm', 'Total Pigment intake 0-21d, ppm', 'g Ca intake 8-21d', '$/kg BWG 8-21d', 'FI 0-21d, g', 'WC 0-21d, g', 'BWG 0-21d, g', 'BWG 0-21d correct, g', 'FCR 0-21d, g:g', 'FCR 0-21d corrected, g:g', 'Mortality 0 - 21d, %', 'Culling 0 - 21d, %', 'Mort + Cull 0 - 21d, %', 'EM intake 0-21d, kcal', 'kcal intake/Kg 0-21d', 'g dLys intake 0-21d', 'g dLys intake/kg BWG 0-21d', 'g Ca intake 0-21d', 'g Ca intake/ kg BWG 0-21d', 'g P intake 0-21d', 'g P intake/ kg BWG 0-21d', '$/kg BWG 0-21d', 'FI 0-21d, g.1', 'FI Zea 0-21d, g', 'BWG 0-21d, g.1', 'BWG 0-21d correct, g.1', 'FCR 0-21d, g:g.1', 'FCR 0-21d corrected, g:g.1', 'Mort + Cull 0-21d, %', 'BW 28d, g', 'FI 22-28d, g', 'FI 22-28d, g corrected', 'BWG 22-28d, g', 'BWG 22-28d correct, g', 'FCR 22-28d, g:g', 'FCR 22-28d corrected, g:g', 'Mortality 22 - 28d, %', 'Culling 22 - 28d, %', 'Mort + Cull 22 - 28d, %', 'kg/m2 22-28d', 'EM intake 22-28d, kcal', 'kcal intake/Kg 22-28d', 'g dLys intake 22-28d', 'g dLys intake/kg BWG 22-28d', 'Fat intake 22-28d, g', 'Added oil intake 22-28d, g', 'Zeax Intake 22-28d, ppm', 'Xant Intake 22-28d, ppm', 'Luc Amll Intake 22-28, ppm', 'Total yellow Intake 22-28d, ppm', 'Luc Rojo Intake 22-28, ppm', 'Total Pigment Intake 22-28, ppm', 'Fat intake 0-28d, g', 'Added oil intake 0-28d, g', 'Zeaxanthin intake 0-28d, ppm', 'Xant Intake 0-28d, ppm', 'Luc intake 0-28d, ppm', 'Total yellow Intake 0-28d, ppm', 'Canth intake 0-28d, ppm ', 'Total Pigment intake 0-28d, ppm', '$/kg BWG 22-28d', 'BW 35d, g', 'FI 29-35d, g', 'FI 29-35d, g corrected', 'BWG 29-35d, g', 'BWG 29-35d correct, g', 'FCR 29-35d, g:g', 'FCR 29-35d corrected, g:g', 'Mortality 29 - 35d, %', 'Culling 29 - 35d, %', 'Mort + Cull 29 - 35d, %', 'kg/m2 29-35d', 'EM intake 29-35d (kcal)', 'kcal intake/Kg 29-35d', 'g dLys intake 29-35d', 'g dLys intake/kg BWG 29-35d', 'Fat intake 29-35d, g', 'Added oil intake 29-35d, g', 'Zeax Intake 29-35d, ppm', 'Xant Intake 29-35d, ppm', 'Luc Amll Intake 29-35, ppm', 'Total yellow Intake 29-35d, ppm', 'Luc Rojo Intake 29-35, ppm', 'Total Pigment Intake 29-35, ppm', 'Fat intake 0-35d, g', 'Added oil intake 0-35d, g', 'Zeaxanthin intake 0-35d, ppm', 'Xant Intake 0-35d, ppm', 'Luc intake 0-35d, ppm', 'Total yellow Intake 0-35d, ppm', 'Canth intake 0-35d, ppm ', 'Total Pigment intake 0-35d, ppm', '$/kg BWG 29-35d', 'BW 42d, g', 'FI 36-42d, g', 'FI 36-42d, g corrected', 'BWG 36-42d, g', 'BWG 36-42d, g correct', 'FCR 36-42d, g:g', 'FCR 36-42d corrected, g:g', 'Mortality 36 - 42d, %', 'Culling 36 - 42d, %', 'Mort + Cull 36 - 42d, %', 'kg/m2 36-42d', 'EM intake 36-42d, kcal', 'kcal intake/Kg 36-42d', 'g dLys intake 36-42d', 'g dLys intake/kg BWG 36-42d', 'Fat intake 36-42d, g', 'Added oil intake 36-42d, g', 'Zeax Intake 36-42d, ppm', 'Xant Intake 36-42d, ppm', 'Luc Amll Intake 36-42, ppm', 'Total yellow Intake 36-42d, ppm', 'Luc Rojo Intake 36-42, ppm', 'Total Pigment Intake 36-42, ppm', 'Fat intake 0-42d, g', 'Added oil intake 0-42d, g', 'Zeaxanthin intake 0-42d, ppm', 'Xant Intake 0-42d, ppm', 'Luc intake 0-42d, ppm', 'Total yellow Intake 0-42d, ppm', 'Canth intake 0-42d, ppm ', 'Total Pigment intake 0-42d, ppm', '$/kg BWG 36-42d', 'FI 22-42, g', 'FI 22-42d, g corrected', 'BWG 22-42d, g', 'BWG 22-42d corrected, g', 'FCR 22-42d, g:g', 'FCR 22-42d corrected, g:g', 'Mortality 22 - 42d, %', 'Culling 22 - 42d, %', 'Mort + Cull 22 - 42d, %', 'EM intake 22-42d, kcal', 'kcal intake/Kg 22-42d', 'g dLys intake 22-42d', 'g dLys intake/kg BWG 22-42d', 'Zeax Intake 22-41d, ppm', 'Xant Intake 22-41d, ppm', 'Luc Amll Intake 22-41, ppm', 'Luc Rojo Intake 22-41, ppm', 'Total Pigment Intake 22-41, ppm', '$/kg BWG 22-42d', 'FI 0-42d, g', 'BWG 0-42d, g', 'BWG 0-42d correct, g', 'FCR 0-42d, g:g', 'FCR 0-42d corrected, g:g', 'Mortality 0 - 42d, %', 'Culling 0 - 42d, %', 'Mort + Cull 0 - 42d, %', 'ProjectID']

,House,Line,Block 1,Pen,Operator,Trts,Diet_Pst_St,Diet_St,Block_2,"Formulated EM Pst, Kcal/kg",...,$/kg BWG 22-42d,"FI 0-42d, g","BWG 0-42d, g","BWG 0-42d correct, g","FCR 0-42d, g:g","FCR 0-42d corrected, g:g","Mortality 0 - 42d, %","Culling 0 - 42d, %","Mort + Cull 0 - 42d, %",ProjectID
0,1,A,1A,1,D,9,Raza,1,1,NaN,...,0,3960.521429,2583.119048,2623.869048,1.533232,1.509420,0.0,4.000000,4.000000,E352
1,1,A,1A,2,D,12,Mejia,2,1,NaN,...,0,4138.057143,2658.773810,2736.690476,1.556378,1.512066,0.0,4.000000,4.000000,E352
2,1,A,1A,3,D,16,Raza,1,1,NaN,...,0,4036.593176,2587.814620,2728.674152,1.559846,1.479324,4.0,11.142857,15.142857,E352
3,1,A,1A,4,D,2,Mejia,2,1,NaN,...,0,4218.883333,2725.642857,2785.726190,1.547849,1.514464,4.0,0.000000,4.000000,E352
4,1,A,1A,5,D,15,Raza,1,1,NaN,...,0,3856.742857,2522.364286,2522.364286,1.529019,1.529019,0.0,0.000000,0.000000,E352

In [17]:
E352[[i for i in E352.columns if "BW " in i]].columns

Index(['BW 7d, g', 'BW 14d, g', 'BW 21d, g', 'BW 22d, g', 'BW 28d, g',
       'BW 35d, g', 'BW 42d, g'],
      dtype='object')

In [18]:
E352 = E352[['ProjectID', 'House', 'Pen', 'Trts', 
             
             'FCR 0-42d corrected, g:g', 'FCR 36-42d corrected, g:g',


             'BWG 0-42d correct, g', 'BWG 36-42d, g correct',


             'BW 42d, g'

             
             
               
             ]]
E352.head()

,ProjectID,House,Pen,Trts,"FCR 0-42d corrected, g:g","FCR 36-42d corrected, g:g","BWG 0-42d correct, g","BWG 36-42d, g correct","BW 42d, g"
0,E352,1,1,9,1.509420,0.443017,2623.869048,2796.166667,2755.416667
1,E352,1,2,12,1.512066,0.430774,2736.690476,2919.166667,2841.250000
2,E352,1,3,16,1.479324,0.438940,2728.674152,2805.173913,2748.260870
3,E352,1,4,2,1.514464,0.443649,2785.726190,2909.583333,2909.583333
4,E352,1,5,15,1.529019,0.461852,2522.364286,2652.800000,2652.800000

In [19]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Trts': 'Treatment',


    'FCR 0-42d corrected, g:g':'FCR',
    'FCR 36-42d corrected, g:g':'FCRbefore', 
    'BWG 0-42d correct, g':'BWG',
    'BWG 36-42d, g correct':'BWGbefore', 
    'BW 42d, g':'BW'




    
}

E352.rename(columns=column_rename_map, inplace=True)

In [21]:
E352["Age"] = '42'
E352.head()

,ProjectID,House,Pen,Treatment,FCR,FCRbefore,BWG,BWGbefore,BW,Age
0,E352,1,1,9,1.509420,0.443017,2623.869048,2796.166667,2755.416667,42
1,E352,1,2,12,1.512066,0.430774,2736.690476,2919.166667,2841.250000,42
2,E352,1,3,16,1.479324,0.438940,2728.674152,2805.173913,2748.260870,42
3,E352,1,4,2,1.514464,0.443649,2785.726190,2909.583333,2909.583333,42
4,E352,1,5,15,1.529019,0.461852,2522.364286,2652.800000,2652.800000,42

In [22]:
E352.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE352.csv', index=False)

# E355

In [3]:
E355 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/E-355 Energia + Enzimas 16-11-2022.xlsx", "Performance Data") 
E355["ProjectID"] = 'E355'
print(list(E355.columns))
E355.head()

['House', 'Line', 'Pen', 'Blind Trts ', 'Operator', '# Ini birds 1d', 'Group BWh, g', 'BW placement, g', 'Mortality 0-6d', 'Mortality weight 0-6d, g', 'Culling 0-6d', 'Culling weight 0-6d, g', 'Total Mort. + cull 0-6d, g', 'Mortality 7d', 'Mortality weight 7d, g', 'Culling 7d', 'Culling weight 7d, g', 'Total Weight Mort. + cull 7d, g', 'Sampling 7d', 'Sampling weight 7d, g', 'Offered feed 1d, g', 'Offered water 1d, g', 'Leftover feed 7d, g', 'Leftover water 7d, g', 'Container weight, g', 'Container + birds weight, g', '# Fnl birds 7d', 'Group BW7, g', 'BW7, g', 'Group FI 0-7d, g', 'FI 0-7d, g', 'Group WC 0-7d, g', 'WC 0-7d, g', 'Group BWG 0-7d, g', 'BWG 0-7d, g', 'Group BWG 0-7d corrected, g', 'BWG 0-7d corrected, g', 'FCR 0-7d, g:g', 'FCR 0-7d corrected, g:g', 'Mortality 0-7d, %', 'Culling 0-7d, %', 'Mort + Cull 0-7d, %', 'Wk2   (8-14d)', '# Ini birds 8d', 'Ini GBW8, g', 'Offered feed 8d, g', 'Leftover feed 14d, g', 'Offered Water 8d, g', 'Leftover water 14d, g', 'Mortality 8-13d', 'Mortality weight 8-13d, g', 'Culling 8-13d', 'Culling weight 8-13d, g', 'Total Mort. + cull 8-13d, g', 'Mortality 14d', 'Mortality weight 14d, g', 'Culling 14d', 'Culling weight 14d, g', 'Mort + Cull 14d (g)', 'Sampling 14d', 'Sampling weight 14d, g', 'Container weight, g.1', 'Container + birds weight, g.1', 'Fnl birds 14d', 'Group BW14, g', 'BW14, g', 'Group FI 8-14d, g', 'FI 8-14d, g', 'Group WC 8-14d, g', 'WC 8-14d, g', 'Group BWG 8-14d, g', 'BWG 8-14d, g', 'Group BWG 8-14d corrected, g', 'BWG 8-14d  corrected, g', 'FCR 8-14d, g:g', 'FCR 8-14d corrected, g:g', 'Mortality 8-14d, %', 'Culling 8-14d, %', 'Mort + Cull 8-14d, %', 'Wk3  (15-21d)', '# Ini birds 15d', 'Ini GBW 15d, g', 'Offered feed 15-21, g', 'Feed adition 15-21, g', 'Offered water 15-21, g', 'Leftover feed 15-21d, g', 'Leftover water 15-21, g', 'Mortality 15-20d', 'Mortality weight 15-20d, g', 'Culling 15-20d', 'Culling weight 15-20d, g', 'Total Mort. + cull 15-20d, g', 'Mortality 21d', 'Mortality weight 21d, g', 'Culling 21d', 'Culling weight 21d, g', 'Total Mort + Cull 21d, g', 'Sampling 21d', 'Sampling weight 21d, g', 'Container weight, g.2', 'Container + birds weight, g.2', '# Fnl birds 21d', 'Group BW 21d, g', 'BW 21d, g', 'Group FI 15-21d, g', 'FI 15-21d, g', 'Group WC 15-21d, g', 'WC 15-21d, g', 'Group BWG 15-21d, g', 'BWG 15-21d, g', 'Group BWG 15-21d  corrected, g', 'BWG 15-21d  corrected, g', 'FCR 15-21d, g:g', 'FCR 15-21d corrected, g:g', 'Mortality 15-21d, %', 'Culling 15-21d, %', 'Mort + Cull 15-21d, %', 'Wk4  (22-28d)', '#Ini birds 22d', 'Ini GBW 22d, g', 'Offered feed 22-28d, g', 'Feed adition 22-28d, g', 'Leftover feed 22-28d, g', 'Offered water 22 -28d, g', 'Leftover water 22-28d, g', 'Mortality 22-27d', 'Mortality weight 22-27d, g', 'Culling 22-27d', 'Culling weight 22-27d, g', 'Total Mort. + Cull 22-27d, g', 'Mortality 28d', 'Mortality weight 28d, g', 'Culling 28d', 'Culling weight 28d, g', 'Total Mort + Cull 28d, g', 'Sampling 28d', 'Sampling weight 28d, g', 'Container weight, g.3', 'Container + birds weight, g.3', '# Fnl birds 28d', 'Group BW28d, g', 'BW28d, g', 'Group FI 22-28d, g', 'FI 22-28d, g', 'Group WC 22-28d, g', 'WC 22-28d, g', 'Group BWG 22-28d, g', 'BWG 22-28d, g', 'Group BWG 22-28d corrected, g', 'BWG 22-28d corrected, g', 'FCR 22-28d, g:g', 'FCR22-28 corrected, g:g', 'Mortality 22-28d, %', 'Culling 22-28d, %', 'Mort + Cull 22-28d, %', 'Wk5   (29-35d)', '#Ini birds 29d', 'Ini GBW 29d, g', 'Offered feed 29-35d, g', 'Adition feed 29-35d, g', 'Leftover feed 29-35d, g', 'Offered water 29-35d, g', 'Leftover water 29-35d, g', 'Mortality 29-34d', 'Mortality weight 29-34d, g', 'Culling 29-34d', 'Culling weight 29-34d, g', 'Total Mort. + cull 29-34d, g', 'Mortality 35d', 'Mortality weight 35d, g', 'Culling 35d', 'Culling weight 35d', 'Total Mort + Cull 35d, g', 'Sampling 35d', 'Sampling weight 35d, g', 'Container weight (g)', 'Container + birds weight (g)', '# Fnl birds 35d', 'Group BW 35d, g', 'BW35d, g', 'Group FI 29-35d, g', 'FI 29-35d, g', 'Group WC 29-35d, g', 'WC 29 - 35d, g', 'Group BWG 29-35d, g', 'BWG 29-35d, g', 'Group BWG 29-35d corrected, g', 'BWG 29-35d corrected, g', 'FCR 29-35d, g:g', 'FCR 29-35d corrected, g:g', 'Mortality 29-35d, %', 'Culling 29-35d, %', 'Mort + Cull 29-35d, %', 'Wk5   (36-42d)', '# Ini Birds 36d', 'Ini GBW 36d, g', 'Offered feed 36-42d, g', 'Adition feed 36-42d, g', 'Leftover feed 36-42d, g', 'Offered water 26-42d, g', 'Leftover water 36 - 42d, g', 'Mortality 36-41d', 'Mortality weight 36-41d, g', 'Culling 36-41d', 'Culling weight 36-41d, g', 'Total Mort. + cull 36-41d, g', 'Mortality 42d', 'Mortality weight 42d, g', 'Culling 42d', 'Culling weight 42d, g', 'Total Mort + Cull 42d, g', 'Sampling 42d', 'Sampling weight 42d, g', 'Container weight, g.4', 'Container + birds weight, g.4', '# Fnl birds 42d', 'Group BW 42d, g', 'BW 42d, g', 'Group FI 36-42d, g', 'FI 36-42d, g', 'Group WC 36-42d, g', 'WC 36 - 42d, g', 'Group BWG 36-42d, g', 'BWG 36-42d, g', 'Group BWG 36-42d corrected, g', 'BWG 36-42d corrected, g', 'FCR 36-42d, g:g', 'FCR 36-42d corrected, g:g', 'Mortality 36-42d, %', 'Culling 36-42d, %', 'Mort + Cull 36-42d, %', 'ProjectID']

,House,Line,Pen,Blind Trts,Operator,# Ini birds 1d,"Group BWh, g","BW placement, g",Mortality 0-6d,"Mortality weight 0-6d, g",...,"Group BWG 36-42d, g","BWG 36-42d, g","Group BWG 36-42d corrected, g","BWG 36-42d corrected, g","FCR 36-42d, g:g","FCR 36-42d corrected, g:g","Mortality 36-42d, %","Culling 36-42d, %","Mort + Cull 36-42d, %",ProjectID
0,1,A,1,2,NaN,25,1002.3,40.092000,0,0,...,16460,783.809524,16460,783.809524,1.772783,1.772783,0.0,0.0,0.0,E355
1,1,A,2,7,NaN,25,1043.5,41.740000,0,0,...,18410,767.083333,18410,767.083333,1.872352,1.872352,0.0,0.0,0.0,E355
2,1,A,3,3,NaN,25,1038.5,41.540000,0,0,...,18990,759.600000,18990,759.600000,1.831490,1.831490,0.0,0.0,0.0,E355
3,1,A,4,1,NaN,25,1049.5,41.980000,0,0,...,17540,797.272727,17540,797.272727,1.828962,1.828962,0.0,0.0,0.0,E355
4,1,A,5,11,NaN,26,1001.5,38.519231,0,0,...,19580,783.200000,19580,783.200000,1.802349,1.802349,0.0,0.0,0.0,E355

In [519]:
E355[[i for i in E355.columns if "Group FI" in i]].columns

Index(['Group FI 0-7d, g', 'Group FI 8-14d, g', 'Group FI 15-21d, g',
       'Group FI 22-28d, g', 'Group FI 29-35d, g', 'Group FI 36-42d, g'],
      dtype='object')

In [520]:
E355 = E355[['ProjectID', 'House', 'Pen', 'Blind Trts ', '# Ini birds 1d',
             
             'Group BWh, g', 'Group BW7, g', 'Group BW14, g', 'Group BW 21d, g', 'Group BW28d, g', 'Group BW 35d, g', 'Group BW 42d, g',
             
             
             '# Fnl birds 7d', 'Fnl birds 14d', '# Fnl birds 21d', '# Fnl birds 28d', '# Fnl birds 35d', '# Fnl birds 42d',

              
               
             'Mortality weight 0-6d, g', 'Mortality weight 7d, g',
       'Mortality weight 8-13d, g', 'Mortality weight 14d, g',
       'Mortality weight 15-20d, g', 'Mortality weight 21d, g',
       'Mortality weight 22-27d, g', 'Mortality weight 28d, g',
       'Mortality weight 29-34d, g', 'Mortality weight 35d, g',
       'Mortality weight 36-41d, g', 'Mortality weight 42d, g',
             
            'Culling 0-6d', 'Culling weight 0-6d, g', 'Culling 7d',
       'Culling weight 7d, g', 'Culling 8-13d',
       'Culling weight 8-13d, g', 'Culling 14d', 'Culling weight 14d, g',
        'Culling 15-20d', 'Culling weight 15-20d, g',
       'Culling 21d', 'Culling weight 21d, g', 
       'Culling 22-27d', 'Culling weight 22-27d, g', 'Culling 28d',
       'Culling weight 28d, g', 'Culling 29-34d',
       'Culling weight 29-34d, g', 'Culling 35d', 'Culling weight 35d',
       'Culling 36-41d', 'Culling weight 36-41d, g',
       'Culling 42d', 'Culling weight 42d, g',

               

             'Group FI 0-7d, g', 'Group FI 8-14d, g', 'Group FI 15-21d, g',
       'Group FI 22-28d, g', 'Group FI 29-35d, g', 'Group FI 36-42d, g'
               
               
               
             ]]
E355.head()

,ProjectID,House,Pen,Blind Trts,# Ini birds 1d,"Group BWh, g","Group BW7, g","Group BW14, g","Group BW 21d, g","Group BW28d, g",...,Culling 36-41d,"Culling weight 36-41d, g",Culling 42d,"Culling weight 42d, g","Group FI 0-7d, g","Group FI 8-14d, g","Group FI 15-21d, g","Group FI 22-28d, g","Group FI 29-35d, g","Group FI 36-42d, g"
0,E355,1,1,2,25,1002.3,4032,9560,19730,32450,...,0,0,0,0,3520,7450,13620,19670,25370,29180
1,E355,1,2,7,25,1043.5,4301,10930,22670,37290,...,0,0,0,0,3840,8390,15640,22670,29670,34470
2,E355,1,3,3,25,1038.5,4152,10910,23090,39500,...,0,0,0,0,3460,8180,15470,23250,30050,34780
3,E355,1,4,1,25,1049.5,4331,10670,21560,34880,...,0,0,0,0,3680,8450,15650,22640,27780,32080
4,E355,1,5,11,26,1001.5,4462,11120,22900,37080,...,0,0,0,0,3820,8410,18440,23000,30060,35290

In [523]:

column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Blind Trts ': 'Treatment',
    '# Ini birds 1d':'Init_Birds_D1', 



     'Group BWh, g':'GBW_initial',  
    'Group BW7, g':'GBW_7', 
    'Group BW14, g':'GBW_14', 
    'Group BW 21d, g':'GBW_21',
    'Group BW28d, g':'GBW_28',
    'Group BW 35d, g':'GBW_35', 
    'Group BW 42d, g':'GBW_42',
             
             
     '# Fnl birds 7d':'Fnl_Birds_D7', 
    'Fnl birds 14d':'Fnl_Birds_D14', 
    '# Fnl birds 21d':'Fnl_Birds_D21', 
    '# Fnl birds 28d':'Fnl_Birds_D27', 
    '# Fnl birds 35d':'Fnl_Birds_D35', 
    '# Fnl birds 42d':'Fnl_Birds_D42',


    'Mortality weight 0-6d, g':'Mort_Wt_D6',
    'Mortality weight 7d, g':'Mort_Wt_D7',
       'Mortality weight 8-13d, g' :'Mort_Wt_D13',
    'Mortality weight 14d, g':'Mort_Wt_D14',
       'Mortality weight 15-20d, g' :'Mort_Wt_D20',
    'Mortality weight 21d, g':'Mort_Wt_D21',
       'Mortality weight 22-27d, g':'Mort_Wt_D27',
    'Mortality weight 28d, g':'Mort_Wt_D28',
       'Mortality weight 29-34d, g':'Mort_Wt_D34',
    'Mortality weight 35d, g':'Mort_Wt_D35',
       'Mortality weight 36-41d, g':'Mort_Wt_D41',
    'Mortality weight 42d, g':'Mort_Wt_D42',
              
     
     'Culling 0-6d':'Cull_D6',
    'Culling weight 0-6d, g' :'Cull_Wt_D6', 
    'Culling 7d':'Cull_D7',
       'Culling weight 7d, g':'Cull_Wt_D7', 
    'Culling 8-13d':'Cull_D13',
       'Culling weight 8-13d, g':'Cull_Wt_D13', 
    'Culling 14d' :'Cull_D14',
    'Culling weight 14d, g':'Cull_Wt_D14', 
        'Culling 15-20d' :'Cull_D20',
    'Culling weight 15-20d, g':'Cull_Wt_D20', 
       'Culling 21d' :'Cull_D21',
    'Culling weight 21d, g':'Cull_Wt_D21', 
        'Culling 22-27d' :'Cull_D27',
    'Culling weight 22-27d, g':'Cull_Wt_D27', 
       'Culling 28d':'Cull_D28',
    'Culling weight 28d, g':'Cull_Wt_D28', 
       'Culling 29-34d':'Cull_D34', 
    'Culling weight 29-34d, g':'Cull_Wt_D34', 
    'Culling 35d':'Cull_D35',
       'Culling weight 35d':'Cull_Wt_D35', 
    'Culling 36-41d':'Cull_D41',
       'Culling weight 36-41d, g':'Cull_Wt_D41', 
    'Culling 42d':'Cull_D42',
    'Culling weight 42d, g':'Cull_Wt_D42', 

    'Group FI 0-7d, g' :'GFI_D7', 
    'Group FI 8-14d, g' :'GFI_D14', 
    'Group FI 8-21d, g':'GFI_D21', 
       'Group FI 22-27d, g' :'GFI_D27', 
    'Group FI 28-34d, g' :'GFI_D34', 
    'Group FI 36-42d, g':'GFI_D42' 



    
}

E355.rename(columns=column_rename_map, inplace=True)

In [524]:
E355.columns

Index(['ProjectID', 'House', 'Pen', 'Treatment', 'Init_Birds_D1',
       'GBW_initial', 'GBW_7', 'GBW_14', 'GBW_21', 'GBW_28', 'GBW_35',
       'GBW_42', 'Fnl_Birds_D7', 'Fnl_Birds_D14', 'Fnl_Birds_D21',
       'Fnl_Birds_D27', 'Fnl_Birds_D35', 'Fnl_Birds_D42', 'Mort_Wt_D6',
       'Mort_Wt_D7', 'Mort_Wt_D13', 'Mort_Wt_D14', 'Mort_Wt_D20',
       'Mort_Wt_D21', 'Mort_Wt_D27', 'Mort_Wt_D28', 'Mort_Wt_D34',
       'Mort_Wt_D35', 'Mort_Wt_D41', 'Mort_Wt_D42', 'Cull_D6', 'Cull_Wt_D6',
       'Cull_D7', 'Cull_Wt_D7', 'Cull_D13', 'Cull_Wt_D13', 'Cull_D14',
       'Cull_Wt_D14', 'Cull_D20', 'Cull_Wt_D20', 'Cull_D21', 'Cull_Wt_D21',
       'Cull_D26', 'Cull_Wt_D27', 'Cull_D27', 'Cull_Wt_D28', 'Cull_D34',
       'Cull_Wt_D34', 'Cull_D35', 'Cull_Wt_D35', 'Cull_D41', 'Cull_Wt_D41',
       'Cull_D42', 'Cull_Wt_D42', 'GFI_D7', 'GFI_D14', 'Group FI 15-21d, g',
       'Group FI 22-28d, g', 'Group FI 29-35d, g', 'GFI_D42'],
      dtype='object')

In [525]:
E355.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE355.csv', index=False)

### ETL for correlation ---

In [5]:
E355 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/E-355 Energia + Enzimas 16-11-2022.xlsx", "Data to stat") 
E355["ProjectID"] = 'E355'
print(list(E355.columns))
E355.head()

['House', 'Line', 'Block 1', 'Pen', 'Operator', 'Trts', 'Trts.', 'Block 2', 'Formulated EM Pst, Kcal/kg', 'Formulated EM St, kcal/kg', 'Formulated EM Gr, kcal/kg', 'Formulated EM Fn, kcal/kg', 'Formulated dLys Pst, %', 'Formulated dLys St, %', 'Formulated dLys Gr, %', 'Formulated dLys Fn, %', 'Analyzed Ca Pst, %', 'Analyzed Ca St, %', 'Analyzed Ca Gr, %', 'Analyzed Ca Fn, %', 'analyzed P Pst, %', 'analyzed P St, %', 'analyzed P Gr, %', 'analyzed P Fn, %', 'Pst diet cost, $/Kg', 'Formulated dMet St, %', 'Formulated dMet Gr, %', 'Formulated dMet + Cis St, %', 'Formulated dMet + Cis Gr, %', 'Formulated dTre St, %', 'Formulated dTre Gr, %', 'EM/dLys St', 'EM/dLys Fn', 'Xantophyll Fn, ppm', 'Canthaxanthin Fn, ppm', 'St diet cost, $/Kg', 'Gr diet cost, $/Kg', 'Fn diet cost, $/Kg', 'BW1, g', 'BW 7d, g', 'FI 0-7d, g', 'WC 0-7d, g', 'BWG 0-7d, g', 'BWG 0-7d, g correct', 'FCR 0-7d, g:g', 'FCR 0-7d corrected, g:g', 'Mortality 0-7d, %', 'Culling 0-7d, %', 'Mort + Cull 0-7d, %', 'kg/m2 0-7d', 'EM intake 0-7d, kcal', 'kcal intake/Kg 0-7d', 'g dLys intake 0-7d', 'g dLys intake/kg BWG 0-7d', 'g Ca intake 0-7d', 'g Ca intake/ kg BWG 0-7d', 'g P intake 0-7d', 'g P intake/ kg BWG 0-7d', '$/kg BWG 0-7d', 'BW 14d, g', 'FI 8-14d, g', 'WC 8-14d, g', 'BWG 8-14d, g', 'BWG 8-14d correct, g', 'FCR 8-14d, g:g', 'FCR 8-14d corrected, g:g', 'Mortality 8-14d, %', 'Culling 8-14d, %', 'Mort + Cull 8-14d, %', 'kg/m2 8-14d', 'EM intake 8-14d, kcal', 'kcal intake/Kg 8-14d', 'g dLys intake 8-14d', 'g dLys intake/kg BWG 8-14d', 'g Ca intake 8-14d', 'g Ca intake/ kg BWG 8-14d', 'g P intake 8-14d', 'g P intake/ kg BWG 8-14d', '$/kg BWG 8-14d', 'BW 21d, g', 'FI 15-21d, g', 'WC 15-21d, g', 'BWG 15-21d, g', 'BWG 15-21d correct, g', 'FCR 15-21d, g:g', 'FCR 15-21d corrected, g:g', 'Mortality 15-21d, %', 'Culling 15-21d, %', 'Mort + Cull 15-21d, %', 'kg/m2 15-21d', 'EM intake 15-21dl kcal', 'kcal intake/Kg 15-21d', 'g dLys intake 15-21d', 'g dLys intake/kg BWG 15-21d', 'g Ca intake 15-21d', 'g Ca intake/ kg BWG 15-21d', 'g P intake 15-21d', 'g P intake/ kg BWG 15-21d', '$/kg BWG 15-21d', 'FI 0-21d, g', 'WC 0-21d, g', 'BWG 0-21d, g', 'BWG 0-21d correct, g', 'FCR 0-21d, g:g', 'FCR 0-21d corrected, g:g', 'Mortality 0 - 21d, %', 'Culling 0 - 21d, %', 'Mort + Cull 0 - 21d, %', 'EM intake 0-21d, kcal', 'kcal intake/Kg 0-21d', 'g dLys intake 0-21d', 'g dLys intake/kg BWG 0-21d', 'g Ca intake 0-21d', 'g Ca intake/ kg BWG 0-21d', 'g P intake 0-21d', 'g P intake/ kg BWG 0-21d', '$/kg BWG 0-21d', 'BW 28d, g', 'FI 22-28d, g', 'WC 22-28d, g', 'BWG 22-28d, g', 'BWG 22-28d correct, g', 'FCR 22-28d, g:g', 'FCR 22-28d corrected, g:g', 'Mortality 22 - 28d, %', 'Culling 22 - 28d, %', 'Mort + Cull 22 - 28d, %', 'kg/m2 22-28d', 'EM intake 22-28d, kcal', 'kcal intake/Kg 22-28d', 'g dLys intake 22-28d', 'g dLys intake/kg BWG 22-28d', 'g Ca intake 22-28d', 'g Ca intake/ kg BWG 22-28d', 'g P intake 22-28d', 'g P intake/ kg BWG 22-28d', '$/kg BWG 22-28d', 'BW 35d, g', 'FI 29-35d, g', 'WC 29-35d, g', 'BWG 29-35d, g', 'BWG 29-35d correct, g', 'FCR 29-35d, g:g', 'FCR 29-35d corrected, g:g', 'Mortality 29 - 35d, %', 'Culling 29 - 35d, %', 'Mort + Cull 29 - 35d, %', 'kg/m2 29-35d', 'EM intake 29-35d (kcal)', 'kcal intake/Kg 29-35d', 'g dLys intake 29-35d', 'g dLys intake/kg BWG 29-35d', 'g Ca intake 29-35d', 'g Ca intake/ kg BWG 29-35d', 'g P intake 29-35d', 'g P intake/ kg BWG 29-35d', '$/kg BWG 29-35d', 'BW 42d, g', 'FI 36-42d, g', 'WC 36-42d, g', 'BWG 36-42d, g', 'BWG 36-42d, g correct', 'FCR 36-42d, g:g', 'FCR 36-42d corrected, g:g', 'Mortality 36 - 42d, %', 'Culling 36 - 42d, %', 'Mort + Cull 36 - 42d, %', 'kg/m2 36-42d', 'EM intake 36-42d, kcal', 'kcal intake/Kg 36-42d', 'g dLys intake 36-42d', 'g dLys intake/kg BWG 36-42d', 'g Ca intake 36-42d', 'g Ca intake/ kg BWG 36-42d', 'g P intake 36-42d', 'g P intake/ kg BWG 36-42d', '$/kg BWG 36-42d', 'FI 22-42, g', 'WC 22-42, g', 'BWG 22-42d, g', 'BWG 22-42d corrected, g', 'FCR 22-42d, g:g', 'FCR 22-42d corrected, g:g', 'Mortality 22 - 42d, %', 'Culling 22 - 42d, %', 'Mort + Cull 22 - 42d, %', 'EM intake 22-42d, kcal', 'kcal intake/Kg 22-42d', 'g dLys intake 22-42d', 'g dLys intake/kg BWG 22-42d', 'g Ca intake 22-42d', 'g Ca intake/ kg BWG 22-42d', 'g P intake 22-42d', 'g P intake/ kg BWG 22-42d', '$/kg BWG 22-42d', 'FI 0-42d, g', 'WC 0-42d, g', 'BWG 0-42d, g', 'BWG 0-42d correct, g', 'FCR 0-42d, g:g', 'FCR 0-42d corrected, g:g', 'Mortality 0 - 42d, %', 'Culling 0 - 42d, %', 'Mort + Cull 0 - 42d, %', 'EM intake 0-42d, kcal', 'kcal intake/Kg 0-42d', 'g dLys intake 0-42d', 'g dLys intake/kg BWG 0-42d', 'Xanthophyll Intake, ppm 22-42d', 'Canthaxanthin Intake, ppm 22-42d', 'Total Pigment Intake, ppm 22-42d', '$/kg BWG 22-42d.1', 'ProjectID']

,House,Line,Block 1,Pen,Operator,Trts,Trts.,Block 2,"Formulated EM Pst, Kcal/kg","Formulated EM St, kcal/kg",...,"Mort + Cull 0 - 42d, %","EM intake 0-42d, kcal",kcal intake/Kg 0-42d,g dLys intake 0-42d,g dLys intake/kg BWG 0-42d,"Xanthophyll Intake, ppm 22-42d","Canthaxanthin Intake, ppm 22-42d","Total Pigment Intake, ppm 22-42d",$/kg BWG 22-42d.1,ProjectID
0,1,A,1A,1,D,2,MB,1,NaN,3020,...,21.407773,14370.745080,4762.628211,52.806408,17.500644,353.428571,21.205714,374.634286,NaN,E355
1,1,A,1A,2,D,7,B2N,1,NaN,2940,...,4.000000,14345.787000,4730.066449,54.111893,17.841674,361.708333,21.702500,383.410833,NaN,E355
2,1,A,1A,3,D,3,MA,1,NaN,3100,...,0.000000,14706.344000,4871.489238,52.689520,17.453449,352.320000,21.139200,373.459200,NaN,E355
3,1,A,1A,4,D,1,B,1,NaN,2940,...,12.333333,14311.512190,4970.418167,53.981262,18.747805,360.934124,21.656047,382.590171,NaN,E355
4,1,A,1A,5,D,11,B1NNTG,1,NaN,2940,...,3.846154,14282.109231,4852.825888,53.972108,18.338835,353.400000,21.204000,374.604000,NaN,E355

In [8]:
E355[[i for i in E355.columns if "BW " in i]].columns

Index(['BW 7d, g', 'BW 14d, g', 'BW 21d, g', 'BW 28d, g', 'BW 35d, g',
       'BW 42d, g'],
      dtype='object')

In [10]:
E355 = E355[['ProjectID', 'House', 'Pen', 'Trts', 
             
             'FCR 0-42d corrected, g:g', 'FCR 36-42d corrected, g:g',


             'BWG 0-42d correct, g', 'BWG 36-42d, g correct',


             'BW 42d, g'

             
             
               
             ]]
E355.head()

,ProjectID,House,Pen,Trts,"FCR 0-42d corrected, g:g","FCR 36-42d corrected, g:g","BWG 0-42d correct, g","BWG 36-42d, g correct","BW 42d, g"
0,E355,1,1,2,1.530487,1.772783,3017.398051,783.809524,3069.523810
1,E355,1,2,7,1.560188,1.872352,3032.893333,767.083333,3087.500000
2,E355,1,3,3,1.526272,1.831490,3018.860000,759.600000,3060.400000
3,E355,1,4,1,1.639454,1.828962,2879.337655,797.272727,2988.636364
4,E355,1,5,11,1.601609,1.802349,2943.050000,783.200000,2974.800000

In [11]:
E355.columns

Index(['ProjectID', 'House', 'Pen', 'Trts', 'FCR 0-42d corrected, g:g',
       'FCR 36-42d corrected, g:g', 'BWG 0-42d correct, g',
       'BWG 36-42d, g correct', 'BW 42d, g'],
      dtype='object')

In [12]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Trts': 'Treatment',


    'FCR 0-42d corrected, g:g':'FCR',
    'FCR 36-42d corrected, g:g':'FCRbefore', 
    'BWG 0-42d correct, g':'BWG',
    'BWG 36-42d, g correct':'BWGbefore', 
    'BW 42d, g':'BW'




    
}

E355.rename(columns=column_rename_map, inplace=True)

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_3447/695082082.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  E355.rename(columns=column_rename_map, inplace=True)

In [14]:
E355["Age"] = '42'
E355.head()

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_3447/353262216.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  E355["Age"] = '42'

,ProjectID,House,Pen,Treatment,FCR,FCRbefore,BWG,BWGbefore,BW,Age
0,E355,1,1,2,1.530487,1.772783,3017.398051,783.809524,3069.523810,42
1,E355,1,2,7,1.560188,1.872352,3032.893333,767.083333,3087.500000,42
2,E355,1,3,3,1.526272,1.831490,3018.860000,759.600000,3060.400000,42
3,E355,1,4,1,1.639454,1.828962,2879.337655,797.272727,2988.636364,42
4,E355,1,5,11,1.601609,1.802349,2943.050000,783.200000,2974.800000,42

In [15]:
E355.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/DE1/LongFormat_Performance/LongFormatE355.csv', index=False)

# FractalPronaca1

In [4]:
pronaca1 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Performance_ExpFarm/FractalPronaca1 Datos desempeño 35d Alura.xlsx") 
pronaca1["ProjectID"] = 'FractalPronaca1'
print(list(pronaca1.columns))
pronaca1.head()

['Jaula', 'Trat.', 'Bloque', 'Peso Inicial (g/ave)', 'Peso 7d (g/ave)', 'GDP 7d (g/ave/día)', 'Cons. 7d (g/ave)', 'C.A 7d', 'Mort 7d %', 'Peso 14d (g/ave)', 'GDP Total 14d (g/ave/día)', 'Cons. Tot 14d (g/ave)', 'C.A acum 14d', 'Mort 14d %', 'Peso 21d (g/ave)', 'GDP Total 21d (g/ave/día)', 'Cons. Tot 21d (g/ave)', 'C.A acum 21d', 'Mort 21d %', 'Peso 28d (g/ave)', 'GDP Total 28d (g/ave/día)', 'Cons. Tot 28d (g/ave)', 'C.A acum 28d', 'Mort 28d %', 'Peso 35d (g/ave)', 'GDP Total 35d (g/ave/día)', 'Cons. Tot 35d (g/ave)', 'C.A acum 35d', 'Mort 35d %', 'FEE', 'ProjectID']

,Jaula,Trat.,Bloque,Peso Inicial (g/ave),Peso 7d (g/ave),GDP 7d (g/ave/día),Cons. 7d (g/ave),C.A 7d,Mort 7d %,Peso 14d (g/ave),...,Cons. Tot 28d (g/ave),C.A acum 28d,Mort 28d %,Peso 35d (g/ave),GDP Total 35d (g/ave/día),Cons. Tot 35d (g/ave),C.A acum 35d,Mort 35d %,FEE,ProjectID
0,1,F,1,41.818182,188.181818,20.909091,141.363636,0.965839,0.000000,500.909091,...,2456.512131,1.342992,4.545455,2726.341463,76.700665,3860.542329,1.438074,4.545455,517.044204,FractalPronaca1
1,2,E,1,42.272727,186.190476,20.559678,139.152824,0.966891,4.545455,503.902439,...,2465.795100,1.325178,9.090909,2771.578947,77.980178,3835.687138,1.405371,11.363636,499.436443,FractalPronaca1
2,3,D,1,42.272727,195.813953,21.934461,147.325581,0.959518,2.272727,527.906977,...,2509.186047,1.339940,2.272727,2745.853659,77.245169,3871.190476,1.431875,4.545455,522.998919,FractalPronaca1
3,4,C,1,42.727273,191.363636,21.233766,140.000000,0.941896,0.000000,522.727273,...,2430.454545,1.321522,2.272727,2660.000000,74.779221,3789.413571,1.447848,2.272727,512.986983,FractalPronaca1
4,5,E,1,41.818182,191.818182,21.428571,144.090909,0.960606,0.000000,526.818182,...,2427.727273,1.338596,0.000000,2607.441860,73.303534,3750.835095,1.461958,0.000000,509.579060,FractalPronaca1

In [3]:
pronaca1[[i for i in pronaca1.columns if "Group FI" in i]].columns

Index([], dtype='object')

In [5]:

column_rename_map = {
    'ProjectID': 'ProjectID',
    'Bloque':'Block',
    'House': 'House',
    'Jaula': 'Pen',
    'Trat.': 'Treatment',
    
    'Peso Inicial (g/ave)':'BW_initial', 
    'Peso 7d (g/ave)':'BW_7', 
    'GDP 7d (g/ave/día)':'DBW_7', 
    'Cons. 7d (g/ave)':'FI_7', 
    'C.A 7d':'FCR_7', 
    'Mort 7d %':'MortPct_7', 
    'Peso 14d (g/ave)':'BW_14', 
    'GDP Total 14d (g/ave/día)':'DBW_14', 
    'Cons. Tot 14d (g/ave)':'FI_14', 
    'C.A acum 14d':'FCR_14', 
    'Mort 14d %':'MortPct_14', 
    'Peso 21d (g/ave)':'BW_21', 
    'GDP Total 21d (g/ave/día)':'DBW_21', 
    'Cons. Tot 21d (g/ave)':'FI_21', 
    'C.A acum 21d':'FCR_21', 
    'Mort 21d %':'MortPct_21', 
    'Peso 28d (g/ave)':'BW_28', 
    'GDP Total 28d (g/ave/día)':'DBW_28', 
    'Cons. Tot 28d (g/ave)':'FI_28', 
    'C.A acum 28d':'FCR_28', 
    'Mort 28d %':'MortPct_28', 
    'Peso 35d (g/ave)':'BW_35', 
    'GDP Total 35d (g/ave/día)':'DBW_35', 
    'Cons. Tot 35d (g/ave)':'FI_35', 
    'C.A acum 35d':'FCR_35', 
    'Mort 35d %':'MortPct_35', 
    'FEE':'FE_35',
     
}

pronaca1.rename(columns=column_rename_map, inplace=True)

In [6]:
pronaca1.columns

Index(['Pen', 'Treatment', 'Block', 'BW_initial', 'BW_7', 'DBW_7', 'FI_7',
       'FCR_7', 'MortPct_7', 'BW_14', 'DBW_14', 'FI_14', 'FCR_14',
       'MortPct_14', 'BW_21', 'DBW_21', 'FI_21', 'FCR_21', 'MortPct_21',
       'BW_28', 'DBW_28', 'FI_28', 'FCR_28', 'MortPct_28', 'BW_35', 'DBW_35',
       'FI_35', 'FCR_35', 'MortPct_35', 'FE_35', 'ProjectID'],
      dtype='object')

In [11]:
pronaca1.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideFractalPronaca1.csv', index=False)

In [7]:
pronaca1.head()

,Pen,Treatment,Block,BW_initial,BW_7,DBW_7,FI_7,FCR_7,MortPct_7,BW_14,...,FI_28,FCR_28,MortPct_28,BW_35,DBW_35,FI_35,FCR_35,MortPct_35,FE_35,ProjectID
0,1,F,1,41.818182,188.181818,20.909091,141.363636,0.965839,0.000000,500.909091,...,2456.512131,1.342992,4.545455,2726.341463,76.700665,3860.542329,1.438074,4.545455,517.044204,FractalPronaca1
1,2,E,1,42.272727,186.190476,20.559678,139.152824,0.966891,4.545455,503.902439,...,2465.795100,1.325178,9.090909,2771.578947,77.980178,3835.687138,1.405371,11.363636,499.436443,FractalPronaca1
2,3,D,1,42.272727,195.813953,21.934461,147.325581,0.959518,2.272727,527.906977,...,2509.186047,1.339940,2.272727,2745.853659,77.245169,3871.190476,1.431875,4.545455,522.998919,FractalPronaca1
3,4,C,1,42.727273,191.363636,21.233766,140.000000,0.941896,0.000000,522.727273,...,2430.454545,1.321522,2.272727,2660.000000,74.779221,3789.413571,1.447848,2.272727,512.986983,FractalPronaca1
4,5,E,1,41.818182,191.818182,21.428571,144.090909,0.960606,0.000000,526.818182,...,2427.727273,1.338596,0.000000,2607.441860,73.303534,3750.835095,1.461958,0.000000,509.579060,FractalPronaca1

In [9]:
pronaca1 = pronaca1[['ProjectID', 'Pen',  

               'BW_35', 'FCR_35'

             
             
               
             ]]
pronaca1.head()

         ProjectID  Pen        BW_35    FCR_35
0  FractalPronaca1    1  2726.341463  1.438074
1  FractalPronaca1    2  2771.578947  1.405371
2  FractalPronaca1    3  2745.853659  1.431875
3  FractalPronaca1    4  2660.000000  1.447848
4  FractalPronaca1    5  2607.441860  1.461958

In [12]:
column_rename_map = {'BW_35':'BW', 
                     'FCR_35':'FCR'}
pronaca1["Age"] = '34'

pronaca1.rename(columns=column_rename_map, inplace=True)
pronaca1.head()

         ProjectID  Pen           BW       FCR Age
0  FractalPronaca1    1  2726.341463  1.438074  34
1  FractalPronaca1    2  2771.578947  1.405371  34
2  FractalPronaca1    3  2745.853659  1.431875  34
3  FractalPronaca1    4  2660.000000  1.447848  34
4  FractalPronaca1    5  2607.441860  1.461958  34

In [14]:
pronaca1

          ProjectID  Pen           BW       FCR Age
0   FractalPronaca1    1  2726.341463  1.438074  34
1   FractalPronaca1    2  2771.578947  1.405371  34
2   FractalPronaca1    3  2745.853659  1.431875  34
3   FractalPronaca1    4  2660.000000  1.447848  34
4   FractalPronaca1    5  2607.441860  1.461958  34
..              ...  ...          ...       ...  ..
59  FractalPronaca1   60  2635.609756  1.448007  34
60  FractalPronaca1   61  2672.195122  1.443567  34
61  FractalPronaca1   62  2717.777778  1.418183  34
62  FractalPronaca1   63  2757.500000  1.409180  34
63  FractalPronaca1   64  2678.947368  1.449989  34

[64 rows x 5 columns]

In [15]:
pronaca1.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/DE1/LongFormat_Performance/LongFormatFractalPronaca1.csv', index=False)

# FractalSPRG1

In [28]:
SPRG1 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/SPRG1 (03.05.21) AB092020-92 Performance Data FINAL.xlsx", "stats") 
SPRG1["ProjectID"] = 'FractalSPRG1'
print(list(SPRG1.columns))
SPRG1.head()

['trt', 'blk', 'pen', 'fi14', 'fcr14', 'non14', 'wt14', 'fi22', 'fcr22', 'non22', 'wt22', 'fi28', 'fcr28', 'non28', 'wt28', 'permort', 'Nemort', 'Nelesion', 'FITC', 'ProjectID']

,trt,blk,pen,fi14,fcr14,non14,wt14,fi22,fcr22,non22,wt22,fi28,fcr28,non28,wt28,permort,Nemort,Nelesion,FITC,ProjectID
0,3,1,1,4.60,1.464968,1.464968,0.3140,10.45,1.612654,2.228145,0.687333,15.10,1.601273,1.976440,1.179000,30,30,1,0.546695,FractalSPRG1
1,1,1,2,4.40,1.426256,1.426256,0.3085,10.75,1.505602,1.505602,0.736833,18.35,1.569718,1.569718,1.242389,0,0,0,0.504937,FractalSPRG1
2,2,1,3,4.65,1.524590,1.524590,0.3050,10.20,1.597494,2.402827,0.735000,13.85,1.550084,2.038263,1.245000,40,40,0,0.558033,FractalSPRG1
3,4,1,4,5.25,1.456311,1.456311,0.3605,11.25,1.488095,1.488095,0.749944,17.75,1.496627,1.496627,1.227722,0,0,1,0.425439,FractalSPRG1
4,3,2,5,4.90,1.498471,1.498471,0.3270,10.05,1.725322,5.303430,0.877000,11.90,1.730909,4.040747,1.402000,70,60,1,0.500753,FractalSPRG1

In [ ]:
E347[[i for i in E347.columns if "Group FI" in i]].columns

In [29]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'pen': 'Pen',
    'blk':'Block',
    'trt': 'Treatment',

    
    'fi14':'FI_14', 
    'fcr14':'FCR_14', 
    'non14':'non14', 
    'wt14':'BW_14', 
    'fi22':'FI_22', 
    'fcr22':'FCR_22', 
    'non22':'BW_22', 
    'wt22':'BW_22', 
    'fi28':'FI_28', 
    'fcr28':'FCR_28', 
    'non28':'non28', 
    'wt28':'BW_28', 
    'permort':'MortPct_28', 
    'Nemort':'NEMortPct_28', 
    'Nelesion':'NE_', 
    'FITC':'FITC_28'
}

SPRG1.rename(columns=column_rename_map, inplace=True)

In [30]:
SPRG1.columns

Index(['Treatment', 'Block', 'Pen', 'FI_14', 'FCR_14', 'non14', 'BW_14',
       'FI_22', 'FCR_22', 'BW_22', 'BW_22', 'FI_28', 'FCR_28', 'non28',
       'BW_28', 'MortPct_28', 'NEMortPct_28', 'NE_', 'FITC_28', 'ProjectID'],
      dtype='object')

In [31]:
SPRG1.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideFractalSPRG1.csv', index=False)

# FractalSPRG2

In [5]:
SPRG2 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Performance_ExpFarm/SPRG2 (10.31.23) ANE052023-55 Performance Data FINAL.xlsx", "stats") 
SPRG2["ProjectID"] = 'FractalSPRG2'
print(list(SPRG2.columns))
SPRG2.head()

['Trt', 'Blk', 'Pen', 'FI14', 'aFCR14', 'nFCR14', 'WtGain14', 'FI22', 'aFCR22', 'nFCR22', 'WtGain22', 'FI28', 'aFCR28', 'nFCR28', 'WtGain28', 'TotMort', 'NEMort', 'NElesion', 'ProjectID']

,Trt,Blk,Pen,FI14,aFCR14,nFCR14,WtGain14,FI22,aFCR22,nFCR22,WtGain22,FI28,aFCR28,nFCR28,WtGain28,TotMort,NEMort,NElesion,ProjectID
0,1,1,1,3.75,1.670379,1.704545,0.248333,8.35,1.655104,1.670000,0.546250,12.90,1.730382,1.984615,0.990000,30,0,0,FractalSPRG2
1,4,1,2,4.75,1.466049,1.466049,0.324000,10.05,1.665286,3.582888,0.730667,11.40,1.788235,4.550898,0.964000,70,60,0,FractalSPRG2
2,2,1,3,4.55,1.430818,1.430818,0.318000,10.05,1.651602,2.273756,0.638000,13.40,1.802286,2.617187,0.913000,40,40,1,FractalSPRG2
3,3,1,4,3.50,1.120000,1.198630,0.328667,8.85,1.328829,1.505102,0.740571,13.95,1.400602,1.519608,1.212000,20,10,1,FractalSPRG2
4,2,2,5,4.10,1.411360,1.411360,0.290500,9.45,1.473110,2.010638,0.665500,14.40,1.562670,1.920000,1.132167,30,30,1,FractalSPRG2

In [6]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Pen': 'Pen',
    'Trt': 'Treatment',
    'Blk':'Block',

    
    'FI14':'FI_14', 
    'aFCR14':'aFCR_14', 
    'nFCR14':'FCR_14', 
    'WtGain14':'WG_14', 
    'FI22':'FI_22', 
    'aFCR22':'aFCR_22', 
    'nFCR22':'FCR_22', 
    'WtGain22':'WG_22', 
    'FI28':'FI_28', 
    'aFCR28':'aFCR_28', 
    'nFCR28':'FCR_28', 
    'WtGain28':'WG_28', 
    'TotMort':'MortPct_28', 
    'NEMort':'NEMortPct_28', 
    'NElesion':'NE'
}

SPRG2.rename(columns=column_rename_map, inplace=True)

In [7]:
SPRG2.columns

Index(['Treatment', 'Block', 'Pen', 'FI_14', 'aFCR_14', 'FCR_14', 'WG_14',
       'FI_22', 'aFCR_22', 'FCR_22', 'WG_22', 'FI_28', 'aFCR_28', 'FCR_28',
       'WG_28', 'MortPct_28', 'NEMortPct_28', 'NE', 'ProjectID'],
      dtype='object')

In [25]:
SPRG2.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideFractalSPRG2.csv', index=False)

In [9]:
SPRG2.head()

,Treatment,Block,Pen,FI_14,aFCR_14,FCR_14,WG_14,FI_22,aFCR_22,FCR_22,WG_22,FI_28,aFCR_28,FCR_28,WG_28,MortPct_28,NEMortPct_28,NE,ProjectID
0,1,1,1,3.75,1.670379,1.704545,0.248333,8.35,1.655104,1.670000,0.546250,12.90,1.730382,1.984615,0.990000,30,0,0,FractalSPRG2
1,4,1,2,4.75,1.466049,1.466049,0.324000,10.05,1.665286,3.582888,0.730667,11.40,1.788235,4.550898,0.964000,70,60,0,FractalSPRG2
2,2,1,3,4.55,1.430818,1.430818,0.318000,10.05,1.651602,2.273756,0.638000,13.40,1.802286,2.617187,0.913000,40,40,1,FractalSPRG2
3,3,1,4,3.50,1.120000,1.198630,0.328667,8.85,1.328829,1.505102,0.740571,13.95,1.400602,1.519608,1.212000,20,10,1,FractalSPRG2
4,2,2,5,4.10,1.411360,1.411360,0.290500,9.45,1.473110,2.010638,0.665500,14.40,1.562670,1.920000,1.132167,30,30,1,FractalSPRG2

In [11]:
SPRG2 = SPRG2[['ProjectID', 'Treatment', 'Pen',  

               'WG_14', 'aFCR_22'

             
             
               
             ]]
SPRG2.head()

      ProjectID  Treatment  Pen     WG_14   aFCR_22
0  FractalSPRG2          1    1  0.248333  1.655104
1  FractalSPRG2          4    2  0.324000  1.665286
2  FractalSPRG2          2    3  0.318000  1.651602
3  FractalSPRG2          3    4  0.328667  1.328829
4  FractalSPRG2          2    5  0.290500  1.473110

In [13]:
column_rename_map = {'WG_14':'BW', 
                     'aFCR_22':'FCR'}
SPRG2["Age"] = '22'

SPRG2.rename(columns=column_rename_map, inplace=True)
SPRG2.head()

/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_1697/1626235210.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  SPRG2["Age"] = '22'
/var/folders/s7/v76xrt891jl1w29h38yvj5n00000gp/T/ipykernel_1697/1626235210.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  SPRG2.rename(columns=column_rename_map, inplace=True)

      ProjectID  Treatment  Pen        BW       FCR Age
0  FractalSPRG2          1    1  0.248333  1.655104  22
1  FractalSPRG2          4    2  0.324000  1.665286  22
2  FractalSPRG2          2    3  0.318000  1.651602  22
3  FractalSPRG2          3    4  0.328667  1.328829  22
4  FractalSPRG2          2    5  0.290500  1.473110  22

In [14]:
SPRG2.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/DE1/LongFormat_Performance/LongFormatFractalSPRG2.csv', index=False)

# FractalFieldale1

In [38]:
fieldale = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/Fieldale Copia de 051523 Fractal Pen Data_for Allura.xlsx", "data") 
fieldale["ProjectID"] = 'FractalFieldale1'
print(list(fieldale.columns))
fieldale.head()

['Pen', 'TRT', 'BLK', 'Gender', 'Day 0 Date', 'Starter FCRm', 'Starter FCRm + bw 1.45', 'Grower FCRm', 'Grower FCRm + bw 3.50', 'Finisher FCRm', 'Finisher FCRm + bw 5.75', 'WD FCRm', 'WD FCRm + bw 7.55', 'Overall FCRm', 'Overall FCRm + bw 7.55', 'ProjectID']

,Pen,TRT,BLK,Gender,Day 0 Date,Starter FCRm,Starter FCRm + bw 1.45,Grower FCRm,Grower FCRm + bw 3.50,Finisher FCRm,Finisher FCRm + bw 5.75,WD FCRm,WD FCRm + bw 7.55,Overall FCRm,Overall FCRm + bw 7.55,ProjectID
0,1,A,1,Male,2023-02-24,1.291858,1.307096,1.546512,1.561912,1.884434,1.898656,2.026798,2.029622,1.715915,1.718739,FractalFieldale1
1,2,B,1,Male,2023-02-24,1.301593,1.318736,1.529554,1.547869,1.785235,1.794124,1.945983,1.937983,1.669771,1.661771,FractalFieldale1
2,3,A,2,Male,2023-02-24,1.354373,1.381230,1.483436,1.512324,1.679225,1.682284,1.995370,1.994120,1.643011,1.641761,FractalFieldale1
3,4,B,2,Male,2023-02-24,1.365004,1.388242,1.596513,1.620303,1.775556,1.792889,1.917827,1.923077,1.694044,1.699294,FractalFieldale1
4,5,A,3,Male,2023-02-24,1.326533,1.344533,1.521951,1.541109,1.722282,1.724949,1.864407,1.834657,1.640096,1.610346,FractalFieldale1

In [39]:
fieldale = fieldale[['Pen', 'TRT', 'BLK','ProjectID',
             
             'Starter FCRm', 'Starter FCRm + bw 1.45', 'Grower FCRm', 
             'Grower FCRm + bw 3.50', 'Finisher FCRm', 'Finisher FCRm + bw 5.75', 
             'WD FCRm', 'WD FCRm + bw 7.55', 'Overall FCRm', 'Overall FCRm + bw 7.55'
               
               
               
             ]]
fieldale.head()

,Pen,TRT,BLK,ProjectID,Starter FCRm,Starter FCRm + bw 1.45,Grower FCRm,Grower FCRm + bw 3.50,Finisher FCRm,Finisher FCRm + bw 5.75,WD FCRm,WD FCRm + bw 7.55,Overall FCRm,Overall FCRm + bw 7.55
0,1,A,1,FractalFieldale1,1.291858,1.307096,1.546512,1.561912,1.884434,1.898656,2.026798,2.029622,1.715915,1.718739
1,2,B,1,FractalFieldale1,1.301593,1.318736,1.529554,1.547869,1.785235,1.794124,1.945983,1.937983,1.669771,1.661771
2,3,A,2,FractalFieldale1,1.354373,1.381230,1.483436,1.512324,1.679225,1.682284,1.995370,1.994120,1.643011,1.641761
3,4,B,2,FractalFieldale1,1.365004,1.388242,1.596513,1.620303,1.775556,1.792889,1.917827,1.923077,1.694044,1.699294
4,5,A,3,FractalFieldale1,1.326533,1.344533,1.521951,1.541109,1.722282,1.724949,1.864407,1.834657,1.640096,1.610346

In [40]:
column_rename_map = {
    'ProjectID': 'ProjectID',
    'Pen': 'Pen',
    'TRT': 'Treatment',
    'BLK':'Block',

    
    'Starter FCRm':'FCR_17', 
    'Starter FCRm + bw 1.45':'aFCR_17', 
    'Grower FCRm':'FCR_28', 
    'Grower FCRm + bw 3.50':'aFCR_28', 
    'Finisher FCRm':'FCR_38', 
    'Finisher FCRm + bw 5.75':'aFCR_38', 
    'WD FCRm':'FCR_47', 
    'WD FCRm + bw 7.55':'aFCR_47', 
    'Overall FCRm':'FCR_0_47', 
    'Overall FCRm + bw 7.55':'aFCR_0_47'
}

fieldale.rename(columns=column_rename_map, inplace=True)

In [41]:
fieldale.columns

Index(['Pen', 'Treatment', 'Block', 'ProjectID', 'FCR_17', 'aFCR_17', 'FCR_28',
       'aFCR_28', 'FCR_38', 'aFCR_38', 'FCR_47', 'aFCR_47', 'FCR_0_47',
       'aFCR_0_47'],
      dtype='object')

In [42]:
fieldale.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideFractaFieldale1.csv', index=False)

In [ ]:
E347 = pd.read_excel("/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/E-347 Niveles de Sodio 24-01-2022.xlsx", "Performance Data") 
E347["ProjectID"] = 'E347'
print(list(E347.columns))
E347.head()
E347[[i for i in E347.columns if "Group FI" in i]].columns


E347 = E347[['ProjectID', 'House', 'Pen', 'Blind Trts ', '# Ini birds 1d',
             
             'Group BWh (g)', 'Group BW7(g)', 'Group BW14(g)', 'Group BW21 (g)', 'Group BW28(g)', 'Group BW 35 (g)', 'Group BW 42d (g)',
             
             
             '# Fnl birds 7d', 'Fnl birds 14d', '# Fnl birds 21d', '# Fnl birds 28d', '# Fnl birds 35d', '# Fnl birds 42d',

              
               
             'Mortality weight 0-6d (g)', 'Mortality weight 7d (g)',
           'Mortality weight 8-13d (g)', 'Mortality weight 14d',
           'Mortality weight 15-20d (g)', 'Mortality weight 21d',
           'Mortality weight 22-27d (g)', 'Mortality weight 28d (g)',
           'Mortality weight 29-34d (g)', 'Mortality weight 35d (g)',
           'Mortality weight 36-41d (g)', 'Mortality weight 42d (g)',
             
            'Culling 0-6d', 'Culling weight 0-6d (g)', 'Culling 7d',
       'Culling weight 7d (g)', 'Culling 8-13d',
       'Culling weight 8-13d (g)', 'Culling 14d', 'Culling weight 14d',
        'Culling 15-20d', 'Culling weight 15-20d (g)',
       'Culling 21d', 'Culling weight 21d', 
       'Culling 22-27d', 'Culling weight 22-27d (g)', 'Culling 28d',
       'Culling weight 28d (g)', 'Culling 29-34d',
       'Culling weight 29-34d (g)', 'Culling 35d', 'Culling weight 35d',
        'Culling 36-41d', 'Culling weight 36-41d (g)',
       'Culling 42d', 'Culling weight 42d (g)', 

               

             'Group FI 0-7d (g)', 'Group FI 8-14d (g)', 'Group FI 15-21d (g)',
       'Group FI 22-28d (g)', 'Group FI 29-35d (g)', 'Group FI 36-42d (g)'
               
               
               
             ]]
E347.head()




column_rename_map = {
    'ProjectID': 'ProjectID',
    'House': 'House',
    'Pen': 'Pen',
    'Blind Trts ': 'Treatment',
    '# Ini birds 1d':'Init_Birds_D1', 


    'Group BWh (g)':'GBW_initial', 
    'Group BW7(g)':'GBW_7', 
    'Group BW14(g)':'GBW_14', 
    'Group BW21 (g)':'GBW_21', 
    'Group BW28(g)':'GBW_28', 
    'Group BW 35 (g)':'GBW_35', 
    'Group BW 42d (g)':'GBW_42',
             
             
     '# Fnl birds 7d':'Fnl_Birds_D7', 
    'Fnl birds 14d':'Fnl_Birds_D14', 
    '# Fnl birds 21d':'Fnl_Birds_D21', 
    '# Fnl birds 28d':'Fnl_Birds_D27', 
    '# Fnl birds 35d':'Fnl_Birds_D35', 
    '# Fnl birds 42d':'Fnl_Birds_D42',

              
               
     'Mortality weight 0-6d (g)':'Mort_Wt_D6', 
    'Mortality weight 7d (g)':'Mort_Wt_D7',
     'Mortality weight 8-13d (g)':'Mort_Wt_D13', 
    'Mortality weight 14d':'Mort_Wt_D14',
     'Mortality weight 15-20d (g)':'Mort_Wt_D20', 
    'Mortality weight 21d':'Mort_Wt_D21',
    'Mortality weight 22-27d (g)':'Mort_Wt_D26', 
    'Mortality weight 28d (g)':'Mort_Wt_D27',
   'Mortality weight 29-34d (g)':'Mort_Wt_D34', 
    'Mortality weight 35d (g)':'Mort_Wt_D35',
   'Mortality weight 36-41d (g)':'Mort_Wt_D41', 
    'Mortality weight 42d (g)':'Mort_Wt_D42',
     
     'Culling 0-6d':'Cull_D6', 
    'Culling weight 0-6d (g)':'Cull_Wt_D6', 
    'Culling 7d':'Cull_D7',
   'Culling weight 7d (g)':'Cull_Wt_D7', 
    'Culling 8-13d':'Cull_D13',
   'Culling weight 8-13d (g)':'Cull_Wt_D13', 
    'Culling 14d':'Cull_D14', 
    'Culling weight 14d':'Cull_Wt_D14',
    'Culling 15-20d':'Cull_D20', 
    'Culling weight 15-20d (g)':'Cull_Wt_D20',
   'Culling 21d':'Cull_D21', 
    'Culling weight 21d':'Cull_Wt_D21', 
   'Culling 22-27d':'Cull_D26', 
    'Culling weight 22-27d (g)':'Cull_Wt_D26', 
    'Culling 28d':'Cull_D27',
   'Culling weight 28d (g)':'Cull_Wt_D27', 
    'Culling 29-34d':'Cull_D34',
   'Culling weight 29-34d (g)':'Cull_Wt_D34', 
    'Culling 35d':'Cull_D35', 
    'Culling weight 35d':'Cull_Wt_D35',
    'Culling 36-41d':'Cull_D41', 
    'Culling weight 36-41d (g)':'Cull_Wt_D41',
   'Culling 42d':'Cull_D42', 
    'Culling weight 42d (g)':'Cull_Wt_D42', 

       

     'Group FI 0-7d (g)':'GFI_D7', 
    'Group FI 8-14d (g)':'GFI_D14', 
    'Group FI 15-21d (g)':'GFI_D21',
   'Group FI 22-28d (g)':'GFI_D28', 
    'Group FI 29-35d (g)':'GFI_D35', 
    'Group FI 36-42d (g)':'GFI_D42'

    
    
   


    
}

E347.rename(columns=column_rename_map, inplace=True)
E347.head()


E351.to_csv('/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl/WideE351.csv', index=False)

In [456]:
# Definir las columnas finales a revisar
final_columns = [
    'ProjectID', 'House', 'Pen', 'TreatmentNumber', 'Treatment',
    'GBW_initial', 'GBW_7', 'GBW_14', 'GBW_21', 'GBW_28', 'GBW_35', 'GBW_42',
    'Init_Birds_D1', 'Fnl_Birds_D7', 'Fnl_Birds_D14', 'Fnl_Birds_D21', 'Fnl_Birds_D28', 
    'Fnl_Birds_D35', 'Fnl_Birds_D42', 'Mort_Wt_D7', 'Mort_Wt_D14', 'Mort_Wt_D21',
    'Mort_Wt_D28', 'Mort_Wt_D35', 'Mort_Wt_D42', 'Cull_D7', 'Cull_D14', 'Cull_D21',
    'Cull_D28', 'Cull_D35', 'Cull_D42', 'Cull_Wt_D7', 'Cull_Wt_D14', 'Cull_Wt_D21',
    'Cull_Wt_D28', 'Cull_Wt_D35', 'Cull_Wt_D42', 'Samp_D7', 'Samp_D14', 'Samp_D21',
    'Samp_D22', 'Samp_D29', 'Samp_D42', 'Samp_Wt_D7', 'Samp_Wt_D14', 'Samp_Wt_D21',
    'Samp_Wt_D22', 'Samp_Wt_D29', 'Samp_Wt_D42', 'GFI_0_7D', 'GFI_8_14D', 
    'GFI_15_21D', 'GFI_22_28D', 'GFI_29_35D', 'GFI_36_42D'
]

# Carpeta con los archivos
etl_folder = "/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/datawarehouse_performance_etl"

# Lista para almacenar los resultados
results = []

# Iterar sobre los archivos en la carpeta
for filename in os.listdir(etl_folder):
    if filename.startswith("Wide") and filename.endswith(".csv"):
        filepath = os.path.join(etl_folder, filename)
        project_name = filename.replace("Wide", "").replace(".csv", "").strip()
        
        # Leer el archivo CSV
        try:
            df = pd.read_csv(filepath)
            # Crear un registro para este archivo
            row = {"Project": project_name}
            
            # Verificar cada columna en las columnas finales
            for col in final_columns:
                row[col] = 1 if col in df.columns else 0
            
            # Agregar el registro a los resultados
            results.append(row)
        except Exception as e:
            print(f"Error al procesar {filename}: {e}")

# Crear un DataFrame con los resultados
results_df = pd.DataFrame(results)

# Guardar los resultados en un archivo Excel
output_path = "/Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/summary_results.xlsx"
results_df.to_excel(output_path, index=False)
print(f"Archivo guardado en: {output_path}")

Archivo guardado en: /Users/sbedoya/Documents/siwa_git/Reports_sebas/performance etl/ALL ETL performance/summary_results.xlsx